<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Invoice {{ $invoiceNumber }}</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 12px;
            color: #1f2937;
            margin: 0;
            padding: 24px;
        }

        .header {
            margin-bottom: 18px;
        }

        .title {
            font-size: 24px;
            font-weight: 700;
            margin: 0 0 6px;
        }

        .meta {
            margin: 2px 0;
            color: #4b5563;
        }

        .section-title {
            margin: 20px 0 8px;
            font-size: 14px;
            font-weight: 700;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th, td {
            border: 1px solid #d1d5db;
            padding: 8px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #f3f4f6;
            font-weight: 700;
        }

        .text-right {
            text-align: right;
        }

        .summary {
            width: 48%;
            margin-left: auto;
            margin-top: 12px;
        }

        .summary td {
            border: none;
            padding: 4px 0;
        }

        .footer-note {
            margin-top: 22px;
            color: #6b7280;
            font-size: 11px;
        }
    </style>
</head>
<body>
@php
    $shipping = $order->shipping;
    $promotion = $order->promotion;
    $subtotal = (int) ($order->subtotal_minor ?? $order->total_harga);
    $discount = (int) ($order->discount_minor ?? $promotion?->discount_minor ?? 0);
    $shippingCost = (int) ($order->shipping_minor ?? 0);
    $tax = (int) ($order->tax_minor ?? 0);
    $total = (int) ($order->total_harga_minor ?? $order->total_harga);
@endphp

<div class="header">
    <p class="title">Invoice</p>
    <p class="meta">Invoice Number: {{ $invoiceNumber }}</p>
    <p class="meta">Order ID: #{{ $order->id }}</p>
    <p class="meta">Issued At: {{ $issuedAt }}</p>
    <p class="meta">Order Status: {{ strtoupper($order->status) }}</p>
</div>

<p class="section-title">Items</p>
<table>
    <thead>
        <tr>
            <th style="width: 42%;">Product</th>
            <th style="width: 12%;">Qty</th>
            <th style="width: 23%;" class="text-right">Price</th>
            <th style="width: 23%;" class="text-right">Subtotal</th>
        </tr>
    </thead>
    <tbody>
    @foreach ($order->details as $detail)
        @php
            $itemSubtotal = (int) ($detail->qty * $detail->harga);
        @endphp
        <tr>
            <td>{{ $detail->produkItem?->nama ?? ('Produk #'.$detail->produk_item_id) }}</td>
            <td>{{ $detail->qty }}</td>
            <td class="text-right">Rp {{ number_format((int) $detail->harga, 0, ',', '.') }}</td>
            <td class="text-right">Rp {{ number_format($itemSubtotal, 0, ',', '.') }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

<table class="summary">
    <tr>
        <td>Subtotal</td>
        <td class="text-right">Rp {{ number_format($subtotal, 0, ',', '.') }}</td>
    </tr>
    <tr>
        <td>Discount</td>
        <td class="text-right">Rp {{ number_format($discount, 0, ',', '.') }}</td>
    </tr>
    <tr>
        <td>Shipping</td>
        <td class="text-right">Rp {{ number_format($shippingCost, 0, ',', '.') }}</td>
    </tr>
    <tr>
        <td>Tax</td>
        <td class="text-right">Rp {{ number_format($tax, 0, ',', '.') }}</td>
    </tr>
    <tr>
        <td><strong>Total</strong></td>
        <td class="text-right"><strong>Rp {{ number_format($total, 0, ',', '.') }}</strong></td>
    </tr>
</table>

<p class="section-title">Shipping Information</p>
<table>
    <tr>
        <th style="width: 25%;">Name</th>
        <td>{{ $shipping?->nama ?? '-' }}</td>
    </tr>
    <tr>
        <th>Phone</th>
        <td>{{ $shipping?->telepon ?? '-' }}</td>
    </tr>
    <tr>
        <th>Address</th>
        <td>{{ $shipping?->alamat ?? '-' }}</td>
    </tr>
    <tr>
        <th>City</th>
        <td>{{ $shipping?->kota ?? '-' }}</td>
    </tr>
    <tr>
        <th>Postal Code</th>
        <td>{{ $shipping?->kode_pos ?? '-' }}</td>
    </tr>
</table>

<p class="section-title">Payment Information</p>
<table>
    <tr>
        <th style="width: 25%;">Method</th>
        <td>{{ $order->payment?->metode ?? '-' }}</td>
    </tr>
    <tr>
        <th>Status</th>
        <td>{{ $order->payment?->status ?? 'pending' }}</td>
    </tr>
    <tr>
        <th>Paid At</th>
        <td>{{ $order->payment?->paid_at?->toDateTimeString() ?? '-' }}</td>
    </tr>
</table>

<p class="footer-note">Generated by WebApp backend.</p>
</body>
</html>
