// Auto-generated by routesync. Do not edit manually.
import { z } from 'zod'

export const ApiSchema = {
  RegisterCreate: z.object({
    name: z.string(),
    email: z.string(),
    password: z.string(),
  }),
  LoginCreate: z.object({
    email: z.string(),
    password: z.string(),
  }),
  OauthRedirectGet: z.object({
    redirectTo: z.string().optional().nullable(),
  }),
  SocialLoginCreate: z.object({
    provider: z.enum(['google', 'facebook', 'apple']),
    providerUserId: z.string(),
    email: z.string(),
    name: z.string().optional().nullable(),
    avatarUrl: z.string().optional().nullable(),
  }),
  ForgotPasswordCreate: z.object({
    email: z.string(),
  }),
  ResetPasswordCreate: z.object({
    email: z.string(),
    token: z.string(),
    password: z.string(),
  }),
  ProdukReviewsCreate: z.object({
    rating: z.number(),
    title: z.string().optional().nullable(),
    comment: z.string().optional().nullable(),
  }),
  ProfileUpdate: z.object({
    name: z.string(),
    email: z.string(),
  }),
  CartItemsCreate: z.object({
    produkItemId: z.string(),
    qty: z.number(),
  }),
  CartItemsUpdate: z.object({
    qty: z.number(),
  }),
  CartPromoCreate: z.object({
    code: z.string(),
  }),
  CheckoutCreate: z.object({
    items: z.array(z.object({
    produkItemId: z.string(),
    qty: z.number(),
  })).optional(),
    shippingNama: z.string().optional().nullable(),
    shippingTelepon: z.string().optional().nullable(),
    shippingAlamat: z.string().optional().nullable(),
    shippingKota: z.string().optional().nullable(),
    shippingKodePos: z.string().optional().nullable(),
  }),
  BuyNowCreate: z.object({
    produkItemId: z.string(),
    qty: z.number(),
    shippingNama: z.string().optional().nullable(),
    shippingTelepon: z.string().optional().nullable(),
    shippingAlamat: z.string().optional().nullable(),
    shippingKota: z.string().optional().nullable(),
    shippingKodePos: z.string().optional().nullable(),
  }),
  WishlistCreate: z.object({
    produkItemId: z.string(),
  }),
  PaymentCreate: z.object({
    metode: z.string(),
    detail: z.array(z.unknown()).optional().nullable(),
    provider: z.enum(['mock', 'midtrans']).optional().nullable(),
    providerTxnId: z.string().optional().nullable(),
    idempotencyKey: z.string().optional().nullable(),
    gatewayCode: z.string().optional().nullable(),
    gatewayMessage: z.string().optional().nullable(),
  }),
  AdminProdukCreate: z.object({
    nama: z.string(),
    deskripsi: z.string().optional().nullable(),
    gambar: z.string().optional().nullable(),
    categoryId: z.string(),
    harga: z.number(),
    stok: z.number(),
    rating: z.number().optional().nullable(),
    jumlahReview: z.number().optional().nullable(),
  }),
}

export type ApiFormValues = {
  RegisterCreate: z.infer<typeof ApiSchema.RegisterCreate>
  LoginCreate: z.infer<typeof ApiSchema.LoginCreate>
  OauthRedirectGet: z.infer<typeof ApiSchema.OauthRedirectGet>
  SocialLoginCreate: z.infer<typeof ApiSchema.SocialLoginCreate>
  ForgotPasswordCreate: z.infer<typeof ApiSchema.ForgotPasswordCreate>
  ResetPasswordCreate: z.infer<typeof ApiSchema.ResetPasswordCreate>
  ProdukReviewsCreate: z.infer<typeof ApiSchema.ProdukReviewsCreate>
  ProfileUpdate: z.infer<typeof ApiSchema.ProfileUpdate>
  CartItemsCreate: z.infer<typeof ApiSchema.CartItemsCreate>
  CartItemsUpdate: z.infer<typeof ApiSchema.CartItemsUpdate>
  CartPromoCreate: z.infer<typeof ApiSchema.CartPromoCreate>
  CheckoutCreate: z.infer<typeof ApiSchema.CheckoutCreate>
  BuyNowCreate: z.infer<typeof ApiSchema.BuyNowCreate>
  WishlistCreate: z.infer<typeof ApiSchema.WishlistCreate>
  PaymentCreate: z.infer<typeof ApiSchema.PaymentCreate>
  AdminProdukCreate: z.infer<typeof ApiSchema.AdminProdukCreate>
}

export const ApiDefaultValues = {
  registerCreate: {} as ApiFormValues['RegisterCreate'],
  loginCreate: {} as ApiFormValues['LoginCreate'],
  oauthRedirectGet: {} as ApiFormValues['OauthRedirectGet'],
  socialLoginCreate: {} as ApiFormValues['SocialLoginCreate'],
  forgotPasswordCreate: {} as ApiFormValues['ForgotPasswordCreate'],
  resetPasswordCreate: {} as ApiFormValues['ResetPasswordCreate'],
  produkReviewsCreate: {} as ApiFormValues['ProdukReviewsCreate'],
  profileUpdate: {} as ApiFormValues['ProfileUpdate'],
  cartItemsCreate: {} as ApiFormValues['CartItemsCreate'],
  cartItemsUpdate: {} as ApiFormValues['CartItemsUpdate'],
  cartPromoCreate: {} as ApiFormValues['CartPromoCreate'],
  checkoutCreate: {} as ApiFormValues['CheckoutCreate'],
  buyNowCreate: {} as ApiFormValues['BuyNowCreate'],
  wishlistCreate: {} as ApiFormValues['WishlistCreate'],
  paymentCreate: {} as ApiFormValues['PaymentCreate'],
  adminProdukCreate: {} as ApiFormValues['AdminProdukCreate'],
}

export type ApiFormIndex = keyof ApiFormValues

export const ApiFormValidators = {
  validateRegisterCreate: (data: unknown): ApiFormValues['RegisterCreate'] => ApiSchema.RegisterCreate.parse(data),
  validateLoginCreate: (data: unknown): ApiFormValues['LoginCreate'] => ApiSchema.LoginCreate.parse(data),
  validateOauthRedirectGet: (data: unknown): ApiFormValues['OauthRedirectGet'] => ApiSchema.OauthRedirectGet.parse(data),
  validateSocialLoginCreate: (data: unknown): ApiFormValues['SocialLoginCreate'] => ApiSchema.SocialLoginCreate.parse(data),
  validateForgotPasswordCreate: (data: unknown): ApiFormValues['ForgotPasswordCreate'] => ApiSchema.ForgotPasswordCreate.parse(data),
  validateResetPasswordCreate: (data: unknown): ApiFormValues['ResetPasswordCreate'] => ApiSchema.ResetPasswordCreate.parse(data),
  validateProdukReviewsCreate: (data: unknown): ApiFormValues['ProdukReviewsCreate'] => ApiSchema.ProdukReviewsCreate.parse(data),
  validateProfileUpdate: (data: unknown): ApiFormValues['ProfileUpdate'] => ApiSchema.ProfileUpdate.parse(data),
  validateCartItemsCreate: (data: unknown): ApiFormValues['CartItemsCreate'] => ApiSchema.CartItemsCreate.parse(data),
  validateCartItemsUpdate: (data: unknown): ApiFormValues['CartItemsUpdate'] => ApiSchema.CartItemsUpdate.parse(data),
  validateCartPromoCreate: (data: unknown): ApiFormValues['CartPromoCreate'] => ApiSchema.CartPromoCreate.parse(data),
  validateCheckoutCreate: (data: unknown): ApiFormValues['CheckoutCreate'] => ApiSchema.CheckoutCreate.parse(data),
  validateBuyNowCreate: (data: unknown): ApiFormValues['BuyNowCreate'] => ApiSchema.BuyNowCreate.parse(data),
  validateWishlistCreate: (data: unknown): ApiFormValues['WishlistCreate'] => ApiSchema.WishlistCreate.parse(data),
  validatePaymentCreate: (data: unknown): ApiFormValues['PaymentCreate'] => ApiSchema.PaymentCreate.parse(data),
  validateAdminProdukCreate: (data: unknown): ApiFormValues['AdminProdukCreate'] => ApiSchema.AdminProdukCreate.parse(data),
}

export type ApiFormErrors<T extends ApiFormIndex> = Partial<Record<keyof ApiFormValues[T], string>>