// Auto-generated by routesync. Do not edit manually.
import { z } from 'zod'

export const CategorySchema = z.object({
  id: z.number(),
  nama: z.string(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type CategoryApiResponse = z.infer<typeof CategorySchema>
export const validateCategory = (payload: unknown): CategoryApiResponse => CategorySchema.parse(payload)

export const OrderSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  total_harga: z.number(),
  status: z.union([z.literal('pending'), z.literal('paid'), z.literal('canceled')]),
  order_number: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderApiResponse = z.infer<typeof OrderSchema>
export const validateOrder = (payload: unknown): OrderApiResponse => OrderSchema.parse(payload)

export const OrderAmountSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  subtotal_minor: z.number(),
  shipping_minor: z.number(),
  discount_minor: z.number(),
  tax_minor: z.number(),
  total_minor: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  subtotal: z.number().optional(), // accessor attribute
  shipping: z.number().optional(), // accessor attribute
  discount: z.number().optional(), // accessor attribute
  tax: z.number().optional(), // accessor attribute
  total: z.number().optional(), // accessor attribute
})

export type OrderAmountApiResponse = z.infer<typeof OrderAmountSchema>
export const validateOrderAmount = (payload: unknown): OrderAmountApiResponse => OrderAmountSchema.parse(payload)

export const OrderDetailSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  produk_item_id: z.number(),
  qty: z.number(),
  harga: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  banana: z.string().nullable(),
  potato: z.number().nullable(),
  flying_dog: z.boolean().nullable(),
  foo: z.unknown().optional(), // accessor attribute
})

export type OrderDetailApiResponse = z.infer<typeof OrderDetailSchema>
export const validateOrderDetail = (payload: unknown): OrderDetailApiResponse => OrderDetailSchema.parse(payload)

export const OrderFinancialSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  financial_status: z.string(),
  refunded_at: z.string().nullable(),
  refund_reason: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderFinancialApiResponse = z.infer<typeof OrderFinancialSchema>
export const validateOrderFinancial = (payload: unknown): OrderFinancialApiResponse => OrderFinancialSchema.parse(payload)

export const OrderFulfillmentSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  fulfillment_status: z.string(),
  processing_at: z.string().nullable(),
  shipped_at: z.string().nullable(),
  completed_at: z.string().nullable(),
  canceled_at: z.string().nullable(),
  cancel_reason: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderFulfillmentApiResponse = z.infer<typeof OrderFulfillmentSchema>
export const validateOrderFulfillment = (payload: unknown): OrderFulfillmentApiResponse => OrderFulfillmentSchema.parse(payload)

export const OrderPromotionSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  promo_code_id: z.number().nullable(),
  promo_code: z.string(),
  discount_minor: z.number(),
  metadata: z.record(z.string(), z.unknown()).nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderPromotionApiResponse = z.infer<typeof OrderPromotionSchema>
export const validateOrderPromotion = (payload: unknown): OrderPromotionApiResponse => OrderPromotionSchema.parse(payload)

export const OrderShippingSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  nama: z.string().nullable(),
  telepon: z.string().nullable(),
  alamat: z.string().nullable(),
  kota: z.string().nullable(),
  kode_pos: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderShippingApiResponse = z.infer<typeof OrderShippingSchema>
export const validateOrderShipping = (payload: unknown): OrderShippingApiResponse => OrderShippingSchema.parse(payload)

export const PaymentSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  metode: z.string().nullable(),
  status: z.union([z.literal('pending'), z.literal('success'), z.literal('failed')]),
  paid_at: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  gatewayStatus: z.string().optional(), // accessor attribute
  amountMinor: z.number().optional(), // accessor attribute
  providerTxnId: z.string().optional(), // accessor attribute
  provider: z.string().optional(), // accessor attribute
  refundAmountMinor: z.unknown().optional(), // accessor attribute
  foo: z.unknown().optional(), // accessor attribute
  bar: z.unknown().optional(), // accessor attribute
})

export type PaymentApiResponse = z.infer<typeof PaymentSchema>
export const validatePayment = (payload: unknown): PaymentApiResponse => PaymentSchema.parse(payload)

export const PaymentAmountSchema = z.object({
  id: z.number(),
  payment_id: z.number(),
  currency_code: z.string(),
  amount_minor: z.number(),
  fee_minor: z.number(),
  net_amount_minor: z.number(),
  refund_amount_minor: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PaymentAmountApiResponse = z.infer<typeof PaymentAmountSchema>
export const validatePaymentAmount = (payload: unknown): PaymentAmountApiResponse => PaymentAmountSchema.parse(payload)

export const PaymentDetailSchema = z.object({
  id: z.number(),
  payment_id: z.number(),
  detail: z.record(z.string(), z.unknown()).nullable(),
  payload_hash: z.string().nullable(),
  payload_received_at: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PaymentDetailApiResponse = z.infer<typeof PaymentDetailSchema>
export const validatePaymentDetail = (payload: unknown): PaymentDetailApiResponse => PaymentDetailSchema.parse(payload)

export const PaymentGatewaySchema = z.object({
  id: z.number(),
  payment_id: z.number(),
  provider: z.string().nullable(),
  provider_txn_id: z.string().nullable(),
  idempotency_key: z.string().nullable(),
  gateway_status: z.string().nullable(),
  gateway_code: z.string().nullable(),
  gateway_message: z.string().nullable(),
  authorized_at: z.string().nullable(),
  captured_at: z.string().nullable(),
  failed_at: z.string().nullable(),
  refunded_at: z.string().nullable(),
  reconciled_at: z.string().nullable(),
  reconciliation_batch_id: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PaymentGatewayApiResponse = z.infer<typeof PaymentGatewaySchema>
export const validatePaymentGateway = (payload: unknown): PaymentGatewayApiResponse => PaymentGatewaySchema.parse(payload)

export const ProductReviewSchema = z.object({
  id: z.number(),
  produk_item_id: z.number(),
  user_id: z.number(),
  rating: z.number(),
  title: z.string().nullable(),
  comment: z.string().nullable(),
  is_verified_purchase: z.boolean(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type ProductReviewApiResponse = z.infer<typeof ProductReviewSchema>
export const validateProductReview = (payload: unknown): ProductReviewApiResponse => ProductReviewSchema.parse(payload)

export const ProdukItemSchema = z.object({
  id: z.number(),
  nama: z.string(),
  deskripsi: z.string().nullable(),
  category_id: z.number().nullable(),
  harga: z.number(),
  stok: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  image: z.string().optional(), // appended
  image_url: z.string().optional(), // appended
  category_name: z.string().optional(), // appended
  rating: z.number().optional(), // appended
  review_count: z.number().optional(), // appended
})

export type ProdukItemApiResponse = z.infer<typeof ProdukItemSchema>
export const validateProdukItem = (payload: unknown): ProdukItemApiResponse => ProdukItemSchema.parse(payload)

export const ProdukItemFrontendSchema = z.object({
  id: z.number(),
  produk_item_id: z.number(),
  gambar: z.string().nullable(),
  rating: z.number(),
  jumlah_review: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type ProdukItemFrontendApiResponse = z.infer<typeof ProdukItemFrontendSchema>
export const validateProdukItemFrontend = (payload: unknown): ProdukItemFrontendApiResponse => ProdukItemFrontendSchema.parse(payload)

export const PromoCodeSchema = z.object({
  id: z.number(),
  code: z.string(),
  discount_type: z.string(),
  discount_value: z.number(),
  max_discount_minor: z.number().nullable(),
  min_order_minor: z.number(),
  usage_limit: z.number().nullable(),
  used_count: z.number(),
  is_active: z.boolean(),
  starts_at: z.string().nullable(),
  ends_at: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PromoCodeApiResponse = z.infer<typeof PromoCodeSchema>
export const validatePromoCode = (payload: unknown): PromoCodeApiResponse => PromoCodeSchema.parse(payload)

export const SocialAccountSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  provider: z.string(),
  provider_user_id: z.string(),
  email: z.string().nullable(),
  avatar_url: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type SocialAccountApiResponse = z.infer<typeof SocialAccountSchema>
export const validateSocialAccount = (payload: unknown): SocialAccountApiResponse => SocialAccountSchema.parse(payload)

export const UserSchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string(),
  password: z.string().optional(),
  role: z.union([z.literal('admin'), z.literal('user')]),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  use_factory: z.unknown().optional(), // accessor attribute
})

export type UserApiResponse = z.infer<typeof UserSchema>
export const validateUser = (payload: unknown): UserApiResponse => UserSchema.parse(payload)

export const WishlistSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  produk_item_id: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type WishlistApiResponse = z.infer<typeof WishlistSchema>
export const validateWishlist = (payload: unknown): WishlistApiResponse => WishlistSchema.parse(payload)

export const RegisterResponseSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  data: z.unknown().nullable(),
})

export type RegisterResponseApiResponse = z.infer<typeof RegisterResponseSchema>
export const validateRegisterResponse = (payload: unknown): RegisterResponseApiResponse => RegisterResponseSchema.parse(payload)

export const OrderDetailResourceSchema = z.object({
  id: z.number(),
  produk_item_id: z.number(),
  produk: z.object({ id: z.number(), nama: z.string(), gambar: z.string().nullable(), image_url: z.string() }),
  qty: z.number(),
  harga: z.number(),
  subtotal: z.number(),
  banana: z.string().nullable(),
  potato: z.number().nullable(),
  flying_dog: z.boolean().nullable(),
  foo: z.unknown(),
})

export type OrderDetailResourceResponse = z.infer<typeof OrderDetailResourceSchema>
export const validateOrderDetailResource = (payload: unknown): OrderDetailResourceResponse => OrderDetailResourceSchema.parse(payload)

export const OrderResourceSchema = z.object({
  id: z.number(),
  status: z.string(),
  total_harga: z.number(),
  invoice_number: z.string().nullable(),
  payment_status: z.string(),
  financial_status: z.string(),
  fulfillment_status: z.string(),
  subtotal_minor: z.number(),
  discount_minor: z.number(),
  shipping_minor: z.number(),
  tax_minor: z.number(),
  total_harga_minor: z.number(),
  items: z.array(OrderDetailResourceSchema),
  promotion: z.object({ code: z.string(), discount_minor: z.number() }),
  shipping: z.object({ nama: z.string().nullable(), telepon: z.string().nullable(), alamat: z.string().nullable(), kota: z.string().nullable(), kode_pos: z.string().nullable() }),
  created_at: z.string(),
})

export type OrderResourceResponse = z.infer<typeof OrderResourceSchema>
export const validateOrderResource = (payload: unknown): OrderResourceResponse => OrderResourceSchema.parse(payload)

export const PaymentResourceSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  invoice_number: z.string().nullable(),
  metode: z.string().nullable(),
  detail: z.array(z.unknown()).nullable(),
  status: z.string(),
  paid_at: z.string().nullable(),
  provider: z.string(),
  provider_txn_id: z.string(),
  gateway_status: z.string(),
  amount_minor: z.number(),
  refund_amount_minor: z.unknown(),
  items: z.array(OrderDetailResourceSchema),
  promotion: z.object({ code: z.string(), discount_minor: z.number() }),
  gateway: z.object({ name: z.null(), order_id: z.null(), token: z.null(), redirect_url: z.null() }),
  total_harga: z.number(),
})

export type PaymentResourceResponse = z.infer<typeof PaymentResourceSchema>
export const validatePaymentResource = (payload: unknown): PaymentResourceResponse => PaymentResourceSchema.parse(payload)

export const ProdukItemResourceSchema = z.object({
  id: z.number(),
  nama: z.string(),
  deskripsi: z.string().nullable(),
  image: z.string().nullable(),
  image_url: z.string(),
  category_id: z.number().nullable(),
  category_name: z.string(),
  harga: z.number(),
  stok: z.number(),
  rating: z.number(),
  review_count: z.number(),
})

export type ProdukItemResourceResponse = z.infer<typeof ProdukItemResourceSchema>
export const validateProdukItemResource = (payload: unknown): ProdukItemResourceResponse => ProdukItemResourceSchema.parse(payload)

export const RegisterPostPayloadSchema = z.object({
    name: z.string(),
    email: z.string(),
    password: z.string(),
  })
export type RegisterPostPayload = z.infer<typeof RegisterPostPayloadSchema>
export const validateRegisterPostPayload = (payload: unknown): RegisterPostPayload => RegisterPostPayloadSchema.parse(payload)

export const RegisterPostResponseSchema = RegisterResponseSchema
export type RegisterPostResponse = z.infer<typeof RegisterPostResponseSchema>
export const validateRegisterPostResponse = (payload: unknown): RegisterPostResponse => RegisterPostResponseSchema.parse(payload)

export const LoginPostPayloadSchema = z.object({
    email: z.string(),
    password: z.string(),
  })
export type LoginPostPayload = z.infer<typeof LoginPostPayloadSchema>
export const validateLoginPostPayload = (payload: unknown): LoginPostPayload => LoginPostPayloadSchema.parse(payload)

export const LoginPostResponseSchema = z.object({ success: z.boolean(), message: z.string(), data: z.object({ token: z.string(), user: z.object({ id: z.number(), name: z.string(), email: z.string(), role: z.string(), created_at: z.string(), updated_at: z.string() }) }) })
export type LoginPostResponse = z.infer<typeof LoginPostResponseSchema>
export const validateLoginPostResponse = (payload: unknown): LoginPostResponse => LoginPostResponseSchema.parse(payload)

export const OauthGetProviderRedirectPayloadSchema = z.object({
    redirect_to: z.string().optional().nullable(),
  })
export type OauthGetProviderRedirectPayload = z.infer<typeof OauthGetProviderRedirectPayloadSchema>
export const validateOauthGetProviderRedirectPayload = (payload: unknown): OauthGetProviderRedirectPayload => OauthGetProviderRedirectPayloadSchema.parse(payload)

export const OauthGetProviderRedirectResponseSchema = z.object({ provider: z.string(), auth_url: z.unknown() })
export type OauthGetProviderRedirectResponse = z.infer<typeof OauthGetProviderRedirectResponseSchema>
export const validateOauthGetProviderRedirectResponse = (payload: unknown): OauthGetProviderRedirectResponse => OauthGetProviderRedirectResponseSchema.parse(payload)

export const OauthGetProviderCallbackResponseSchema = z.object({ message: z.string(), error: z.unknown() })
export type OauthGetProviderCallbackResponse = z.infer<typeof OauthGetProviderCallbackResponseSchema>
export const validateOauthGetProviderCallbackResponse = (payload: unknown): OauthGetProviderCallbackResponse => OauthGetProviderCallbackResponseSchema.parse(payload)

export const OauthPostProviderCallbackResponseSchema = z.object({ message: z.string(), error: z.unknown() })
export type OauthPostProviderCallbackResponse = z.infer<typeof OauthPostProviderCallbackResponseSchema>
export const validateOauthPostProviderCallbackResponse = (payload: unknown): OauthPostProviderCallbackResponse => OauthPostProviderCallbackResponseSchema.parse(payload)

export const SocialPostLoginPayloadSchema = z.object({
    provider: z.enum(['google', 'facebook', 'apple']),
    provider_user_id: z.string(),
    email: z.string(),
    name: z.string().optional().nullable(),
    avatar_url: z.string().optional().nullable(),
  })
export type SocialPostLoginPayload = z.infer<typeof SocialPostLoginPayloadSchema>
export const validateSocialPostLoginPayload = (payload: unknown): SocialPostLoginPayload => SocialPostLoginPayloadSchema.parse(payload)

export const SocialPostLoginResponseSchema = z.object({ token: z.string(), user: z.object({ id: z.number(), name: z.string(), email: z.string(), role: z.string(), created_at: z.string(), updated_at: z.string() }) })
export type SocialPostLoginResponse = z.infer<typeof SocialPostLoginResponseSchema>
export const validateSocialPostLoginResponse = (payload: unknown): SocialPostLoginResponse => SocialPostLoginResponseSchema.parse(payload)

export const ForgotPasswordPostPayloadSchema = z.object({
    email: z.string(),
  })
export type ForgotPasswordPostPayload = z.infer<typeof ForgotPasswordPostPayloadSchema>
export const validateForgotPasswordPostPayload = (payload: unknown): ForgotPasswordPostPayload => ForgotPasswordPostPayloadSchema.parse(payload)

export const ResetPasswordPostPayloadSchema = z.object({
    email: z.string(),
    token: z.string(),
    password: z.string(),
  })
export type ResetPasswordPostPayload = z.infer<typeof ResetPasswordPostPayloadSchema>
export const validateResetPasswordPostPayload = (payload: unknown): ResetPasswordPostPayload => ResetPasswordPostPayloadSchema.parse(payload)

export const ResetPasswordPostResponseSchema = z.object({ message: z.string() })
export type ResetPasswordPostResponse = z.infer<typeof ResetPasswordPostResponseSchema>
export const validateResetPasswordPostResponse = (payload: unknown): ResetPasswordPostResponse => ResetPasswordPostResponseSchema.parse(payload)

export const CategoriesGetResponseSchema = z.object({ data: z.array(CategorySchema) })
export type CategoriesGetResponse = z.infer<typeof CategoriesGetResponseSchema>
export const validateCategoriesGetResponse = (payload: unknown): CategoriesGetResponse => CategoriesGetResponseSchema.parse(payload)

export const ProdukGetResponseSchema = ProdukItemResourceSchema
export type ProdukGetResponse = z.infer<typeof ProdukGetResponseSchema>
export const validateProdukGetResponse = (payload: unknown): ProdukGetResponse => ProdukGetResponseSchema.parse(payload)

export const ProdukGetIdResponseSchema = ProdukItemResourceSchema
export type ProdukGetIdResponse = z.infer<typeof ProdukGetIdResponseSchema>
export const validateProdukGetIdResponse = (payload: unknown): ProdukGetIdResponse => ProdukGetIdResponseSchema.parse(payload)

export const ProdukGetIdReviewsResponseSchema = z.object({ summary: z.object({ avg_rating: z.number(), total_review: z.number() }), reviews: z.object({ data: z.array(ProductReviewSchema), current_page: z.number().optional(), total: z.number().optional() }) })
export type ProdukGetIdReviewsResponse = z.infer<typeof ProdukGetIdReviewsResponseSchema>
export const validateProdukGetIdReviewsResponse = (payload: unknown): ProdukGetIdReviewsResponse => ProdukGetIdReviewsResponseSchema.parse(payload)

export const ProdukPostIdReviewsPayloadSchema = z.object({
    rating: z.number(),
    title: z.string().optional().nullable(),
    comment: z.string().optional().nullable(),
  })
export type ProdukPostIdReviewsPayload = z.infer<typeof ProdukPostIdReviewsPayloadSchema>
export const validateProdukPostIdReviewsPayload = (payload: unknown): ProdukPostIdReviewsPayload => ProdukPostIdReviewsPayloadSchema.parse(payload)

export const ProdukPostIdReviewsResponseSchema = z.object({ message: z.string(), data: z.object({ id: z.number(), rating: z.number(), title: z.string().nullable(), comment: z.string().nullable(), is_verified_purchase: z.number(), created_at: z.string().nullable() }) })
export type ProdukPostIdReviewsResponse = z.infer<typeof ProdukPostIdReviewsResponseSchema>
export const validateProdukPostIdReviewsResponse = (payload: unknown): ProdukPostIdReviewsResponse => ProdukPostIdReviewsResponseSchema.parse(payload)

export const PaymentPostWebhookResponseSchema = z.object({ summary: z.object({ avg_rating: z.number(), total_review: z.number() }), reviews: z.object({ data: z.array(ProductReviewSchema), current_page: z.number().optional(), total: z.number().optional() }) })
export type PaymentPostWebhookResponse = z.infer<typeof PaymentPostWebhookResponseSchema>
export const validatePaymentPostWebhookResponse = (payload: unknown): PaymentPostWebhookResponse => PaymentPostWebhookResponseSchema.parse(payload)

export const PaymentPostOrderIdPayloadSchema = z.object({
    metode: z.string(),
    detail: z.array(z.unknown()).optional().nullable(),
    provider: z.enum(['mock', 'midtrans']).optional().nullable(),
    provider_txn_id: z.string().optional().nullable(),
    idempotency_key: z.string().optional().nullable(),
    gateway_code: z.string().optional().nullable(),
    gateway_message: z.string().optional().nullable(),
  })
export type PaymentPostOrderIdPayload = z.infer<typeof PaymentPostOrderIdPayloadSchema>
export const validatePaymentPostOrderIdPayload = (payload: unknown): PaymentPostOrderIdPayload => PaymentPostOrderIdPayloadSchema.parse(payload)

export const PaymentPostOrderIdResponseSchema = PaymentResourceSchema
export type PaymentPostOrderIdResponse = z.infer<typeof PaymentPostOrderIdResponseSchema>
export const validatePaymentPostOrderIdResponse = (payload: unknown): PaymentPostOrderIdResponse => PaymentPostOrderIdResponseSchema.parse(payload)

export const ProfileGetResponseSchema = z.object({ id: z.number(), name: z.string(), email: z.string() })
export type ProfileGetResponse = z.infer<typeof ProfileGetResponseSchema>
export const validateProfileGetResponse = (payload: unknown): ProfileGetResponse => ProfileGetResponseSchema.parse(payload)

export const ProfilePutPayloadSchema = z.object({
    name: z.string(),
    email: z.string(),
  })
export type ProfilePutPayload = z.infer<typeof ProfilePutPayloadSchema>
export const validateProfilePutPayload = (payload: unknown): ProfilePutPayload => ProfilePutPayloadSchema.parse(payload)

export const ProfilePutResponseSchema = z.object({ message: z.string(), data: z.object({ id: z.number(), name: z.string(), email: z.string() }) })
export type ProfilePutResponse = z.infer<typeof ProfilePutResponseSchema>
export const validateProfilePutResponse = (payload: unknown): ProfilePutResponse => ProfilePutResponseSchema.parse(payload)

export const ProfilePatchPayloadSchema = z.object({
    name: z.string(),
    email: z.string(),
  })
export type ProfilePatchPayload = z.infer<typeof ProfilePatchPayloadSchema>
export const validateProfilePatchPayload = (payload: unknown): ProfilePatchPayload => ProfilePatchPayloadSchema.parse(payload)

export const ProfilePatchResponseSchema = z.object({ message: z.string(), data: z.object({ id: z.number(), name: z.string(), email: z.string() }) })
export type ProfilePatchResponse = z.infer<typeof ProfilePatchResponseSchema>
export const validateProfilePatchResponse = (payload: unknown): ProfilePatchResponse => ProfilePatchResponseSchema.parse(payload)

export const OrdersGetResponseSchema = OrderResourceSchema
export type OrdersGetResponse = z.infer<typeof OrdersGetResponseSchema>
export const validateOrdersGetResponse = (payload: unknown): OrdersGetResponse => OrdersGetResponseSchema.parse(payload)

export const OrdersGetIdResponseSchema = OrderResourceSchema
export type OrdersGetIdResponse = z.infer<typeof OrdersGetIdResponseSchema>
export const validateOrdersGetIdResponse = (payload: unknown): OrdersGetIdResponse => OrdersGetIdResponseSchema.parse(payload)

export const CartPostItemsPayloadSchema = z.object({
    produk_item_id: z.string(),
    qty: z.number(),
  })
export type CartPostItemsPayload = z.infer<typeof CartPostItemsPayloadSchema>
export const validateCartPostItemsPayload = (payload: unknown): CartPostItemsPayload => CartPostItemsPayloadSchema.parse(payload)

export const CartPostItemsResponseSchema = OrderResourceSchema
export type CartPostItemsResponse = z.infer<typeof CartPostItemsResponseSchema>
export const validateCartPostItemsResponse = (payload: unknown): CartPostItemsResponse => CartPostItemsResponseSchema.parse(payload)

export const CartPatchItemsProdukItemIdPayloadSchema = z.object({
    qty: z.number(),
  })
export type CartPatchItemsProdukItemIdPayload = z.infer<typeof CartPatchItemsProdukItemIdPayloadSchema>
export const validateCartPatchItemsProdukItemIdPayload = (payload: unknown): CartPatchItemsProdukItemIdPayload => CartPatchItemsProdukItemIdPayloadSchema.parse(payload)

export const CartPatchItemsProdukItemIdResponseSchema = OrderResourceSchema
export type CartPatchItemsProdukItemIdResponse = z.infer<typeof CartPatchItemsProdukItemIdResponseSchema>
export const validateCartPatchItemsProdukItemIdResponse = (payload: unknown): CartPatchItemsProdukItemIdResponse => CartPatchItemsProdukItemIdResponseSchema.parse(payload)

export const CartDeleteItemsProdukItemIdResponseSchema = OrderResourceSchema
export type CartDeleteItemsProdukItemIdResponse = z.infer<typeof CartDeleteItemsProdukItemIdResponseSchema>
export const validateCartDeleteItemsProdukItemIdResponse = (payload: unknown): CartDeleteItemsProdukItemIdResponse => CartDeleteItemsProdukItemIdResponseSchema.parse(payload)

export const CartDeleteResponseSchema = z.object({ message: z.string() })
export type CartDeleteResponse = z.infer<typeof CartDeleteResponseSchema>
export const validateCartDeleteResponse = (payload: unknown): CartDeleteResponse => CartDeleteResponseSchema.parse(payload)

export const CartPostPromoPayloadSchema = z.object({
    code: z.string(),
  })
export type CartPostPromoPayload = z.infer<typeof CartPostPromoPayloadSchema>
export const validateCartPostPromoPayload = (payload: unknown): CartPostPromoPayload => CartPostPromoPayloadSchema.parse(payload)

export const CartPostPromoResponseSchema = OrderResourceSchema
export type CartPostPromoResponse = z.infer<typeof CartPostPromoResponseSchema>
export const validateCartPostPromoResponse = (payload: unknown): CartPostPromoResponse => CartPostPromoResponseSchema.parse(payload)

export const CartDeletePromoResponseSchema = OrderResourceSchema
export type CartDeletePromoResponse = z.infer<typeof CartDeletePromoResponseSchema>
export const validateCartDeletePromoResponse = (payload: unknown): CartDeletePromoResponse => CartDeletePromoResponseSchema.parse(payload)

export const CheckoutPostPayloadSchema = z.object({
    items: z.array(z.object({
    produk_item_id: z.string(),
    qty: z.number(),
  })).optional(),
    shipping_nama: z.string().optional().nullable(),
    shipping_telepon: z.string().optional().nullable(),
    shipping_alamat: z.string().optional().nullable(),
    shipping_kota: z.string().optional().nullable(),
    shipping_kode_pos: z.string().optional().nullable(),
  })
export type CheckoutPostPayload = z.infer<typeof CheckoutPostPayloadSchema>
export const validateCheckoutPostPayload = (payload: unknown): CheckoutPostPayload => CheckoutPostPayloadSchema.parse(payload)

export const CheckoutPostResponseSchema = OrderResourceSchema
export type CheckoutPostResponse = z.infer<typeof CheckoutPostResponseSchema>
export const validateCheckoutPostResponse = (payload: unknown): CheckoutPostResponse => CheckoutPostResponseSchema.parse(payload)

export const BuyNowPostPayloadSchema = z.object({
    produk_item_id: z.string(),
    qty: z.number(),
    shipping_nama: z.string().optional().nullable(),
    shipping_telepon: z.string().optional().nullable(),
    shipping_alamat: z.string().optional().nullable(),
    shipping_kota: z.string().optional().nullable(),
    shipping_kode_pos: z.string().optional().nullable(),
  })
export type BuyNowPostPayload = z.infer<typeof BuyNowPostPayloadSchema>
export const validateBuyNowPostPayload = (payload: unknown): BuyNowPostPayload => BuyNowPostPayloadSchema.parse(payload)

export const BuyNowPostResponseSchema = OrderResourceSchema
export type BuyNowPostResponse = z.infer<typeof BuyNowPostResponseSchema>
export const validateBuyNowPostResponse = (payload: unknown): BuyNowPostResponse => BuyNowPostResponseSchema.parse(payload)

export const KeranjangGetResponseSchema = OrderResourceSchema
export type KeranjangGetResponse = z.infer<typeof KeranjangGetResponseSchema>
export const validateKeranjangGetResponse = (payload: unknown): KeranjangGetResponse => KeranjangGetResponseSchema.parse(payload)

export const WishlistGetResponseSchema = ProdukItemResourceSchema
export type WishlistGetResponse = z.infer<typeof WishlistGetResponseSchema>
export const validateWishlistGetResponse = (payload: unknown): WishlistGetResponse => WishlistGetResponseSchema.parse(payload)

export const WishlistPostPayloadSchema = z.object({
    produk_item_id: z.string(),
  })
export type WishlistPostPayload = z.infer<typeof WishlistPostPayloadSchema>
export const validateWishlistPostPayload = (payload: unknown): WishlistPostPayload => WishlistPostPayloadSchema.parse(payload)

export const WishlistPostResponseSchema = z.object({ message: z.string() })
export type WishlistPostResponse = z.infer<typeof WishlistPostResponseSchema>
export const validateWishlistPostResponse = (payload: unknown): WishlistPostResponse => WishlistPostResponseSchema.parse(payload)

export const WishlistDeleteProdukItemIdResponseSchema = z.object({ message: z.string() })
export type WishlistDeleteProdukItemIdResponse = z.infer<typeof WishlistDeleteProdukItemIdResponseSchema>
export const validateWishlistDeleteProdukItemIdResponse = (payload: unknown): WishlistDeleteProdukItemIdResponse => WishlistDeleteProdukItemIdResponseSchema.parse(payload)

export const LogoutPostResponseSchema = z.object({ message: z.string() })
export type LogoutPostResponse = z.infer<typeof LogoutPostResponseSchema>
export const validateLogoutPostResponse = (payload: unknown): LogoutPostResponse => LogoutPostResponseSchema.parse(payload)

export const AdminPostProdukPayloadSchema = z.object({
    nama: z.string(),
    deskripsi: z.string().optional().nullable(),
    gambar: z.string().optional().nullable(),
    category_id: z.string(),
    harga: z.number(),
    stok: z.number(),
    rating: z.number().optional().nullable(),
    jumlah_review: z.number().optional().nullable(),
  })
export type AdminPostProdukPayload = z.infer<typeof AdminPostProdukPayloadSchema>
export const validateAdminPostProdukPayload = (payload: unknown): AdminPostProdukPayload => AdminPostProdukPayloadSchema.parse(payload)

export const AdminPostProdukResponseSchema = ProdukItemResourceSchema
export type AdminPostProdukResponse = z.infer<typeof AdminPostProdukResponseSchema>
export const validateAdminPostProdukResponse = (payload: unknown): AdminPostProdukResponse => AdminPostProdukResponseSchema.parse(payload)
