// Auto-generated by routesync. Do not edit manually.
import { z } from 'zod'

export const ApiSchema = {
  RegisterCreate: z.object({
    name: z.string(),
    email: z.string(),
    password: z.string(),
  }),
  LoginCreate: z.object({
    email: z.string(),
    password: z.string(),
  }),
  OauthRedirectGet: z.object({
    redirectTo: z.string().optional().nullable(),
  }),
  SocialLoginCreate: z.object({
    provider: z.enum(['google', 'facebook', 'apple']),
    providerUserId: z.string(),
    email: z.string(),
    name: z.string().optional().nullable(),
    avatarUrl: z.string().optional().nullable(),
  }),
  ForgotPasswordCreate: z.object({
    email: z.string(),
  }),
  ResetPasswordCreate: z.object({
    email: z.string(),
    token: z.string(),
    password: z.string(),
  }),
  ProdukReviewsPost: z.object({
    rating: z.number(),
    title: z.string().optional().nullable(),
    comment: z.string().optional().nullable(),
  }),
  ProfilePut: z.object({
    name: z.string(),
    email: z.string(),
  }),
  ProfilePatch: z.object({
    name: z.string(),
    email: z.string(),
  }),
  CartItemsCreate: z.object({
    produkItemId: z.string(),
    qty: z.number(),
  }),
  CartItemsUpdate: z.object({
    qty: z.number(),
  }),
  CartPromoCreate: z.object({
    code: z.string(),
  }),
  CheckoutCreate: z.object({
    items: z.array(z.object({
    produkItemId: z.string(),
    qty: z.number(),
  })).optional(),
    shippingNama: z.string().optional().nullable(),
    shippingTelepon: z.string().optional().nullable(),
    shippingAlamat: z.string().optional().nullable(),
    shippingKota: z.string().optional().nullable(),
    shippingKodePos: z.string().optional().nullable(),
  }),
  BuyNowCreate: z.object({
    produkItemId: z.string(),
    qty: z.number(),
    shippingNama: z.string().optional().nullable(),
    shippingTelepon: z.string().optional().nullable(),
    shippingAlamat: z.string().optional().nullable(),
    shippingKota: z.string().optional().nullable(),
    shippingKodePos: z.string().optional().nullable(),
  }),
  WishlistCreate: z.object({
    produkItemId: z.string(),
  }),
  PaymentPost: z.object({
    metode: z.string(),
    detail: z.array(z.unknown()).optional().nullable(),
    provider: z.enum(['mock', 'midtrans']).optional().nullable(),
    providerTxnId: z.string().optional().nullable(),
    idempotencyKey: z.string().optional().nullable(),
    gatewayCode: z.string().optional().nullable(),
    gatewayMessage: z.string().optional().nullable(),
  }),
  AdminProdukCreate: z.object({
    nama: z.string(),
    deskripsi: z.string().optional().nullable(),
    gambar: z.string().optional().nullable(),
    categoryId: z.string(),
    harga: z.number(),
    stok: z.number(),
    rating: z.number().optional().nullable(),
    jumlahReview: z.number().optional().nullable(),
  }),
}

export type ApiFormValues = {
  RegisterCreate: z.infer<typeof ApiSchema.RegisterCreate>
  LoginCreate: z.infer<typeof ApiSchema.LoginCreate>
  OauthRedirectGet: z.infer<typeof ApiSchema.OauthRedirectGet>
  SocialLoginCreate: z.infer<typeof ApiSchema.SocialLoginCreate>
  ForgotPasswordCreate: z.infer<typeof ApiSchema.ForgotPasswordCreate>
  ResetPasswordCreate: z.infer<typeof ApiSchema.ResetPasswordCreate>
  ProdukReviewsPost: z.infer<typeof ApiSchema.ProdukReviewsPost>
  ProfilePut: z.infer<typeof ApiSchema.ProfilePut>
  ProfilePatch: z.infer<typeof ApiSchema.ProfilePatch>
  CartItemsCreate: z.infer<typeof ApiSchema.CartItemsCreate>
  CartItemsUpdate: z.infer<typeof ApiSchema.CartItemsUpdate>
  CartPromoCreate: z.infer<typeof ApiSchema.CartPromoCreate>
  CheckoutCreate: z.infer<typeof ApiSchema.CheckoutCreate>
  BuyNowCreate: z.infer<typeof ApiSchema.BuyNowCreate>
  WishlistCreate: z.infer<typeof ApiSchema.WishlistCreate>
  PaymentPost: z.infer<typeof ApiSchema.PaymentPost>
  AdminProdukCreate: z.infer<typeof ApiSchema.AdminProdukCreate>
}

export const ApiDefaultValues = {
  registerCreate: {} as ApiFormValues['RegisterCreate'],
  loginCreate: {} as ApiFormValues['LoginCreate'],
  oauthRedirectGet: {} as ApiFormValues['OauthRedirectGet'],
  socialLoginCreate: {} as ApiFormValues['SocialLoginCreate'],
  forgotPasswordCreate: {} as ApiFormValues['ForgotPasswordCreate'],
  resetPasswordCreate: {} as ApiFormValues['ResetPasswordCreate'],
  produkReviewsPost: {} as ApiFormValues['ProdukReviewsPost'],
  profilePut: {} as ApiFormValues['ProfilePut'],
  profilePatch: {} as ApiFormValues['ProfilePatch'],
  cartItemsCreate: {} as ApiFormValues['CartItemsCreate'],
  cartItemsUpdate: {} as ApiFormValues['CartItemsUpdate'],
  cartPromoCreate: {} as ApiFormValues['CartPromoCreate'],
  checkoutCreate: {} as ApiFormValues['CheckoutCreate'],
  buyNowCreate: {} as ApiFormValues['BuyNowCreate'],
  wishlistCreate: {} as ApiFormValues['WishlistCreate'],
  paymentPost: {} as ApiFormValues['PaymentPost'],
  adminProdukCreate: {} as ApiFormValues['AdminProdukCreate'],
}