// Auto-generated by routesync. Do not edit manually.
import { z } from 'zod'

export const CategorySchema = z.object({
  id: z.number(),
  nama: z.string(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type CategoryApiResponse = z.infer<typeof CategorySchema>
export const validateCategory = (payload: unknown): CategoryApiResponse => CategorySchema.parse(payload)

export const OrderSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  total_harga: z.number(),
  status: z.union([z.literal('pending'), z.literal('paid'), z.literal('canceled')]),
  order_number: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderApiResponse = z.infer<typeof OrderSchema>
export const validateOrder = (payload: unknown): OrderApiResponse => OrderSchema.parse(payload)

export const OrderAmountSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  subtotal_minor: z.number(),
  shipping_minor: z.number(),
  discount_minor: z.number(),
  tax_minor: z.number(),
  total_minor: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  subtotal: z.number().optional(), // accessor attribute
  shipping: z.number().optional(), // accessor attribute
  discount: z.number().optional(), // accessor attribute
  tax: z.number().optional(), // accessor attribute
  total: z.number().optional(), // accessor attribute
})

export type OrderAmountApiResponse = z.infer<typeof OrderAmountSchema>
export const validateOrderAmount = (payload: unknown): OrderAmountApiResponse => OrderAmountSchema.parse(payload)

export const OrderDetailSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  produk_item_id: z.number(),
  qty: z.number(),
  harga: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  banana: z.string().nullable(),
  potato: z.number().nullable(),
  flying_dog: z.boolean().nullable(),
  foo: z.unknown().optional(), // accessor attribute
})

export type OrderDetailApiResponse = z.infer<typeof OrderDetailSchema>
export const validateOrderDetail = (payload: unknown): OrderDetailApiResponse => OrderDetailSchema.parse(payload)

export const OrderFinancialSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  financial_status: z.string(),
  refunded_at: z.string().nullable(),
  refund_reason: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderFinancialApiResponse = z.infer<typeof OrderFinancialSchema>
export const validateOrderFinancial = (payload: unknown): OrderFinancialApiResponse => OrderFinancialSchema.parse(payload)

export const OrderFulfillmentSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  fulfillment_status: z.string(),
  processing_at: z.string().nullable(),
  shipped_at: z.string().nullable(),
  completed_at: z.string().nullable(),
  canceled_at: z.string().nullable(),
  cancel_reason: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderFulfillmentApiResponse = z.infer<typeof OrderFulfillmentSchema>
export const validateOrderFulfillment = (payload: unknown): OrderFulfillmentApiResponse => OrderFulfillmentSchema.parse(payload)

export const OrderPromotionSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  promo_code_id: z.number().nullable(),
  promo_code: z.string(),
  discount_minor: z.number(),
  metadata: z.record(z.string(), z.unknown()).nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderPromotionApiResponse = z.infer<typeof OrderPromotionSchema>
export const validateOrderPromotion = (payload: unknown): OrderPromotionApiResponse => OrderPromotionSchema.parse(payload)

export const OrderShippingSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  nama: z.string().nullable(),
  telepon: z.string().nullable(),
  alamat: z.string().nullable(),
  kota: z.string().nullable(),
  kode_pos: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type OrderShippingApiResponse = z.infer<typeof OrderShippingSchema>
export const validateOrderShipping = (payload: unknown): OrderShippingApiResponse => OrderShippingSchema.parse(payload)

export const PaymentSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  metode: z.string().nullable(),
  status: z.union([z.literal('pending'), z.literal('success'), z.literal('failed')]),
  paid_at: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  gatewayStatus: z.string().optional(), // accessor attribute
  amountMinor: z.number().optional(), // accessor attribute
  providerTxnId: z.string().optional(), // accessor attribute
  provider: z.string().optional(), // accessor attribute
  refundAmountMinor: z.unknown().optional(), // accessor attribute
  foo: z.unknown().optional(), // accessor attribute
  bar: z.unknown().optional(), // accessor attribute
})

export type PaymentApiResponse = z.infer<typeof PaymentSchema>
export const validatePayment = (payload: unknown): PaymentApiResponse => PaymentSchema.parse(payload)

export const PaymentAmountSchema = z.object({
  id: z.number(),
  payment_id: z.number(),
  currency_code: z.string(),
  amount_minor: z.number(),
  fee_minor: z.number(),
  net_amount_minor: z.number(),
  refund_amount_minor: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PaymentAmountApiResponse = z.infer<typeof PaymentAmountSchema>
export const validatePaymentAmount = (payload: unknown): PaymentAmountApiResponse => PaymentAmountSchema.parse(payload)

export const PaymentDetailSchema = z.object({
  id: z.number(),
  payment_id: z.number(),
  detail: z.record(z.string(), z.unknown()).nullable(),
  payload_hash: z.string().nullable(),
  payload_received_at: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PaymentDetailApiResponse = z.infer<typeof PaymentDetailSchema>
export const validatePaymentDetail = (payload: unknown): PaymentDetailApiResponse => PaymentDetailSchema.parse(payload)

export const PaymentGatewaySchema = z.object({
  id: z.number(),
  payment_id: z.number(),
  provider: z.string().nullable(),
  provider_txn_id: z.string().nullable(),
  idempotency_key: z.string().nullable(),
  gateway_status: z.string().nullable(),
  gateway_code: z.string().nullable(),
  gateway_message: z.string().nullable(),
  authorized_at: z.string().nullable(),
  captured_at: z.string().nullable(),
  failed_at: z.string().nullable(),
  refunded_at: z.string().nullable(),
  reconciled_at: z.string().nullable(),
  reconciliation_batch_id: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PaymentGatewayApiResponse = z.infer<typeof PaymentGatewaySchema>
export const validatePaymentGateway = (payload: unknown): PaymentGatewayApiResponse => PaymentGatewaySchema.parse(payload)

export const ProductReviewSchema = z.object({
  id: z.number(),
  produk_item_id: z.number(),
  user_id: z.number(),
  rating: z.number(),
  title: z.string().nullable(),
  comment: z.string().nullable(),
  is_verified_purchase: z.boolean(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type ProductReviewApiResponse = z.infer<typeof ProductReviewSchema>
export const validateProductReview = (payload: unknown): ProductReviewApiResponse => ProductReviewSchema.parse(payload)

export const ProdukItemSchema = z.object({
  id: z.number(),
  nama: z.string(),
  deskripsi: z.string().nullable(),
  category_id: z.number().nullable(),
  harga: z.number(),
  stok: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  image: z.string().optional(), // appended
  image_url: z.string().optional(), // appended
  category_name: z.string().optional(), // appended
  rating: z.number().optional(), // appended
  review_count: z.number().optional(), // appended
})

export type ProdukItemApiResponse = z.infer<typeof ProdukItemSchema>
export const validateProdukItem = (payload: unknown): ProdukItemApiResponse => ProdukItemSchema.parse(payload)

export const ProdukItemFrontendSchema = z.object({
  id: z.number(),
  produk_item_id: z.number(),
  gambar: z.string().nullable(),
  rating: z.number(),
  jumlah_review: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type ProdukItemFrontendApiResponse = z.infer<typeof ProdukItemFrontendSchema>
export const validateProdukItemFrontend = (payload: unknown): ProdukItemFrontendApiResponse => ProdukItemFrontendSchema.parse(payload)

export const PromoCodeSchema = z.object({
  id: z.number(),
  code: z.string(),
  discount_type: z.string(),
  discount_value: z.number(),
  max_discount_minor: z.number().nullable(),
  min_order_minor: z.number(),
  usage_limit: z.number().nullable(),
  used_count: z.number(),
  is_active: z.boolean(),
  starts_at: z.string().nullable(),
  ends_at: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type PromoCodeApiResponse = z.infer<typeof PromoCodeSchema>
export const validatePromoCode = (payload: unknown): PromoCodeApiResponse => PromoCodeSchema.parse(payload)

export const SocialAccountSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  provider: z.string(),
  provider_user_id: z.string(),
  email: z.string().nullable(),
  avatar_url: z.string().nullable(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type SocialAccountApiResponse = z.infer<typeof SocialAccountSchema>
export const validateSocialAccount = (payload: unknown): SocialAccountApiResponse => SocialAccountSchema.parse(payload)

export const UserSchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string(),
  password: z.string().optional(),
  role: z.union([z.literal('admin'), z.literal('user')]),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
  use_factory: z.unknown().optional(), // accessor attribute
})

export type UserApiResponse = z.infer<typeof UserSchema>
export const validateUser = (payload: unknown): UserApiResponse => UserSchema.parse(payload)

export const WishlistSchema = z.object({
  id: z.number(),
  user_id: z.number(),
  produk_item_id: z.number(),
  created_at: z.string().nullable(),
  updated_at: z.string().nullable(),
})

export type WishlistApiResponse = z.infer<typeof WishlistSchema>
export const validateWishlist = (payload: unknown): WishlistApiResponse => WishlistSchema.parse(payload)

export const RegisterResponseSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  data: z.unknown().nullable(),
})

export type RegisterResponseApiResponse = z.infer<typeof RegisterResponseSchema>
export const validateRegisterResponse = (payload: unknown): RegisterResponseApiResponse => RegisterResponseSchema.parse(payload)

export const OrderDetailResourceSchema = z.object({
  id: z.number(),
  produk_item_id: z.number(),
  produk: z.object({ id: z.number(), nama: z.string(), gambar: z.string().nullable(), image_url: z.string() }),
  qty: z.number(),
  harga: z.number(),
  subtotal: z.number(),
  banana: z.string().nullable(),
  potato: z.number().nullable(),
  flying_dog: z.boolean().nullable(),
  foo: z.unknown(),
})

export type OrderDetailResourceResponse = z.infer<typeof OrderDetailResourceSchema>
export const validateOrderDetailResource = (payload: unknown): OrderDetailResourceResponse => OrderDetailResourceSchema.parse(payload)

export const OrderResourceSchema = z.object({
  id: z.number(),
  status: z.string(),
  total_harga: z.number(),
  invoice_number: z.string().nullable(),
  payment_status: z.string(),
  financial_status: z.string(),
  fulfillment_status: z.string(),
  subtotal_minor: z.number(),
  discount_minor: z.number(),
  shipping_minor: z.number(),
  tax_minor: z.number(),
  total_harga_minor: z.number(),
  items: z.array(OrderDetailResourceSchema),
  promotion: z.object({ code: z.string(), discount_minor: z.number() }),
  shipping: z.object({ nama: z.string().nullable(), telepon: z.string().nullable(), alamat: z.string().nullable(), kota: z.string().nullable(), kode_pos: z.string().nullable() }),
  created_at: z.string(),
})

export type OrderResourceResponse = z.infer<typeof OrderResourceSchema>
export const validateOrderResource = (payload: unknown): OrderResourceResponse => OrderResourceSchema.parse(payload)

export const PaymentResourceSchema = z.object({
  id: z.number(),
  order_id: z.number(),
  invoice_number: z.string().nullable(),
  metode: z.string().nullable(),
  detail: z.array(z.unknown()).nullable(),
  status: z.string(),
  paid_at: z.string().nullable(),
  provider: z.string(),
  provider_txn_id: z.string(),
  gateway_status: z.string(),
  amount_minor: z.number(),
  refund_amount_minor: z.unknown(),
  items: z.array(OrderDetailResourceSchema),
  promotion: z.object({ code: z.string(), discount_minor: z.number() }),
  gateway: z.object({ name: z.null(), order_id: z.null(), token: z.null(), redirect_url: z.null() }),
  total_harga: z.number(),
})

export type PaymentResourceResponse = z.infer<typeof PaymentResourceSchema>
export const validatePaymentResource = (payload: unknown): PaymentResourceResponse => PaymentResourceSchema.parse(payload)

export const ProdukItemResourceSchema = z.object({
  id: z.number(),
  nama: z.string(),
  deskripsi: z.string().nullable(),
  image: z.string().nullable(),
  image_url: z.string(),
  category_id: z.number().nullable(),
  category_name: z.string(),
  harga: z.number(),
  stok: z.number(),
  rating: z.number(),
  review_count: z.number(),
})

export type ProdukItemResourceResponse = z.infer<typeof ProdukItemResourceSchema>
export const validateProdukItemResource = (payload: unknown): ProdukItemResourceResponse => ProdukItemResourceSchema.parse(payload)

export const RegisterCreatePayloadSchema = z.object({
    name: z.string(),
    email: z.string(),
    password: z.string(),
  })
export type RegisterCreatePayload = z.infer<typeof RegisterCreatePayloadSchema>
export const validateRegisterCreatePayload = (payload: unknown): RegisterCreatePayload => RegisterCreatePayloadSchema.parse(payload)

export const RegisterCreateResponseSchema = RegisterResponseSchema
export type RegisterCreateResponse = z.infer<typeof RegisterCreateResponseSchema>
export const validateRegisterCreateResponse = (payload: unknown): RegisterCreateResponse => RegisterCreateResponseSchema.parse(payload)

export const LoginCreatePayloadSchema = z.object({
    email: z.string(),
    password: z.string(),
  })
export type LoginCreatePayload = z.infer<typeof LoginCreatePayloadSchema>
export const validateLoginCreatePayload = (payload: unknown): LoginCreatePayload => LoginCreatePayloadSchema.parse(payload)

export const LoginCreateResponseSchema = z.object({ success: z.boolean(), message: z.string(), data: z.object({ token: z.string(), user: z.object({ id: z.number(), name: z.string(), email: z.string(), role: z.string(), created_at: z.string(), updated_at: z.string() }) }) })
export type LoginCreateResponse = z.infer<typeof LoginCreateResponseSchema>
export const validateLoginCreateResponse = (payload: unknown): LoginCreateResponse => LoginCreateResponseSchema.parse(payload)

export const OauthRedirectGetPayloadSchema = z.object({
    redirect_to: z.string().optional().nullable(),
  })
export type OauthRedirectGetPayload = z.infer<typeof OauthRedirectGetPayloadSchema>
export const validateOauthRedirectGetPayload = (payload: unknown): OauthRedirectGetPayload => OauthRedirectGetPayloadSchema.parse(payload)

export const OauthRedirectGetResponseSchema = z.object({ provider: z.string(), auth_url: z.unknown() })
export type OauthRedirectGetResponse = z.infer<typeof OauthRedirectGetResponseSchema>
export const validateOauthRedirectGetResponse = (payload: unknown): OauthRedirectGetResponse => OauthRedirectGetResponseSchema.parse(payload)

export const OauthCallbackGetResponseSchema = z.object({ message: z.string(), error: z.unknown() })
export type OauthCallbackGetResponse = z.infer<typeof OauthCallbackGetResponseSchema>
export const validateOauthCallbackGetResponse = (payload: unknown): OauthCallbackGetResponse => OauthCallbackGetResponseSchema.parse(payload)

export const OauthCallbackPostResponseSchema = z.object({ message: z.string(), error: z.unknown() })
export type OauthCallbackPostResponse = z.infer<typeof OauthCallbackPostResponseSchema>
export const validateOauthCallbackPostResponse = (payload: unknown): OauthCallbackPostResponse => OauthCallbackPostResponseSchema.parse(payload)

export const SocialLoginCreatePayloadSchema = z.object({
    provider: z.enum(['google', 'facebook', 'apple']),
    provider_user_id: z.string(),
    email: z.string(),
    name: z.string().optional().nullable(),
    avatar_url: z.string().optional().nullable(),
  })
export type SocialLoginCreatePayload = z.infer<typeof SocialLoginCreatePayloadSchema>
export const validateSocialLoginCreatePayload = (payload: unknown): SocialLoginCreatePayload => SocialLoginCreatePayloadSchema.parse(payload)

export const SocialLoginCreateResponseSchema = z.object({ token: z.string(), user: z.object({ id: z.number(), name: z.string(), email: z.string(), role: z.string(), created_at: z.string(), updated_at: z.string() }) })
export type SocialLoginCreateResponse = z.infer<typeof SocialLoginCreateResponseSchema>
export const validateSocialLoginCreateResponse = (payload: unknown): SocialLoginCreateResponse => SocialLoginCreateResponseSchema.parse(payload)

export const ForgotPasswordCreatePayloadSchema = z.object({
    email: z.string(),
  })
export type ForgotPasswordCreatePayload = z.infer<typeof ForgotPasswordCreatePayloadSchema>
export const validateForgotPasswordCreatePayload = (payload: unknown): ForgotPasswordCreatePayload => ForgotPasswordCreatePayloadSchema.parse(payload)

export const ResetPasswordCreatePayloadSchema = z.object({
    email: z.string(),
    token: z.string(),
    password: z.string(),
  })
export type ResetPasswordCreatePayload = z.infer<typeof ResetPasswordCreatePayloadSchema>
export const validateResetPasswordCreatePayload = (payload: unknown): ResetPasswordCreatePayload => ResetPasswordCreatePayloadSchema.parse(payload)

export const ResetPasswordCreateResponseSchema = z.object({ message: z.string() })
export type ResetPasswordCreateResponse = z.infer<typeof ResetPasswordCreateResponseSchema>
export const validateResetPasswordCreateResponse = (payload: unknown): ResetPasswordCreateResponse => ResetPasswordCreateResponseSchema.parse(payload)

export const CategoriesListResponseSchema = z.object({ data: z.array(CategorySchema) })
export type CategoriesListResponse = z.infer<typeof CategoriesListResponseSchema>
export const validateCategoriesListResponse = (payload: unknown): CategoriesListResponse => CategoriesListResponseSchema.parse(payload)

export const ProdukListResponseSchema = z.array(ProdukItemResourceSchema)
export type ProdukListResponse = z.infer<typeof ProdukListResponseSchema>
export const validateProdukListResponse = (payload: unknown): ProdukListResponse => ProdukListResponseSchema.parse(payload)

export const ProdukGetResponseSchema = ProdukItemResourceSchema
export type ProdukGetResponse = z.infer<typeof ProdukGetResponseSchema>
export const validateProdukGetResponse = (payload: unknown): ProdukGetResponse => ProdukGetResponseSchema.parse(payload)

export const ProdukReviewsGetResponseSchema = z.object({ summary: z.object({ avg_rating: z.number(), total_review: z.number() }), reviews: z.object({ data: z.array(ProductReviewSchema), current_page: z.number().optional(), total: z.number().optional() }) })
export type ProdukReviewsGetResponse = z.infer<typeof ProdukReviewsGetResponseSchema>
export const validateProdukReviewsGetResponse = (payload: unknown): ProdukReviewsGetResponse => ProdukReviewsGetResponseSchema.parse(payload)

export const ProdukReviewsPostPayloadSchema = z.object({
    rating: z.number(),
    title: z.string().optional().nullable(),
    comment: z.string().optional().nullable(),
  })
export type ProdukReviewsPostPayload = z.infer<typeof ProdukReviewsPostPayloadSchema>
export const validateProdukReviewsPostPayload = (payload: unknown): ProdukReviewsPostPayload => ProdukReviewsPostPayloadSchema.parse(payload)

export const ProdukReviewsPostResponseSchema = z.object({ message: z.string(), data: z.object({ id: z.number(), rating: z.number(), title: z.string().nullable(), comment: z.string().nullable(), is_verified_purchase: z.number(), created_at: z.string().nullable() }) })
export type ProdukReviewsPostResponse = z.infer<typeof ProdukReviewsPostResponseSchema>
export const validateProdukReviewsPostResponse = (payload: unknown): ProdukReviewsPostResponse => ProdukReviewsPostResponseSchema.parse(payload)

export const ProfileListResponseSchema = z.array(z.object({ id: z.number(), name: z.string(), email: z.string() }))
export type ProfileListResponse = z.infer<typeof ProfileListResponseSchema>
export const validateProfileListResponse = (payload: unknown): ProfileListResponse => ProfileListResponseSchema.parse(payload)

export const ProfilePutPayloadSchema = z.object({
    name: z.string(),
    email: z.string(),
  })
export type ProfilePutPayload = z.infer<typeof ProfilePutPayloadSchema>
export const validateProfilePutPayload = (payload: unknown): ProfilePutPayload => ProfilePutPayloadSchema.parse(payload)

export const ProfilePutResponseSchema = z.object({ message: z.string(), data: z.object({ id: z.number(), name: z.string(), email: z.string() }) })
export type ProfilePutResponse = z.infer<typeof ProfilePutResponseSchema>
export const validateProfilePutResponse = (payload: unknown): ProfilePutResponse => ProfilePutResponseSchema.parse(payload)

export const ProfilePatchPayloadSchema = z.object({
    name: z.string(),
    email: z.string(),
  })
export type ProfilePatchPayload = z.infer<typeof ProfilePatchPayloadSchema>
export const validateProfilePatchPayload = (payload: unknown): ProfilePatchPayload => ProfilePatchPayloadSchema.parse(payload)

export const ProfilePatchResponseSchema = z.object({ message: z.string(), data: z.object({ id: z.number(), name: z.string(), email: z.string() }) })
export type ProfilePatchResponse = z.infer<typeof ProfilePatchResponseSchema>
export const validateProfilePatchResponse = (payload: unknown): ProfilePatchResponse => ProfilePatchResponseSchema.parse(payload)

export const OrdersListResponseSchema = z.array(OrderResourceSchema)
export type OrdersListResponse = z.infer<typeof OrdersListResponseSchema>
export const validateOrdersListResponse = (payload: unknown): OrdersListResponse => OrdersListResponseSchema.parse(payload)

export const OrdersGetResponseSchema = OrderResourceSchema
export type OrdersGetResponse = z.infer<typeof OrdersGetResponseSchema>
export const validateOrdersGetResponse = (payload: unknown): OrdersGetResponse => OrdersGetResponseSchema.parse(payload)

export const CartItemsCreatePayloadSchema = z.object({
    produk_item_id: z.string(),
    qty: z.number(),
  })
export type CartItemsCreatePayload = z.infer<typeof CartItemsCreatePayloadSchema>
export const validateCartItemsCreatePayload = (payload: unknown): CartItemsCreatePayload => CartItemsCreatePayloadSchema.parse(payload)

export const CartItemsCreateResponseSchema = OrderResourceSchema
export type CartItemsCreateResponse = z.infer<typeof CartItemsCreateResponseSchema>
export const validateCartItemsCreateResponse = (payload: unknown): CartItemsCreateResponse => CartItemsCreateResponseSchema.parse(payload)

export const CartItemsUpdatePayloadSchema = z.object({
    qty: z.number(),
  })
export type CartItemsUpdatePayload = z.infer<typeof CartItemsUpdatePayloadSchema>
export const validateCartItemsUpdatePayload = (payload: unknown): CartItemsUpdatePayload => CartItemsUpdatePayloadSchema.parse(payload)

export const CartItemsUpdateResponseSchema = OrderResourceSchema
export type CartItemsUpdateResponse = z.infer<typeof CartItemsUpdateResponseSchema>
export const validateCartItemsUpdateResponse = (payload: unknown): CartItemsUpdateResponse => CartItemsUpdateResponseSchema.parse(payload)

export const CartItemsRemoveResponseSchema = OrderResourceSchema
export type CartItemsRemoveResponse = z.infer<typeof CartItemsRemoveResponseSchema>
export const validateCartItemsRemoveResponse = (payload: unknown): CartItemsRemoveResponse => CartItemsRemoveResponseSchema.parse(payload)

export const CartDeleteResponseSchema = z.object({ message: z.string() })
export type CartDeleteResponse = z.infer<typeof CartDeleteResponseSchema>
export const validateCartDeleteResponse = (payload: unknown): CartDeleteResponse => CartDeleteResponseSchema.parse(payload)

export const CartPromoCreatePayloadSchema = z.object({
    code: z.string(),
  })
export type CartPromoCreatePayload = z.infer<typeof CartPromoCreatePayloadSchema>
export const validateCartPromoCreatePayload = (payload: unknown): CartPromoCreatePayload => CartPromoCreatePayloadSchema.parse(payload)

export const CartPromoCreateResponseSchema = OrderResourceSchema
export type CartPromoCreateResponse = z.infer<typeof CartPromoCreateResponseSchema>
export const validateCartPromoCreateResponse = (payload: unknown): CartPromoCreateResponse => CartPromoCreateResponseSchema.parse(payload)

export const CartPromoDeleteResponseSchema = OrderResourceSchema
export type CartPromoDeleteResponse = z.infer<typeof CartPromoDeleteResponseSchema>
export const validateCartPromoDeleteResponse = (payload: unknown): CartPromoDeleteResponse => CartPromoDeleteResponseSchema.parse(payload)

export const CheckoutCreatePayloadSchema = z.object({
    items: z.array(z.object({
    produk_item_id: z.string(),
    qty: z.number(),
  })).optional(),
    shipping_nama: z.string().optional().nullable(),
    shipping_telepon: z.string().optional().nullable(),
    shipping_alamat: z.string().optional().nullable(),
    shipping_kota: z.string().optional().nullable(),
    shipping_kode_pos: z.string().optional().nullable(),
  })
export type CheckoutCreatePayload = z.infer<typeof CheckoutCreatePayloadSchema>
export const validateCheckoutCreatePayload = (payload: unknown): CheckoutCreatePayload => CheckoutCreatePayloadSchema.parse(payload)

export const CheckoutCreateResponseSchema = OrderResourceSchema
export type CheckoutCreateResponse = z.infer<typeof CheckoutCreateResponseSchema>
export const validateCheckoutCreateResponse = (payload: unknown): CheckoutCreateResponse => CheckoutCreateResponseSchema.parse(payload)

export const BuyNowCreatePayloadSchema = z.object({
    produk_item_id: z.string(),
    qty: z.number(),
    shipping_nama: z.string().optional().nullable(),
    shipping_telepon: z.string().optional().nullable(),
    shipping_alamat: z.string().optional().nullable(),
    shipping_kota: z.string().optional().nullable(),
    shipping_kode_pos: z.string().optional().nullable(),
  })
export type BuyNowCreatePayload = z.infer<typeof BuyNowCreatePayloadSchema>
export const validateBuyNowCreatePayload = (payload: unknown): BuyNowCreatePayload => BuyNowCreatePayloadSchema.parse(payload)

export const BuyNowCreateResponseSchema = OrderResourceSchema
export type BuyNowCreateResponse = z.infer<typeof BuyNowCreateResponseSchema>
export const validateBuyNowCreateResponse = (payload: unknown): BuyNowCreateResponse => BuyNowCreateResponseSchema.parse(payload)

export const KeranjangListResponseSchema = z.array(OrderResourceSchema)
export type KeranjangListResponse = z.infer<typeof KeranjangListResponseSchema>
export const validateKeranjangListResponse = (payload: unknown): KeranjangListResponse => KeranjangListResponseSchema.parse(payload)

export const WishlistListResponseSchema = z.array(ProdukItemResourceSchema)
export type WishlistListResponse = z.infer<typeof WishlistListResponseSchema>
export const validateWishlistListResponse = (payload: unknown): WishlistListResponse => WishlistListResponseSchema.parse(payload)

export const WishlistCreatePayloadSchema = z.object({
    produk_item_id: z.string(),
  })
export type WishlistCreatePayload = z.infer<typeof WishlistCreatePayloadSchema>
export const validateWishlistCreatePayload = (payload: unknown): WishlistCreatePayload => WishlistCreatePayloadSchema.parse(payload)

export const WishlistCreateResponseSchema = z.object({ message: z.string() })
export type WishlistCreateResponse = z.infer<typeof WishlistCreateResponseSchema>
export const validateWishlistCreateResponse = (payload: unknown): WishlistCreateResponse => WishlistCreateResponseSchema.parse(payload)

export const WishlistRemoveResponseSchema = z.object({ message: z.string() })
export type WishlistRemoveResponse = z.infer<typeof WishlistRemoveResponseSchema>
export const validateWishlistRemoveResponse = (payload: unknown): WishlistRemoveResponse => WishlistRemoveResponseSchema.parse(payload)

export const PaymentPostPayloadSchema = z.object({
    metode: z.string(),
    detail: z.array(z.unknown()).optional().nullable(),
    provider: z.enum(['mock', 'midtrans']).optional().nullable(),
    provider_txn_id: z.string().optional().nullable(),
    idempotency_key: z.string().optional().nullable(),
    gateway_code: z.string().optional().nullable(),
    gateway_message: z.string().optional().nullable(),
  })
export type PaymentPostPayload = z.infer<typeof PaymentPostPayloadSchema>
export const validatePaymentPostPayload = (payload: unknown): PaymentPostPayload => PaymentPostPayloadSchema.parse(payload)

export const PaymentPostResponseSchema = PaymentResourceSchema
export type PaymentPostResponse = z.infer<typeof PaymentPostResponseSchema>
export const validatePaymentPostResponse = (payload: unknown): PaymentPostResponse => PaymentPostResponseSchema.parse(payload)

export const LogoutCreateResponseSchema = z.object({ message: z.string() })
export type LogoutCreateResponse = z.infer<typeof LogoutCreateResponseSchema>
export const validateLogoutCreateResponse = (payload: unknown): LogoutCreateResponse => LogoutCreateResponseSchema.parse(payload)

export const AdminProdukCreatePayloadSchema = z.object({
    nama: z.string(),
    deskripsi: z.string().optional().nullable(),
    gambar: z.string().optional().nullable(),
    category_id: z.string(),
    harga: z.number(),
    stok: z.number(),
    rating: z.number().optional().nullable(),
    jumlah_review: z.number().optional().nullable(),
  })
export type AdminProdukCreatePayload = z.infer<typeof AdminProdukCreatePayloadSchema>
export const validateAdminProdukCreatePayload = (payload: unknown): AdminProdukCreatePayload => AdminProdukCreatePayloadSchema.parse(payload)

export const AdminProdukCreateResponseSchema = ProdukItemResourceSchema
export type AdminProdukCreateResponse = z.infer<typeof AdminProdukCreateResponseSchema>
export const validateAdminProdukCreateResponse = (payload: unknown): AdminProdukCreateResponse => AdminProdukCreateResponseSchema.parse(payload)
