// Auto-generated by routesync. Do not edit manually.
import { z } from 'zod'

export const ApiSchema = {
  RegisterPost: z.object({
    name: z.string(),
    email: z.string(),
    password: z.string(),
  }),
  LoginPost: z.object({
    email: z.string(),
    password: z.string(),
  }),
  OauthGetProviderRedirect: z.object({
    redirectTo: z.string().optional().nullable(),
  }),
  SocialPostLogin: z.object({
    provider: z.enum(['google', 'facebook', 'apple']),
    providerUserId: z.string(),
    email: z.string(),
    name: z.string().optional().nullable(),
    avatarUrl: z.string().optional().nullable(),
  }),
  ForgotPasswordPost: z.object({
    email: z.string(),
  }),
  ResetPasswordPost: z.object({
    email: z.string(),
    token: z.string(),
    password: z.string(),
  }),
  ProdukPostIdReviews: z.object({
    rating: z.number(),
    title: z.string().optional().nullable(),
    comment: z.string().optional().nullable(),
  }),
  PaymentPostOrderId: z.object({
    metode: z.string(),
    detail: z.array(z.unknown()).optional().nullable(),
    provider: z.enum(['mock', 'midtrans']).optional().nullable(),
    providerTxnId: z.string().optional().nullable(),
    idempotencyKey: z.string().optional().nullable(),
    gatewayCode: z.string().optional().nullable(),
    gatewayMessage: z.string().optional().nullable(),
  }),
  ProfilePut: z.object({
    name: z.string(),
    email: z.string(),
  }),
  ProfilePatch: z.object({
    name: z.string(),
    email: z.string(),
  }),
  CartPostItems: z.object({
    produkItemId: z.string(),
    qty: z.number(),
  }),
  CartPatchItemsProdukItemId: z.object({
    qty: z.number(),
  }),
  CartPostPromo: z.object({
    code: z.string(),
  }),
  CheckoutPost: z.object({
    items: z.array(z.object({
    produkItemId: z.string(),
    qty: z.number(),
  })).optional(),
    shippingNama: z.string().optional().nullable(),
    shippingTelepon: z.string().optional().nullable(),
    shippingAlamat: z.string().optional().nullable(),
    shippingKota: z.string().optional().nullable(),
    shippingKodePos: z.string().optional().nullable(),
  }),
  BuyNowPost: z.object({
    produkItemId: z.string(),
    qty: z.number(),
    shippingNama: z.string().optional().nullable(),
    shippingTelepon: z.string().optional().nullable(),
    shippingAlamat: z.string().optional().nullable(),
    shippingKota: z.string().optional().nullable(),
    shippingKodePos: z.string().optional().nullable(),
  }),
  WishlistPost: z.object({
    produkItemId: z.string(),
  }),
  AdminPostProduk: z.object({
    nama: z.string(),
    deskripsi: z.string().optional().nullable(),
    gambar: z.string().optional().nullable(),
    categoryId: z.string(),
    harga: z.number(),
    stok: z.number(),
    rating: z.number().optional().nullable(),
    jumlahReview: z.number().optional().nullable(),
  }),
}

export type ApiFormValues = {
  RegisterPost: z.infer<typeof ApiSchema.RegisterPost>
  LoginPost: z.infer<typeof ApiSchema.LoginPost>
  OauthGetProviderRedirect: z.infer<typeof ApiSchema.OauthGetProviderRedirect>
  SocialPostLogin: z.infer<typeof ApiSchema.SocialPostLogin>
  ForgotPasswordPost: z.infer<typeof ApiSchema.ForgotPasswordPost>
  ResetPasswordPost: z.infer<typeof ApiSchema.ResetPasswordPost>
  ProdukPostIdReviews: z.infer<typeof ApiSchema.ProdukPostIdReviews>
  PaymentPostOrderId: z.infer<typeof ApiSchema.PaymentPostOrderId>
  ProfilePut: z.infer<typeof ApiSchema.ProfilePut>
  ProfilePatch: z.infer<typeof ApiSchema.ProfilePatch>
  CartPostItems: z.infer<typeof ApiSchema.CartPostItems>
  CartPatchItemsProdukItemId: z.infer<typeof ApiSchema.CartPatchItemsProdukItemId>
  CartPostPromo: z.infer<typeof ApiSchema.CartPostPromo>
  CheckoutPost: z.infer<typeof ApiSchema.CheckoutPost>
  BuyNowPost: z.infer<typeof ApiSchema.BuyNowPost>
  WishlistPost: z.infer<typeof ApiSchema.WishlistPost>
  AdminPostProduk: z.infer<typeof ApiSchema.AdminPostProduk>
}

export const ApiDefaultValues = {
  registerPost: {} as ApiFormValues['RegisterPost'],
  loginPost: {} as ApiFormValues['LoginPost'],
  oauthGetProviderRedirect: {} as ApiFormValues['OauthGetProviderRedirect'],
  socialPostLogin: {} as ApiFormValues['SocialPostLogin'],
  forgotPasswordPost: {} as ApiFormValues['ForgotPasswordPost'],
  resetPasswordPost: {} as ApiFormValues['ResetPasswordPost'],
  produkPostIdReviews: {} as ApiFormValues['ProdukPostIdReviews'],
  paymentPostOrderId: {} as ApiFormValues['PaymentPostOrderId'],
  profilePut: {} as ApiFormValues['ProfilePut'],
  profilePatch: {} as ApiFormValues['ProfilePatch'],
  cartPostItems: {} as ApiFormValues['CartPostItems'],
  cartPatchItemsProdukItemId: {} as ApiFormValues['CartPatchItemsProdukItemId'],
  cartPostPromo: {} as ApiFormValues['CartPostPromo'],
  checkoutPost: {} as ApiFormValues['CheckoutPost'],
  buyNowPost: {} as ApiFormValues['BuyNowPost'],
  wishlistPost: {} as ApiFormValues['WishlistPost'],
  adminPostProduk: {} as ApiFormValues['AdminPostProduk'],
}