// Auto-generated by routesync. Do not edit manually.

import type {
  CategoryApiResponse,
  OrderApiResponse,
  OrderAmountApiResponse,
  OrderDetailApiResponse,
  OrderFinancialApiResponse,
  OrderFulfillmentApiResponse,
  OrderPromotionApiResponse,
  OrderShippingApiResponse,
  PaymentApiResponse,
  PaymentAmountApiResponse,
  PaymentDetailApiResponse,
  PaymentGatewayApiResponse,
  ProductReviewApiResponse,
  ProdukItemApiResponse,
  ProdukItemFrontendApiResponse,
  PromoCodeApiResponse,
  SocialAccountApiResponse,
  UserApiResponse,
  WishlistApiResponse,
  RegisterResponseApiResponse,
  OrderDetailResourceResponse,
  OrderResourceResponse,
  PaymentResourceResponse,
  ProdukItemResourceResponse,
  LoginCreateResponse,
  OauthRedirectGetResponse,
  SocialLoginCreateResponse,
  CategoriesListResponse,
  ProdukReviewsGetResponse,
  ProdukReviewsPostResponse,
  RegisterCreatePayload,
  LoginCreatePayload,
  OauthRedirectGetPayload,
  SocialLoginCreatePayload,
  ForgotPasswordCreatePayload,
  ResetPasswordCreatePayload,
  ProdukReviewsPostPayload,
  ProfilePutPayload,
  ProfilePatchPayload,
  CartItemsCreatePayload,
  CartItemsUpdatePayload,
  CartPromoCreatePayload,
  CheckoutCreatePayload,
  BuyNowCreatePayload,
  WishlistCreatePayload,
  PaymentPostPayload,
  AdminProdukCreatePayload,
} from '../contract/api-contract'
import type {
  CategoryTransformed,
  OrderTransformed,
  OrderAmountTransformed,
  OrderDetailTransformed,
  OrderFinancialTransformed,
  OrderFulfillmentTransformed,
  OrderPromotionTransformed,
  OrderShippingTransformed,
  PaymentTransformed,
  PaymentAmountTransformed,
  PaymentDetailTransformed,
  PaymentGatewayTransformed,
  ProductReviewTransformed,
  ProdukItemTransformed,
  ProdukItemFrontendTransformed,
  PromoCodeTransformed,
  SocialAccountTransformed,
  UserTransformed,
  WishlistTransformed,
  RegisterResponseTransformed,
  OrderDetailResourceTransformed,
  OrderResourceTransformed,
  PaymentResourceTransformed,
  ProdukItemResourceTransformed,
} from '../types/api-read'
import type { ApiFormValues } from '../contract/api-schema'
import { ApiApiField } from '../contract/api-field'

export const toCategoryRead = (api: CategoryApiResponse): CategoryTransformed => ({
  id: api.id,
  nama: api.nama,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toCategoryReadList = (api: CategoryApiResponse[]): CategoryTransformed[] => api.map(toCategoryRead)

export const toOrderRead = (api: OrderApiResponse): OrderTransformed => ({
  id: api.id,
  userId: api.user_id,
  totalHarga: api.total_harga,
  status: api.status,
  orderNumber: api.order_number,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toOrderReadList = (api: OrderApiResponse[]): OrderTransformed[] => api.map(toOrderRead)

export const toOrderAmountRead = (api: OrderAmountApiResponse): OrderAmountTransformed => ({
  id: api.id,
  orderId: api.order_id,
  subtotalMinor: api.subtotal_minor,
  shippingMinor: api.shipping_minor,
  discountMinor: api.discount_minor,
  taxMinor: api.tax_minor,
  totalMinor: api.total_minor,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toOrderAmountReadList = (api: OrderAmountApiResponse[]): OrderAmountTransformed[] => api.map(toOrderAmountRead)

export const toOrderDetailRead = (api: OrderDetailApiResponse): OrderDetailTransformed => ({
  id: api.id,
  orderId: api.order_id,
  produkItemId: api.produk_item_id,
  qty: api.qty,
  harga: api.harga,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
  banana: api.banana,
  potato: api.potato,
  flyingDog: api.flying_dog,
})

export const toOrderDetailReadList = (api: OrderDetailApiResponse[]): OrderDetailTransformed[] => api.map(toOrderDetailRead)

export const toOrderFinancialRead = (api: OrderFinancialApiResponse): OrderFinancialTransformed => ({
  id: api.id,
  orderId: api.order_id,
  financialStatus: api.financial_status,
  refundedAt: api.refunded_at,
  refundReason: api.refund_reason,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toOrderFinancialReadList = (api: OrderFinancialApiResponse[]): OrderFinancialTransformed[] => api.map(toOrderFinancialRead)

export const toOrderFulfillmentRead = (api: OrderFulfillmentApiResponse): OrderFulfillmentTransformed => ({
  id: api.id,
  orderId: api.order_id,
  fulfillmentStatus: api.fulfillment_status,
  processingAt: api.processing_at,
  shippedAt: api.shipped_at,
  completedAt: api.completed_at,
  canceledAt: api.canceled_at,
  cancelReason: api.cancel_reason,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toOrderFulfillmentReadList = (api: OrderFulfillmentApiResponse[]): OrderFulfillmentTransformed[] => api.map(toOrderFulfillmentRead)

export const toOrderPromotionRead = (api: OrderPromotionApiResponse): OrderPromotionTransformed => ({
  id: api.id,
  orderId: api.order_id,
  promoCodeId: api.promo_code_id,
  promoCode: api.promo_code,
  discountMinor: api.discount_minor,
  metadata: api.metadata,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toOrderPromotionReadList = (api: OrderPromotionApiResponse[]): OrderPromotionTransformed[] => api.map(toOrderPromotionRead)

export const toOrderShippingRead = (api: OrderShippingApiResponse): OrderShippingTransformed => ({
  id: api.id,
  orderId: api.order_id,
  nama: api.nama,
  telepon: api.telepon,
  alamat: api.alamat,
  kota: api.kota,
  kodePos: api.kode_pos,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toOrderShippingReadList = (api: OrderShippingApiResponse[]): OrderShippingTransformed[] => api.map(toOrderShippingRead)

export const toPaymentRead = (api: PaymentApiResponse): PaymentTransformed => ({
  id: api.id,
  orderId: api.order_id,
  metode: api.metode,
  status: api.status,
  paidAt: api.paid_at,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toPaymentReadList = (api: PaymentApiResponse[]): PaymentTransformed[] => api.map(toPaymentRead)

export const toPaymentAmountRead = (api: PaymentAmountApiResponse): PaymentAmountTransformed => ({
  id: api.id,
  paymentId: api.payment_id,
  currencyCode: api.currency_code,
  amountMinor: api.amount_minor,
  feeMinor: api.fee_minor,
  netAmountMinor: api.net_amount_minor,
  refundAmountMinor: api.refund_amount_minor,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toPaymentAmountReadList = (api: PaymentAmountApiResponse[]): PaymentAmountTransformed[] => api.map(toPaymentAmountRead)

export const toPaymentDetailRead = (api: PaymentDetailApiResponse): PaymentDetailTransformed => ({
  id: api.id,
  paymentId: api.payment_id,
  detail: api.detail,
  payloadHash: api.payload_hash,
  payloadReceivedAt: api.payload_received_at,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toPaymentDetailReadList = (api: PaymentDetailApiResponse[]): PaymentDetailTransformed[] => api.map(toPaymentDetailRead)

export const toPaymentGatewayRead = (api: PaymentGatewayApiResponse): PaymentGatewayTransformed => ({
  id: api.id,
  paymentId: api.payment_id,
  provider: api.provider,
  providerTxnId: api.provider_txn_id,
  idempotencyKey: api.idempotency_key,
  gatewayStatus: api.gateway_status,
  gatewayCode: api.gateway_code,
  gatewayMessage: api.gateway_message,
  authorizedAt: api.authorized_at,
  capturedAt: api.captured_at,
  failedAt: api.failed_at,
  refundedAt: api.refunded_at,
  reconciledAt: api.reconciled_at,
  reconciliationBatchId: api.reconciliation_batch_id,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toPaymentGatewayReadList = (api: PaymentGatewayApiResponse[]): PaymentGatewayTransformed[] => api.map(toPaymentGatewayRead)

export const toProductReviewRead = (api: ProductReviewApiResponse): ProductReviewTransformed => ({
  id: api.id,
  produkItemId: api.produk_item_id,
  userId: api.user_id,
  rating: api.rating,
  title: api.title,
  comment: api.comment,
  isVerifiedPurchase: api.is_verified_purchase,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toProductReviewReadList = (api: ProductReviewApiResponse[]): ProductReviewTransformed[] => api.map(toProductReviewRead)

export const toProdukItemRead = (api: ProdukItemApiResponse): ProdukItemTransformed => ({
  id: api.id,
  nama: api.nama,
  deskripsi: api.deskripsi,
  categoryId: api.category_id,
  harga: api.harga,
  stok: api.stok,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
  image: api.image,
  imageUrl: api.image_url,
  categoryName: api.category_name,
  rating: api.rating,
  reviewCount: api.review_count,
})

export const toProdukItemReadList = (api: ProdukItemApiResponse[]): ProdukItemTransformed[] => api.map(toProdukItemRead)

export const toProdukItemFrontendRead = (api: ProdukItemFrontendApiResponse): ProdukItemFrontendTransformed => ({
  id: api.id,
  produkItemId: api.produk_item_id,
  gambar: api.gambar,
  rating: api.rating,
  jumlahReview: api.jumlah_review,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toProdukItemFrontendReadList = (api: ProdukItemFrontendApiResponse[]): ProdukItemFrontendTransformed[] => api.map(toProdukItemFrontendRead)

export const toPromoCodeRead = (api: PromoCodeApiResponse): PromoCodeTransformed => ({
  id: api.id,
  code: api.code,
  discountType: api.discount_type,
  discountValue: api.discount_value,
  maxDiscountMinor: api.max_discount_minor,
  minOrderMinor: api.min_order_minor,
  usageLimit: api.usage_limit,
  usedCount: api.used_count,
  isActive: api.is_active,
  startsAt: api.starts_at,
  endsAt: api.ends_at,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toPromoCodeReadList = (api: PromoCodeApiResponse[]): PromoCodeTransformed[] => api.map(toPromoCodeRead)

export const toSocialAccountRead = (api: SocialAccountApiResponse): SocialAccountTransformed => ({
  id: api.id,
  userId: api.user_id,
  provider: api.provider,
  providerUserId: api.provider_user_id,
  email: api.email,
  avatarUrl: api.avatar_url,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toSocialAccountReadList = (api: SocialAccountApiResponse[]): SocialAccountTransformed[] => api.map(toSocialAccountRead)

export const toUserRead = (api: UserApiResponse): UserTransformed => ({
  id: api.id,
  name: api.name,
  email: api.email,
  role: api.role,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toUserReadList = (api: UserApiResponse[]): UserTransformed[] => api.map(toUserRead)

export const toWishlistRead = (api: WishlistApiResponse): WishlistTransformed => ({
  id: api.id,
  userId: api.user_id,
  produkItemId: api.produk_item_id,
  createdAt: api.created_at,
  updatedAt: api.updated_at,
})

export const toWishlistReadList = (api: WishlistApiResponse[]): WishlistTransformed[] => api.map(toWishlistRead)

export const toRegisterResponseRead = (api: RegisterResponseApiResponse): RegisterResponseTransformed => ({
  success: api.success,
  message: api.message,
  data: api.data,
})

export const toRegisterResponseReadList = (api: RegisterResponseApiResponse[]): RegisterResponseTransformed[] => api.map(toRegisterResponseRead)

export const toOrderDetailResourceRead = (api: OrderDetailResourceResponse): OrderDetailResourceTransformed => ({
  id: api.id,
  produkItemId: api.produk_item_id,
  produkId: api.produk?.id,
  produkNama: api.produk?.nama,
  produkGambar: api.produk?.gambar,
  produkImageUrl: api.produk?.image_url,
  qty: api.qty,
  harga: api.harga,
  subtotal: api.subtotal,
  banana: api.banana,
  potato: api.potato,
  flyingDog: api.flying_dog,
  foo: api.foo,
})

export const toOrderDetailResourceReadList = (api: OrderDetailResourceResponse[]): OrderDetailResourceTransformed[] => api.map(toOrderDetailResourceRead)

export const toOrderResourceRead = (api: OrderResourceResponse): OrderResourceTransformed => ({
  id: api.id,
  status: api.status,
  totalHarga: api.total_harga,
  invoiceNumber: api.invoice_number,
  paymentStatus: api.payment_status,
  financialStatus: api.financial_status,
  fulfillmentStatus: api.fulfillment_status,
  subtotalMinor: api.subtotal_minor,
  discountMinor: api.discount_minor,
  shippingMinor: api.shipping_minor,
  taxMinor: api.tax_minor,
  totalHargaMinor: api.total_harga_minor,
  items: api.items?.map((item) => toOrderDetailResourceRead(item)) ?? [],
  promotionCode: api.promotion?.code,
  promotionDiscountMinor: api.promotion?.discount_minor,
  shippingNama: api.shipping?.nama,
  shippingTelepon: api.shipping?.telepon,
  shippingAlamat: api.shipping?.alamat,
  shippingKota: api.shipping?.kota,
  shippingKodePos: api.shipping?.kode_pos,
  createdAt: api.created_at,
})

export const toOrderResourceReadList = (api: OrderResourceResponse[]): OrderResourceTransformed[] => api.map(toOrderResourceRead)

export const toPaymentResourceRead = (api: PaymentResourceResponse): PaymentResourceTransformed => ({
  id: api.id,
  orderId: api.order_id,
  invoiceNumber: api.invoice_number,
  metode: api.metode,
  detail: api.detail,
  status: api.status,
  paidAt: api.paid_at,
  provider: api.provider,
  providerTxnId: api.provider_txn_id,
  gatewayStatus: api.gateway_status,
  amountMinor: api.amount_minor,
  refundAmountMinor: api.refund_amount_minor,
  items: api.items?.map((item) => toOrderDetailResourceRead(item)) ?? [],
  promotionCode: api.promotion?.code,
  promotionDiscountMinor: api.promotion?.discount_minor,
  gatewayName: api.gateway?.name,
  gatewayOrderId: api.gateway?.order_id,
  gatewayToken: api.gateway?.token,
  gatewayRedirectUrl: api.gateway?.redirect_url,
  totalHarga: api.total_harga,
})

export const toPaymentResourceReadList = (api: PaymentResourceResponse[]): PaymentResourceTransformed[] => api.map(toPaymentResourceRead)

export const toProdukItemResourceRead = (api: ProdukItemResourceResponse): ProdukItemResourceTransformed => ({
  id: api.id,
  nama: api.nama,
  deskripsi: api.deskripsi,
  image: api.image,
  imageUrl: api.image_url,
  categoryId: api.category_id,
  categoryName: api.category_name,
  harga: api.harga,
  stok: api.stok,
  rating: api.rating,
  reviewCount: api.review_count,
})

export const toProdukItemResourceReadList = (api: ProdukItemResourceResponse[]): ProdukItemResourceTransformed[] => api.map(toProdukItemResourceRead)

export const toLoginCreateResponseRead = (api: LoginCreateResponse): { success: boolean; message: string; data: { token: string; user: { id: number; name: string; email: string; role: string; createdAt: string; updatedAt: string } } } | undefined => (api)

export const toOauthRedirectGetResponseRead = (api: OauthRedirectGetResponse): { provider: string; authUrl: unknown } | undefined => (api)

export const toSocialLoginCreateResponseRead = (api: SocialLoginCreateResponse): { token: string; user: { id: number; name: string; email: string; role: string; createdAt: string; updatedAt: string } } | undefined => (api)

export const toCategoriesListResponseRead = (api: CategoriesListResponse): { data: CategoryTransformed[] } | undefined => (api)

export const toProdukReviewsGetResponseRead = (api: ProdukReviewsGetResponse): { summary: { avgRating: number; totalReview: number }; reviews: { data: ProductReviewTransformed[]; currentPage?: number; total?: number } } | undefined => (api)

export const toProdukReviewsPostResponseRead = (api: ProdukReviewsPostResponse): { message: string; data: { id: number; rating: number; title: (string) | null; comment: (string) | null; isVerifiedPurchase: number; createdAt: (string) | null } } | undefined => (api)

export const toApiRegisterCreate = (form: ApiFormValues['RegisterCreate']): RegisterCreatePayload => ({
  [ApiApiField.NAME]: form.name,
  [ApiApiField.EMAIL]: form.email,
  [ApiApiField.PASSWORD]: form.password,
})

export const toApiLoginCreate = (form: ApiFormValues['LoginCreate']): LoginCreatePayload => ({
  [ApiApiField.EMAIL]: form.email,
  [ApiApiField.PASSWORD]: form.password,
})

export const toApiOauthRedirectGet = (form: ApiFormValues['OauthRedirectGet']): OauthRedirectGetPayload => ({
  [ApiApiField.REDIRECTTO]: form.redirectTo,
})

export const toApiSocialLoginCreate = (form: ApiFormValues['SocialLoginCreate']): SocialLoginCreatePayload => ({
  [ApiApiField.PROVIDER]: form.provider,
  [ApiApiField.PROVIDERUSERID]: form.providerUserId,
  [ApiApiField.EMAIL]: form.email,
  [ApiApiField.NAME]: form.name,
  [ApiApiField.AVATARURL]: form.avatarUrl,
})

export const toApiForgotPasswordCreate = (form: ApiFormValues['ForgotPasswordCreate']): ForgotPasswordCreatePayload => ({
  [ApiApiField.EMAIL]: form.email,
})

export const toApiResetPasswordCreate = (form: ApiFormValues['ResetPasswordCreate']): ResetPasswordCreatePayload => ({
  [ApiApiField.EMAIL]: form.email,
  [ApiApiField.TOKEN]: form.token,
  [ApiApiField.PASSWORD]: form.password,
})

export const toApiProdukReviewsPost = (form: ApiFormValues['ProdukReviewsPost']): ProdukReviewsPostPayload => ({
  [ApiApiField.RATING]: form.rating,
  [ApiApiField.TITLE]: form.title,
  [ApiApiField.COMMENT]: form.comment,
})

export const toApiProfilePut = (form: ApiFormValues['ProfilePut']): ProfilePutPayload => ({
  [ApiApiField.NAME]: form.name,
  [ApiApiField.EMAIL]: form.email,
})

export const toApiProfilePatch = (form: ApiFormValues['ProfilePatch']): ProfilePatchPayload => ({
  [ApiApiField.NAME]: form.name,
  [ApiApiField.EMAIL]: form.email,
})

export const toApiCartItemsCreate = (form: ApiFormValues['CartItemsCreate']): CartItemsCreatePayload => ({
  [ApiApiField.PRODUKITEMID]: form.produkItemId,
  [ApiApiField.QTY]: form.qty,
})

export const toApiCartItemsUpdate = (form: ApiFormValues['CartItemsUpdate']): CartItemsUpdatePayload => ({
  [ApiApiField.QTY]: form.qty,
})

export const toApiCartPromoCreate = (form: ApiFormValues['CartPromoCreate']): CartPromoCreatePayload => ({
  [ApiApiField.CODE]: form.code,
})

export const toApiCheckoutCreate = (form: ApiFormValues['CheckoutCreate']): CheckoutCreatePayload => ({
  [ApiApiField.ITEMS]: form.items?.map((item1) => ({
      [ApiApiField.PRODUKITEMID]: item1.produkItemId,
      [ApiApiField.QTY]: item1.qty,
    })),
  [ApiApiField.SHIPPINGNAMA]: form.shippingNama,
  [ApiApiField.SHIPPINGTELEPON]: form.shippingTelepon,
  [ApiApiField.SHIPPINGALAMAT]: form.shippingAlamat,
  [ApiApiField.SHIPPINGKOTA]: form.shippingKota,
  [ApiApiField.SHIPPINGKODEPOS]: form.shippingKodePos,
})

export const toApiBuyNowCreate = (form: ApiFormValues['BuyNowCreate']): BuyNowCreatePayload => ({
  [ApiApiField.PRODUKITEMID]: form.produkItemId,
  [ApiApiField.QTY]: form.qty,
  [ApiApiField.SHIPPINGNAMA]: form.shippingNama,
  [ApiApiField.SHIPPINGTELEPON]: form.shippingTelepon,
  [ApiApiField.SHIPPINGALAMAT]: form.shippingAlamat,
  [ApiApiField.SHIPPINGKOTA]: form.shippingKota,
  [ApiApiField.SHIPPINGKODEPOS]: form.shippingKodePos,
})

export const toApiWishlistCreate = (form: ApiFormValues['WishlistCreate']): WishlistCreatePayload => ({
  [ApiApiField.PRODUKITEMID]: form.produkItemId,
})

export const toApiPaymentPost = (form: ApiFormValues['PaymentPost']): PaymentPostPayload => ({
  [ApiApiField.METODE]: form.metode,
  [ApiApiField.DETAIL]: form.detail,
  [ApiApiField.PROVIDER]: form.provider,
  [ApiApiField.PROVIDERTXNID]: form.providerTxnId,
  [ApiApiField.IDEMPOTENCYKEY]: form.idempotencyKey,
  [ApiApiField.GATEWAYCODE]: form.gatewayCode,
  [ApiApiField.GATEWAYMESSAGE]: form.gatewayMessage,
})

export const toApiAdminProdukCreate = (form: ApiFormValues['AdminProdukCreate']): AdminProdukCreatePayload => ({
  [ApiApiField.NAMA]: form.nama,
  [ApiApiField.DESKRIPSI]: form.deskripsi,
  [ApiApiField.GAMBAR]: form.gambar,
  [ApiApiField.CATEGORYID]: form.categoryId,
  [ApiApiField.HARGA]: form.harga,
  [ApiApiField.STOK]: form.stok,
  [ApiApiField.RATING]: form.rating,
  [ApiApiField.JUMLAHREVIEW]: form.jumlahReview,
})
