// Auto-generated by routesync. Do not edit manually.
// Generated at: 2026-06-06T05:13:03.295Z

import { defineApi, endpoint } from 'routesync'
import { validateAdminProdukCreatePayload, validateBuyNowCreatePayload, validateCartDeleteResponse, validateCartItemsCreatePayload, validateCartItemsUpdatePayload, validateCartPromoCreatePayload, validateCategoriesListResponse, validateCheckoutCreatePayload, validateForgotPasswordCreatePayload, validateLoginCreatePayload, validateLoginCreateResponse, validateLogoutCreateResponse, validateOauthCallbackGetResponse, validateOauthCallbackPostResponse, validateOauthRedirectGetPayload, validateOauthRedirectGetResponse, validateOrderResource, validateOrdersListResponse, validatePaymentPostPayload, validatePaymentResource, validateProdukItemResource, validateProdukListResponse, validateProdukReviewsGetResponse, validateProdukReviewsPostPayload, validateProdukReviewsPostResponse, validateProfileListResponse, validateProfilePatchPayload, validateProfilePatchResponse, validateProfilePutPayload, validateProfilePutResponse, validateRegisterCreatePayload, validateRegisterResponse, validateResetPasswordCreatePayload, validateResetPasswordCreateResponse, validateSocialLoginCreatePayload, validateSocialLoginCreateResponse, validateWishlistCreatePayload, validateWishlistCreateResponse, validateWishlistListResponse, validateWishlistRemoveResponse } from './contract/api-contract'
import { toApiAdminProdukCreate, toApiBuyNowCreate, toApiCartItemsCreate, toApiCartItemsUpdate, toApiCartPromoCreate, toApiCheckoutCreate, toApiForgotPasswordCreate, toApiLoginCreate, toApiOauthRedirectGet, toApiPaymentPost, toApiProdukReviewsPost, toApiProfilePatch, toApiProfilePut, toApiRegisterCreate, toApiResetPasswordCreate, toApiSocialLoginCreate, toApiWishlistCreate, toCategoriesListResponseRead, toCategoryReadList, toLoginCreateResponseRead, toOauthRedirectGetResponseRead, toOrderResourceRead, toOrderResourceReadList, toPaymentResourceRead, toProductReviewRead, toProdukItemResourceRead, toProdukItemResourceReadList, toProdukReviewsGetResponseRead, toProdukReviewsPostResponseRead, toRegisterResponseRead, toSocialLoginCreateResponseRead } from './mappers/api-mapper'


/* =========================
   APPLICATION CONSTANTS
========================= */

export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost/api'

export const API_ENDPOINTS = {
  ADMIN_PRODUK: '/admin/produk',
  BUY_NOW: '/buy-now',
  CART: '/cart',
  CART_ITEMS: '/cart/items',
  CART_ITEM: (produkItemId: string | number) => `/cart/items/${produkItemId}`,
  CART_PROMO: '/cart/promo',
  CATEGORIES: '/categories',
  CHECKOUT: '/checkout',
  FORGOT_PASSWORD: '/forgot-password',
  KERANJANG: '/keranjang',
  LOGIN: '/login',
  LOGOUT: '/logout',
  OAUTH_PROVIDER_CALLBACK: (provider: string | number) => `/oauth/${provider}/callback`,
  OAUTH_PROVIDER_REDIRECT: (provider: string | number) => `/oauth/${provider}/redirect`,
  ORDERS: '/orders',
  ORDERS_DETAIL: (id: string | number) => `/orders/${id}`,
  ORDERS_DETAIL_INVOICE: (id: string | number) => `/orders/${id}/invoice`,
  PAYMENT_ORDER_ID: (orderId: string | number) => `/payment/${orderId}`,
  PAYMENT_WEBHOOK: '/payment/webhook',
  PRODUK: '/produk',
  PRODUK_DETAIL: (id: string | number) => `/produk/${id}`,
  PRODUK_DETAIL_REVIEWS: (id: string | number) => `/produk/${id}/reviews`,
  PROFILE: '/profile',
  REGISTER: '/register',
  RESET_PASSWORD: '/reset-password',
  SOCIAL_LOGIN: '/social/login',
  WISHLIST: '/wishlist',
  WISHLIST_PRODUK_ITEM_ID: (produkItemId: string | number) => `/wishlist/${produkItemId}`,
} as const

export const ROUTES = {
  HOME: '/',
  OAUTH_DETAIL_REDIRECT: (provider: string | number) => `/oauth/${provider}/redirect`,
  OAUTH_DETAIL_CALLBACK: (provider: string | number) => `/oauth/${provider}/callback`,
  CATEGORIES: '/categories',
  PRODUK: '/produk',
  PRODUK_DETAIL: (id: string | number) => `/produk/${id}`,
  PRODUK_DETAIL_REVIEWS: (id: string | number) => `/produk/${id}/reviews`,
  PROFILE: '/profile',
  ORDERS: '/orders',
  ORDERS_DETAIL: (id: string | number) => `/orders/${id}`,
  KERANJANG: '/keranjang',
  WISHLIST: '/wishlist',
  ORDERS_DETAIL_INVOICE: (id: string | number) => `/orders/${id}/invoice`,
} as const

export const ORDER_STATUS = {
  PENDING: 'pending',
  PAID: 'paid',
  CANCELED: 'canceled',
} as const

export type OrderStatus = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS]

export const ORDERFINANCIAL_FINANCIAL_STATUS = {
  PENDING: 'pending',
  PAID: 'paid',
  PARTIALLY_REFUNDED: 'partially_refunded',
  REFUNDED: 'refunded',
  FAILED: 'failed',
  CANCELLED: 'cancelled',
} as const

export type OrderFinancialFinancial_status = (typeof ORDERFINANCIAL_FINANCIAL_STATUS)[keyof typeof ORDERFINANCIAL_FINANCIAL_STATUS]

export const ORDERFULFILLMENT_FULFILLMENT_STATUS = {
  UNFULFILLED: 'unfulfilled',
  PROCESSING: 'processing',
  SHIPPED: 'shipped',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
  RETURNED: 'returned',
} as const

export type OrderFulfillmentFulfillment_status = (typeof ORDERFULFILLMENT_FULFILLMENT_STATUS)[keyof typeof ORDERFULFILLMENT_FULFILLMENT_STATUS]

export const PAYMENT_STATUS = {
  PENDING: 'pending',
  SUCCESS: 'success',
  FAILED: 'failed',
} as const

export type PaymentStatus = (typeof PAYMENT_STATUS)[keyof typeof PAYMENT_STATUS]

export const PROMOCODE_DISCOUNT_TYPE = {
  FIXED_MINOR: 'fixed_minor',
  PERCENT: 'percent',
} as const

export type PromoCodeDiscount_type = (typeof PROMOCODE_DISCOUNT_TYPE)[keyof typeof PROMOCODE_DISCOUNT_TYPE]

export const USER_ROLE = {
  ADMIN: 'admin',
  USER: 'user',
} as const

export type UserRole = (typeof USER_ROLE)[keyof typeof USER_ROLE]


export const api = defineApi({
  register: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.REGISTER,
      contract: {
        body: validateRegisterCreatePayload,
        response: validateRegisterResponse,
      },
      mapper: {
        response: toRegisterResponseRead,
        body: toApiRegisterCreate,
      },
    }),
  },
  login: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.LOGIN,
      contract: {
        body: validateLoginCreatePayload,
        response: validateLoginCreateResponse,
      },
      mapper: {
        response: toLoginCreateResponseRead,
        body: toApiLoginCreate,
      },
    }),
  },
  oauthRedirect: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.OAUTH_PROVIDER_REDIRECT,
      contract: {
        body: validateOauthRedirectGetPayload,
        response: validateOauthRedirectGetResponse,
      },
      mapper: {
        response: toOauthRedirectGetResponseRead,
        body: toApiOauthRedirectGet,
      },
    }),
  },
  oauthCallback: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.OAUTH_PROVIDER_CALLBACK,
      contract: {
        response: validateOauthCallbackGetResponse,
      },
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.OAUTH_PROVIDER_CALLBACK,
      contract: {
        response: validateOauthCallbackPostResponse,
      },
    }),
  },
  socialLogin: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.SOCIAL_LOGIN,
      contract: {
        body: validateSocialLoginCreatePayload,
        response: validateSocialLoginCreateResponse,
      },
      mapper: {
        response: toSocialLoginCreateResponseRead,
        body: toApiSocialLoginCreate,
      },
    }),
  },
  forgotPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.FORGOT_PASSWORD,
      contract: {
        body: validateForgotPasswordCreatePayload,
      },
      mapper: {
        body: toApiForgotPasswordCreate,
      },
    }),
  },
  resetPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.RESET_PASSWORD,
      contract: {
        body: validateResetPasswordCreatePayload,
        response: validateResetPasswordCreateResponse,
      },
      mapper: {
        body: toApiResetPasswordCreate,
      },
    }),
  },
  categories: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.CATEGORIES,
      contract: {
        response: validateCategoriesListResponse,
      },
      mapper: {
        response: toCategoriesListResponseRead,
      },
    }),
  },
  produk: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK,
      contract: {
        response: validateProdukListResponse,
      },
      mapper: {
        response: toProdukItemResourceReadList,
      },
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK_DETAIL,
      contract: {
        response: validateProdukItemResource,
      },
      mapper: {
        response: toProdukItemResourceRead,
      },
    }),
  },
  produkReviews: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK_DETAIL_REVIEWS,
      contract: {
        response: validateProdukReviewsGetResponse,
      },
      mapper: {
        response: toProdukReviewsGetResponseRead,
      },
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PRODUK_DETAIL_REVIEWS,
      auth: true,
      contract: {
        body: validateProdukReviewsPostPayload,
        response: validateProdukReviewsPostResponse,
      },
      mapper: {
        response: toProdukReviewsPostResponseRead,
        body: toApiProdukReviewsPost,
      },
    }),
  },
  paymentWebhook: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PAYMENT_WEBHOOK,
    }),
  },
  profile: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
      contract: {
        response: validateProfileListResponse,
      },
    }),
    put: endpoint({
      method: 'PUT',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
      contract: {
        body: validateProfilePutPayload,
        response: validateProfilePutResponse,
      },
      mapper: {
        body: toApiProfilePut,
      },
    }),
    patch: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
      contract: {
        body: validateProfilePatchPayload,
        response: validateProfilePatchResponse,
      },
      mapper: {
        body: toApiProfilePatch,
      },
    }),
  },
  orders: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS,
      auth: true,
      contract: {
        response: validateOrdersListResponse,
      },
      mapper: {
        response: toOrderResourceReadList,
      },
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS_DETAIL,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  cartItems: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CART_ITEMS,
      auth: true,
      contract: {
        body: validateCartItemsCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCartItemsCreate,
      },
    }),
    update: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.CART_ITEM,
      auth: true,
      contract: {
        body: validateCartItemsUpdatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCartItemsUpdate,
      },
    }),
    remove: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART_ITEM,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  cart: {
    delete: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART,
      auth: true,
      contract: {
        response: validateCartDeleteResponse,
      },
    }),
  },
  cartPromo: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CART_PROMO,
      auth: true,
      contract: {
        body: validateCartPromoCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCartPromoCreate,
      },
    }),
    delete: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART_PROMO,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  checkout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CHECKOUT,
      auth: true,
      contract: {
        body: validateCheckoutCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCheckoutCreate,
      },
    }),
  },
  buyNow: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.BUY_NOW,
      auth: true,
      contract: {
        body: validateBuyNowCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiBuyNowCreate,
      },
    }),
  },
  keranjang: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.KERANJANG,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  wishlist: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.WISHLIST,
      auth: true,
      contract: {
        response: validateWishlistListResponse,
      },
      mapper: {
        response: toProdukItemResourceReadList,
      },
    }),
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.WISHLIST,
      auth: true,
      contract: {
        body: validateWishlistCreatePayload,
        response: validateWishlistCreateResponse,
      },
      mapper: {
        body: toApiWishlistCreate,
      },
    }),
    remove: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.WISHLIST_PRODUK_ITEM_ID,
      auth: true,
      contract: {
        response: validateWishlistRemoveResponse,
      },
    }),
  },
  payment: {
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PAYMENT_ORDER_ID,
      auth: true,
      contract: {
        body: validatePaymentPostPayload,
        response: validatePaymentResource,
      },
      mapper: {
        response: toPaymentResourceRead,
        body: toApiPaymentPost,
      },
    }),
  },
  ordersInvoice: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS_DETAIL_INVOICE,
      auth: true,
    }),
  },
  logout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.LOGOUT,
      auth: true,
      contract: {
        response: validateLogoutCreateResponse,
      },
    }),
  },
  adminProduk: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.ADMIN_PRODUK,
      auth: true,
      contract: {
        body: validateAdminProdukCreatePayload,
        response: validateProdukItemResource,
      },
      mapper: {
        response: toProdukItemResourceRead,
        body: toApiAdminProdukCreate,
      },
    }),
  },
})

export default api
