// Auto-generated by routesync. Do not edit manually.
// Generated at: 2026-07-16T00:59:21.329Z

import { defineApi, endpoint } from 'routesync'
import { API_URL, API_ENDPOINTS, ROUTES, Enums } from './constants'
import { validateCartResponse, validateCategoriesResponse, validateLoginResponse, validateLogoutResponse, validateOauthCallbackCreateResponse, validateOauthCallbackGetResponse, validateOauthRedirectResponse, validateOrderResource, validateOrdersListResponse, validatePaymentResource, validateProdukItemResource, validateProdukListResponse, validateProdukReviewsCreateResponse, validateProdukReviewsGetResponse, validateProfileListResponse, validateProfileUpdateResponse, validateRegisterResponse, validateResetPasswordResponse, validateSocialLoginResponse, validateWishlistCreateResponse, validateWishlistListResponse, validateWishlistRemoveResponse } from './contract/api-contract'
import { validateAdminProdukCreatePayload, validateBuyNowCreatePayload, validateCartItemsCreatePayload, validateCartItemsUpdatePayload, validateCartPromoCreatePayload, validateCheckoutCreatePayload, validateForgotPasswordCreatePayload, validateLoginCreatePayload, validateOauthRedirectGetPayload, validatePaymentCreatePayload, validateProdukReviewsCreatePayload, validateProfileUpdatePayload, validateRegisterCreatePayload, validateResetPasswordCreatePayload, validateSocialLoginCreatePayload, validateWishlistCreatePayload } from './contract/api-schema'
import { toApiAdminProdukCreate, toApiBuyNowCreate, toApiCartItemsCreate, toApiCartItemsUpdate, toApiCartPromoCreate, toApiCheckoutCreate, toApiForgotPasswordCreate, toApiLoginCreate, toApiOauthRedirectGet, toApiPaymentCreate, toApiProdukReviewsCreate, toApiProfileUpdate, toApiRegisterCreate, toApiResetPasswordCreate, toApiSocialLoginCreate, toApiWishlistCreate, toCategoriesResponseRead, toLoginResponseRead, toOauthRedirectResponseRead, toOrderResourceRead, toOrdersListResponseRead, toPaymentResourceRead, toProductReviewReadList, toProdukItemResourceRead, toProdukListResponseRead, toProdukReviewsCreateResponseRead, toProdukReviewsGetResponseRead, toRegisterResponseRead, toSocialLoginResponseRead, toWishlistListResponseRead } from './mappers/api-mapper'

export const api = defineApi({
  register: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.REGISTER,
      contract: {
        body: validateRegisterCreatePayload,
        response: validateRegisterResponse,
      },
      mapper: {
        response: toRegisterResponseRead,
        body: toApiRegisterCreate,
      },
    }),
  },
  login: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.LOGIN,
      contract: {
        body: validateLoginCreatePayload,
        response: validateLoginResponse,
      },
      mapper: {
        response: toLoginResponseRead,
        body: toApiLoginCreate,
      },
    }),
  },
  oauthRedirect: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.OAUTH_PROVIDER_REDIRECT,
      contract: {
        body: validateOauthRedirectGetPayload,
        response: validateOauthRedirectResponse,
      },
      mapper: {
        response: toOauthRedirectResponseRead,
        body: toApiOauthRedirectGet,
      },
    }),
  },
  oauthCallback: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.OAUTH_PROVIDER_CALLBACK,
      contract: {
        response: validateOauthCallbackGetResponse,
      },
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.OAUTH_PROVIDER_CALLBACK,
      contract: {
        response: validateOauthCallbackCreateResponse,
      },
    }),
  },
  socialLogin: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.SOCIAL_LOGIN,
      contract: {
        body: validateSocialLoginCreatePayload,
        response: validateSocialLoginResponse,
      },
      mapper: {
        response: toSocialLoginResponseRead,
        body: toApiSocialLoginCreate,
      },
    }),
  },
  forgotPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.FORGOT_PASSWORD,
      contract: {
        body: validateForgotPasswordCreatePayload,
      },
      mapper: {
        body: toApiForgotPasswordCreate,
      },
    }),
  },
  resetPassword: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.RESET_PASSWORD,
      contract: {
        body: validateResetPasswordCreatePayload,
        response: validateResetPasswordResponse,
      },
      mapper: {
        body: toApiResetPasswordCreate,
      },
    }),
  },
  categories: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.CATEGORIES,
      contract: {
        response: validateCategoriesResponse,
      },
      mapper: {
        response: toCategoriesResponseRead,
      },
    }),
  },
  produk: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK,
      contract: {
        response: validateProdukListResponse,
      },
      mapper: {
        response: toProdukListResponseRead,
      },
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK_DETAIL,
      contract: {
        response: validateProdukItemResource,
      },
      mapper: {
        response: toProdukItemResourceRead,
      },
    }),
  },
  produkReviews: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PRODUK_DETAIL_REVIEWS,
      contract: {
        response: validateProdukReviewsGetResponse,
      },
      mapper: {
        response: toProdukReviewsGetResponseRead,
      },
    }),
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PRODUK_DETAIL_REVIEWS,
      auth: true,
      contract: {
        body: validateProdukReviewsCreatePayload,
        response: validateProdukReviewsCreateResponse,
      },
      mapper: {
        response: toProdukReviewsCreateResponseRead,
        body: toApiProdukReviewsCreate,
      },
    }),
  },
  paymentWebhook: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PAYMENT_WEBHOOK,
    }),
  },
  profile: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
      contract: {
        response: validateProfileListResponse,
      },
    }),
    put: endpoint({
      method: 'PUT',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
      contract: {
        body: validateProfileUpdatePayload,
        response: validateProfileUpdateResponse,
      },
      mapper: {
        body: toApiProfileUpdate,
      },
    }),
    patch: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.PROFILE,
      auth: true,
      contract: {
        body: validateProfileUpdatePayload,
        response: validateProfileUpdateResponse,
      },
      mapper: {
        body: toApiProfileUpdate,
      },
    }),
  },
  orders: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS,
      auth: true,
      contract: {
        response: validateOrdersListResponse,
      },
      mapper: {
        response: toOrdersListResponseRead,
      },
    }),
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS_DETAIL,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  cartItems: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CART_ITEMS,
      auth: true,
      contract: {
        body: validateCartItemsCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCartItemsCreate,
      },
    }),
    update: endpoint({
      method: 'PATCH',
      path: API_ENDPOINTS.CART_ITEM,
      auth: true,
      contract: {
        body: validateCartItemsUpdatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCartItemsUpdate,
      },
    }),
    remove: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART_ITEM,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  cart: {
    delete: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART,
      auth: true,
      contract: {
        response: validateCartResponse,
      },
    }),
  },
  cartPromo: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CART_PROMO,
      auth: true,
      contract: {
        body: validateCartPromoCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCartPromoCreate,
      },
    }),
    delete: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.CART_PROMO,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  checkout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.CHECKOUT,
      auth: true,
      contract: {
        body: validateCheckoutCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiCheckoutCreate,
      },
    }),
  },
  buyNow: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.BUY_NOW,
      auth: true,
      contract: {
        body: validateBuyNowCreatePayload,
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
        body: toApiBuyNowCreate,
      },
    }),
  },
  keranjang: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.KERANJANG,
      auth: true,
      contract: {
        response: validateOrderResource,
      },
      mapper: {
        response: toOrderResourceRead,
      },
    }),
  },
  wishlist: {
    list: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.WISHLIST,
      auth: true,
      contract: {
        response: validateWishlistListResponse,
      },
      mapper: {
        response: toWishlistListResponseRead,
      },
    }),
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.WISHLIST,
      auth: true,
      contract: {
        body: validateWishlistCreatePayload,
        response: validateWishlistCreateResponse,
      },
      mapper: {
        body: toApiWishlistCreate,
      },
    }),
    remove: endpoint({
      method: 'DELETE',
      path: API_ENDPOINTS.WISHLIST_PRODUK_ITEM_ID,
      auth: true,
      contract: {
        response: validateWishlistRemoveResponse,
      },
    }),
  },
  payment: {
    post: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.PAYMENT_ORDER_ID,
      auth: true,
      contract: {
        body: validatePaymentCreatePayload,
        response: validatePaymentResource,
      },
      mapper: {
        response: toPaymentResourceRead,
        body: toApiPaymentCreate,
      },
    }),
  },
  ordersInvoice: {
    get: endpoint({
      method: 'GET',
      path: API_ENDPOINTS.ORDERS_DETAIL_INVOICE,
      auth: true,
    }),
  },
  logout: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.LOGOUT,
      auth: true,
      contract: {
        response: validateLogoutResponse,
      },
    }),
  },
  adminProduk: {
    create: endpoint({
      method: 'POST',
      path: API_ENDPOINTS.ADMIN_PRODUK,
      auth: true,
      contract: {
        body: validateAdminProdukCreatePayload,
        response: validateProdukItemResource,
      },
      mapper: {
        response: toProdukItemResourceRead,
        body: toApiAdminProdukCreate,
      },
    }),
  },
})

export default api
