// Auto-generated by routesync. Do not edit manually.
// Generated at: 2026-05-31T18:21:20.789Z

import { defineApi, endpoint } from 'routesync'
import { z } from 'zod'
import * as Schemas from './schemas'
export * as Schemas from './schemas'
import * as Types from './types'

export type RegisterPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.RegisterPostSchema>
  }
  response: unknown
}
export type LoginPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.LoginPostSchema>
  }
  response: unknown
}
export type OauthGetProviderRedirectContract = {
  request: {
    params: { provider: string }
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.OauthGetProviderRedirectSchema>
  }
  response: unknown
}
export type OauthGetProviderCallbackContract = {
  request: {
    params: { provider: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type OauthPostProviderCallbackContract = {
  request: {
    params: { provider: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type SocialPostLoginContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.SocialPostLoginSchema>
  }
  response: unknown
}
export type ForgotPasswordPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.ForgotPasswordPostSchema>
  }
  response: unknown
}
export type ResetPasswordPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.ResetPasswordPostSchema>
  }
  response: unknown
}
export type CategoriesGetContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type ProdukGetContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: Types.ProdukItem[]
}
export type ProdukGetIdContract = {
  request: {
    params: { id: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: Types.ProdukItem
}
export type ProdukGetIdReviewsContract = {
  request: {
    params: { id: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type ProdukPostIdReviewsContract = {
  request: {
    params: { id: string }
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.ProdukPostIdReviewsSchema>
  }
  response: unknown
}
export type PaymentPostWebhookContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type PaymentPostOrderIdContract = {
  request: {
    params: { orderId: string }
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.PaymentPostOrderIdSchema>
  }
  response: unknown
}
export type ProfileGetContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type ProfilePutContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.ProfilePutSchema>
  }
  response: unknown
}
export type ProfilePatchContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.ProfilePatchSchema>
  }
  response: unknown
}
export type OrdersGetContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type OrdersGetIdContract = {
  request: {
    params: { id: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type OrdersGetIdInvoiceContract = {
  request: {
    params: { id: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type CartPostItemsContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.CartPostItemsSchema>
  }
  response: unknown
}
export type CartPatchItemsProdukItemIdContract = {
  request: {
    params: { produkItemId: string }
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.CartPatchItemsProdukItemIdSchema>
  }
  response: unknown
}
export type CartDeleteItemsProdukItemIdContract = {
  request: {
    params: { produkItemId: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type CartDeleteContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type CartPostPromoContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.CartPostPromoSchema>
  }
  response: unknown
}
export type CartDeletePromoContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type CheckoutPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.CheckoutPostSchema>
  }
  response: unknown
}
export type BuyNowPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.BuyNowPostSchema>
  }
  response: unknown
}
export type KeranjangGetContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type WishlistGetContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: Types.ProdukItem[]
}
export type WishlistPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.WishlistPostSchema>
  }
  response: unknown
}
export type WishlistDeleteProdukItemIdContract = {
  request: {
    params: { produkItemId: string }
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type LogoutPostContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body?: unknown
  }
  response: unknown
}
export type AdminPostProdukContract = {
  request: {
    params?: unknown
    query?: Record<string, unknown>
    body: z.infer<typeof Schemas.AdminPostProdukSchema>
  }
  response: unknown
}

export const api = defineApi({
  register: {
    post: endpoint<RegisterPostContract['response'], RegisterPostContract['request']['params'], RegisterPostContract['request']['body']>({
      method: 'POST',
      path: '/register',
      schema: {
        body: Schemas.RegisterPostSchema
      },
    }),
  },
  login: {
    post: endpoint<LoginPostContract['response'], LoginPostContract['request']['params'], LoginPostContract['request']['body']>({
      method: 'POST',
      path: '/login',
      schema: {
        body: Schemas.LoginPostSchema
      },
    }),
  },
  oauth: {
    getProviderRedirect: endpoint<OauthGetProviderRedirectContract['response'], OauthGetProviderRedirectContract['request']['params'], OauthGetProviderRedirectContract['request']['body']>({
      method: 'GET',
      path: '/oauth/:provider/redirect',
      schema: {
        body: Schemas.OauthGetProviderRedirectSchema
      },
    }),
    getProviderCallback: endpoint<OauthGetProviderCallbackContract['response'], OauthGetProviderCallbackContract['request']['params'], OauthGetProviderCallbackContract['request']['body']>({
      method: 'GET',
      path: '/oauth/:provider/callback',
    }),
    postProviderCallback: endpoint<OauthPostProviderCallbackContract['response'], OauthPostProviderCallbackContract['request']['params'], OauthPostProviderCallbackContract['request']['body']>({
      method: 'POST',
      path: '/oauth/:provider/callback',
    }),
  },
  social: {
    postLogin: endpoint<SocialPostLoginContract['response'], SocialPostLoginContract['request']['params'], SocialPostLoginContract['request']['body']>({
      method: 'POST',
      path: '/social/login',
      schema: {
        body: Schemas.SocialPostLoginSchema
      },
    }),
  },
  forgotPassword: {
    post: endpoint<ForgotPasswordPostContract['response'], ForgotPasswordPostContract['request']['params'], ForgotPasswordPostContract['request']['body']>({
      method: 'POST',
      path: '/forgot-password',
      schema: {
        body: Schemas.ForgotPasswordPostSchema
      },
    }),
  },
  resetPassword: {
    post: endpoint<ResetPasswordPostContract['response'], ResetPasswordPostContract['request']['params'], ResetPasswordPostContract['request']['body']>({
      method: 'POST',
      path: '/reset-password',
      schema: {
        body: Schemas.ResetPasswordPostSchema
      },
    }),
  },
  categories: {
    get: endpoint<CategoriesGetContract['response'], CategoriesGetContract['request']['params'], CategoriesGetContract['request']['body']>({
      method: 'GET',
      path: '/categories',
    }),
  },
  produk: {
    get: endpoint<ProdukGetContract['response'], ProdukGetContract['request']['params'], ProdukGetContract['request']['body']>({
      method: 'GET',
      path: '/produk',
    }),
    getId: endpoint<ProdukGetIdContract['response'], ProdukGetIdContract['request']['params'], ProdukGetIdContract['request']['body']>({
      method: 'GET',
      path: '/produk/:id',
    }),
    getIdReviews: endpoint<ProdukGetIdReviewsContract['response'], ProdukGetIdReviewsContract['request']['params'], ProdukGetIdReviewsContract['request']['body']>({
      method: 'GET',
      path: '/produk/:id/reviews',
    }),
    postIdReviews: endpoint<ProdukPostIdReviewsContract['response'], ProdukPostIdReviewsContract['request']['params'], ProdukPostIdReviewsContract['request']['body']>({
      method: 'POST',
      path: '/produk/:id/reviews',
      auth: true,
      schema: {
        body: Schemas.ProdukPostIdReviewsSchema
      },
    }),
  },
  payment: {
    postWebhook: endpoint<PaymentPostWebhookContract['response'], PaymentPostWebhookContract['request']['params'], PaymentPostWebhookContract['request']['body']>({
      method: 'POST',
      path: '/payment/webhook',
    }),
    postOrderId: endpoint<PaymentPostOrderIdContract['response'], PaymentPostOrderIdContract['request']['params'], PaymentPostOrderIdContract['request']['body']>({
      method: 'POST',
      path: '/payment/:orderId',
      auth: true,
      schema: {
        body: Schemas.PaymentPostOrderIdSchema
      },
    }),
  },
  profile: {
    get: endpoint<ProfileGetContract['response'], ProfileGetContract['request']['params'], ProfileGetContract['request']['body']>({
      method: 'GET',
      path: '/profile',
      auth: true,
    }),
    put: endpoint<ProfilePutContract['response'], ProfilePutContract['request']['params'], ProfilePutContract['request']['body']>({
      method: 'PUT',
      path: '/profile',
      auth: true,
      schema: {
        body: Schemas.ProfilePutSchema
      },
    }),
    patch: endpoint<ProfilePatchContract['response'], ProfilePatchContract['request']['params'], ProfilePatchContract['request']['body']>({
      method: 'PATCH',
      path: '/profile',
      auth: true,
      schema: {
        body: Schemas.ProfilePatchSchema
      },
    }),
  },
  orders: {
    get: endpoint<OrdersGetContract['response'], OrdersGetContract['request']['params'], OrdersGetContract['request']['body']>({
      method: 'GET',
      path: '/orders',
      auth: true,
    }),
    getId: endpoint<OrdersGetIdContract['response'], OrdersGetIdContract['request']['params'], OrdersGetIdContract['request']['body']>({
      method: 'GET',
      path: '/orders/:id',
      auth: true,
    }),
    getIdInvoice: endpoint<OrdersGetIdInvoiceContract['response'], OrdersGetIdInvoiceContract['request']['params'], OrdersGetIdInvoiceContract['request']['body']>({
      method: 'GET',
      path: '/orders/:id/invoice',
      auth: true,
    }),
  },
  cart: {
    postItems: endpoint<CartPostItemsContract['response'], CartPostItemsContract['request']['params'], CartPostItemsContract['request']['body']>({
      method: 'POST',
      path: '/cart/items',
      auth: true,
      schema: {
        body: Schemas.CartPostItemsSchema
      },
    }),
    patchItemsProdukItemId: endpoint<CartPatchItemsProdukItemIdContract['response'], CartPatchItemsProdukItemIdContract['request']['params'], CartPatchItemsProdukItemIdContract['request']['body']>({
      method: 'PATCH',
      path: '/cart/items/:produkItemId',
      auth: true,
      schema: {
        body: Schemas.CartPatchItemsProdukItemIdSchema
      },
    }),
    deleteItemsProdukItemId: endpoint<CartDeleteItemsProdukItemIdContract['response'], CartDeleteItemsProdukItemIdContract['request']['params'], CartDeleteItemsProdukItemIdContract['request']['body']>({
      method: 'DELETE',
      path: '/cart/items/:produkItemId',
      auth: true,
    }),
    delete: endpoint<CartDeleteContract['response'], CartDeleteContract['request']['params'], CartDeleteContract['request']['body']>({
      method: 'DELETE',
      path: '/cart',
      auth: true,
    }),
    postPromo: endpoint<CartPostPromoContract['response'], CartPostPromoContract['request']['params'], CartPostPromoContract['request']['body']>({
      method: 'POST',
      path: '/cart/promo',
      auth: true,
      schema: {
        body: Schemas.CartPostPromoSchema
      },
    }),
    deletePromo: endpoint<CartDeletePromoContract['response'], CartDeletePromoContract['request']['params'], CartDeletePromoContract['request']['body']>({
      method: 'DELETE',
      path: '/cart/promo',
      auth: true,
    }),
  },
  checkout: {
    post: endpoint<CheckoutPostContract['response'], CheckoutPostContract['request']['params'], CheckoutPostContract['request']['body']>({
      method: 'POST',
      path: '/checkout',
      auth: true,
      schema: {
        body: Schemas.CheckoutPostSchema
      },
    }),
  },
  buyNow: {
    post: endpoint<BuyNowPostContract['response'], BuyNowPostContract['request']['params'], BuyNowPostContract['request']['body']>({
      method: 'POST',
      path: '/buy-now',
      auth: true,
      schema: {
        body: Schemas.BuyNowPostSchema
      },
    }),
  },
  keranjang: {
    get: endpoint<KeranjangGetContract['response'], KeranjangGetContract['request']['params'], KeranjangGetContract['request']['body']>({
      method: 'GET',
      path: '/keranjang',
      auth: true,
    }),
  },
  wishlist: {
    get: endpoint<WishlistGetContract['response'], WishlistGetContract['request']['params'], WishlistGetContract['request']['body']>({
      method: 'GET',
      path: '/wishlist',
      auth: true,
    }),
    post: endpoint<WishlistPostContract['response'], WishlistPostContract['request']['params'], WishlistPostContract['request']['body']>({
      method: 'POST',
      path: '/wishlist',
      auth: true,
      schema: {
        body: Schemas.WishlistPostSchema
      },
    }),
    deleteProdukItemId: endpoint<WishlistDeleteProdukItemIdContract['response'], WishlistDeleteProdukItemIdContract['request']['params'], WishlistDeleteProdukItemIdContract['request']['body']>({
      method: 'DELETE',
      path: '/wishlist/:produkItemId',
      auth: true,
    }),
  },
  logout: {
    post: endpoint<LogoutPostContract['response'], LogoutPostContract['request']['params'], LogoutPostContract['request']['body']>({
      method: 'POST',
      path: '/logout',
      auth: true,
    }),
  },
  admin: {
    postProduk: endpoint<AdminPostProdukContract['response'], AdminPostProdukContract['request']['params'], AdminPostProdukContract['request']['body']>({
      method: 'POST',
      path: '/admin/produk',
      auth: true,
      schema: {
        body: Schemas.AdminPostProdukSchema
      },
    }),
  },
})

export default api