// Auto-generated by routesync. Do not edit manually.

/* =========================
   APPLICATION CONSTANTS
========================= */

export const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost/api'

export const API_ENDPOINTS = {
  ADMIN_PRODUK: '/admin/produk',
  BUY_NOW: '/buy-now',
  CART: '/cart',
  CART_ITEMS: '/cart/items',
  CART_ITEM: (produkItemId: string | number) => `/cart/items/${produkItemId}`,
  CART_PROMO: '/cart/promo',
  CATEGORIES: '/categories',
  CHECKOUT: '/checkout',
  FORGOT_PASSWORD: '/forgot-password',
  KERANJANG: '/keranjang',
  LOGIN: '/login',
  LOGOUT: '/logout',
  OAUTH_PROVIDER_CALLBACK: (provider: string | number) => `/oauth/${provider}/callback`,
  OAUTH_PROVIDER_REDIRECT: (provider: string | number) => `/oauth/${provider}/redirect`,
  ORDERS: '/orders',
  ORDERS_DETAIL: (id: string | number) => `/orders/${id}`,
  ORDERS_DETAIL_INVOICE: (id: string | number) => `/orders/${id}/invoice`,
  PAYMENT_ORDER_ID: (orderId: string | number) => `/payment/${orderId}`,
  PAYMENT_WEBHOOK: '/payment/webhook',
  PRODUK: '/produk',
  PRODUK_DETAIL: (id: string | number) => `/produk/${id}`,
  PRODUK_DETAIL_REVIEWS: (id: string | number) => `/produk/${id}/reviews`,
  PROFILE: '/profile',
  REGISTER: '/register',
  RESET_PASSWORD: '/reset-password',
  SOCIAL_LOGIN: '/social/login',
  WISHLIST: '/wishlist',
  WISHLIST_PRODUK_ITEM_ID: (produkItemId: string | number) => `/wishlist/${produkItemId}`,
} as const

export const ROUTES = {
  HOME: '/',
  OAUTH_DETAIL_REDIRECT: (provider: string | number) => `/oauth/${provider}/redirect`,
  OAUTH_DETAIL_CALLBACK: (provider: string | number) => `/oauth/${provider}/callback`,
  CATEGORIES: '/categories',
  PRODUK: '/produk',
  PRODUK_DETAIL: (id: string | number) => `/produk/${id}`,
  PRODUK_DETAIL_REVIEWS: (id: string | number) => `/produk/${id}/reviews`,
  PROFILE: '/profile',
  ORDERS: '/orders',
  ORDERS_DETAIL: (id: string | number) => `/orders/${id}`,
  KERANJANG: '/keranjang',
  WISHLIST: '/wishlist',
  ORDERS_DETAIL_INVOICE: (id: string | number) => `/orders/${id}/invoice`,
} as const

export const Enums = {
  Order: {
    Status: {
      PENDING: 'pending',
      PAID: 'paid',
      CANCELED: 'canceled',
    } as const,
  },
  OrderFinancial: {
    FinancialStatus: {
      PENDING: 'pending',
      PAID: 'paid',
      PARTIALLY_REFUNDED: 'partially_refunded',
      REFUNDED: 'refunded',
      FAILED: 'failed',
      CANCELLED: 'cancelled',
    } as const,
  },
  OrderFulfillment: {
    FulfillmentStatus: {
      UNFULFILLED: 'unfulfilled',
      PROCESSING: 'processing',
      SHIPPED: 'shipped',
      COMPLETED: 'completed',
      CANCELLED: 'cancelled',
      RETURNED: 'returned',
    } as const,
  },
  Payment: {
    Status: {
      PENDING: 'pending',
      SUCCESS: 'success',
      FAILED: 'failed',
    } as const,
    Provider: {
      MOCK: 'mock',
      MIDTRANS: 'midtrans',
    } as const,
  },
  PromoCode: {
    DiscountType: {
      FIXED_MINOR: 'fixed_minor',
      PERCENT: 'percent',
    } as const,
  },
  User: {
    Role: {
      ADMIN: 'admin',
      USER: 'user',
    } as const,
  },
  Social: {
    Provider: {
      GOOGLE: 'google',
      FACEBOOK: 'facebook',
      APPLE: 'apple',
    } as const,
  },
} as const

export type OrderStatus = (typeof Enums.Order.Status)[keyof typeof Enums.Order.Status]
export type OrderFinancialFinancialStatus = (typeof Enums.OrderFinancial.FinancialStatus)[keyof typeof Enums.OrderFinancial.FinancialStatus]
export type OrderFulfillmentFulfillmentStatus = (typeof Enums.OrderFulfillment.FulfillmentStatus)[keyof typeof Enums.OrderFulfillment.FulfillmentStatus]
export type PaymentStatus = (typeof Enums.Payment.Status)[keyof typeof Enums.Payment.Status]
export type PaymentProvider = (typeof Enums.Payment.Provider)[keyof typeof Enums.Payment.Provider]
export type PromoCodeDiscountType = (typeof Enums.PromoCode.DiscountType)[keyof typeof Enums.PromoCode.DiscountType]
export type UserRole = (typeof Enums.User.Role)[keyof typeof Enums.User.Role]
export type SocialProvider = (typeof Enums.Social.Provider)[keyof typeof Enums.Social.Provider]
