// Auto-generated by routesync. Do not edit manually.

import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { api } from './api'

export function useRegisterPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.register.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['register'] })
    }
  })
}

export function useLoginPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.login.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['login'] })
    }
  })
}

export function useOauthGetProviderRedirect(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['oauth', 'getProviderRedirect'],
    queryFn: () => api.oauth.getProviderRedirect({ query: params })
  })
}

export function useOauthGetProviderCallback(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['oauth', 'getProviderCallback'],
    queryFn: () => api.oauth.getProviderCallback({ query: params })
  })
}

export function useOauthPostProviderCallback() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.oauth.postProviderCallback({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['oauth'] })
    }
  })
}

export function useSocialPostLogin() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.social.postLogin({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['social'] })
    }
  })
}

export function useForgotPasswordPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.forgotPassword.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['forgotPassword'] })
    }
  })
}

export function useResetPasswordPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.resetPassword.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['resetPassword'] })
    }
  })
}

export function useCategoriesGet(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['categories', 'get'],
    queryFn: () => api.categories.get({ query: params })
  })
}

export function useProdukGet(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['produk', 'get'],
    queryFn: () => api.produk.get({ query: params })
  })
}

export function useProdukGetId(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['produk', 'getId'],
    queryFn: () => api.produk.getId({ query: params })
  })
}

export function useProdukGetIdReviews(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['produk', 'getIdReviews'],
    queryFn: () => api.produk.getIdReviews({ query: params })
  })
}

export function useProdukPostIdReviews() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.produk.postIdReviews({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['produk'] })
    }
  })
}

export function usePaymentPostWebhook() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.payment.postWebhook({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['payment'] })
    }
  })
}

export function usePaymentPostOrderId() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.payment.postOrderId({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['payment'] })
    }
  })
}

export function useProfileGet(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['profile', 'get'],
    queryFn: () => api.profile.get({ query: params })
  })
}

export function useProfilePut() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.profile.put({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['profile'] })
    }
  })
}

export function useProfilePatch() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.profile.patch({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['profile'] })
    }
  })
}

export function useOrdersGet(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['orders', 'get'],
    queryFn: () => api.orders.get({ query: params })
  })
}

export function useOrdersGetId(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['orders', 'getId'],
    queryFn: () => api.orders.getId({ query: params })
  })
}

export function useOrdersGetIdInvoice(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['orders', 'getIdInvoice'],
    queryFn: () => api.orders.getIdInvoice({ query: params })
  })
}

export function useCartPostItems() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.cart.postItems({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cart'] })
    }
  })
}

export function useCartPatchItemsProdukItemId() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.cart.patchItemsProdukItemId({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cart'] })
    }
  })
}

export function useCartDeleteItemsProdukItemId() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.cart.deleteItemsProdukItemId({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cart'] })
    }
  })
}

export function useCartDelete() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.cart.delete({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cart'] })
    }
  })
}

export function useCartPostPromo() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.cart.postPromo({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cart'] })
    }
  })
}

export function useCartDeletePromo() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.cart.deletePromo({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['cart'] })
    }
  })
}

export function useCheckoutPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.checkout.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['checkout'] })
    }
  })
}

export function useBuyNowPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.buyNow.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['buyNow'] })
    }
  })
}

export function useKeranjangGet(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['keranjang', 'get'],
    queryFn: () => api.keranjang.get({ query: params })
  })
}

export function useWishlistGet(params?: Record<string, unknown>) {
  return useQuery({
    queryKey: ['wishlist', 'get'],
    queryFn: () => api.wishlist.get({ query: params })
  })
}

export function useWishlistPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.wishlist.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['wishlist'] })
    }
  })
}

export function useWishlistDeleteProdukItemId() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.wishlist.deleteProdukItemId({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['wishlist'] })
    }
  })
}

export function useLogoutPost() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.logout.post({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['logout'] })
    }
  })
}

export function useAdminPostProduk() {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: (data: Record<string, unknown>) => api.admin.postProduk({ body: data }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['admin'] })
    }
  })
}
