// Auto-generated by routesync. Do not edit manually.

import { defineHooks } from 'routesync/react'
import { api } from './api'
import { QueryKey } from './query-key'
import type {
  AdminProdukForm,
  BuyNowForm,
  CartItemsForm,
  CartPromoForm,
  CategoryIndex,
  CheckoutForm,
  ForgotPasswordForm,
  LoginForm,
  OauthRedirectForm,
  OrderResourceIndex,
  OrderResourceShow,
  ProdukItemResourceIndex,
  ProdukItemResourceShow,
  RegisterForm,
  ResetPasswordForm,
  SocialLoginForm,
  WishlistForm,
} from './types/index'
import type {
  PaymentPostPayload,
  ProdukReviewsPostPayload,
  ProfileListResponse,
} from './contract/api-contract'

export const typeOf = <T>() => ({} as T)

export const hooks = defineHooks({
  register: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<RegisterForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.register,
    actionKeys: {
      create: QueryKey.register.create,
    },
    endpoint: api.register,
  },
  login: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<LoginForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.login,
    actionKeys: {
      create: QueryKey.login.create,
    },
    endpoint: api.login,
  },
  oauthRedirect: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<OauthRedirectForm['Get']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.oauthRedirect,
    actionKeys: {
      get: QueryKey.oauthRedirect.get,
    },
    endpoint: api.oauthRedirect,
  },
  oauthCallback: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.oauthCallback,
    actionKeys: {
      get: QueryKey.oauthCallback.get,
      post: QueryKey.oauthCallback.post,
    },
    endpoint: api.oauthCallback,

    cache: {
      post: {
        invalidate: [
          QueryKey.oauthCallback.get,
        ],
      },
    },
  },
  socialLogin: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<SocialLoginForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.socialLogin,
    actionKeys: {
      create: QueryKey.socialLogin.create,
    },
    endpoint: api.socialLogin,
  },
  forgotPassword: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<ForgotPasswordForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.forgotPassword,
    actionKeys: {
      create: QueryKey.forgotPassword.create,
    },
    endpoint: api.forgotPassword,
  },
  resetPassword: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<ResetPasswordForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.resetPassword,
    actionKeys: {
      create: QueryKey.resetPassword.create,
    },
    endpoint: api.resetPassword,
  },
  categories: {
    types: {
      list: typeOf<CategoryIndex>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.categories,
    actionKeys: {
      list: QueryKey.categories.list,
    },
    endpoint: api.categories,

    cache: {
      list: QueryKey.categories.list,
    },
  },
  produk: {
    types: {
      list: typeOf<ProdukItemResourceIndex>(),
      detail: typeOf<ProdukItemResourceShow>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.produk,
    actionKeys: {
      list: QueryKey.produk.list,
      get: QueryKey.produk.get,
    },
    endpoint: api.produk,

    cache: {
      list: QueryKey.produk.lists,
      detail: QueryKey.produk.detail,
    },
  },
  produkReviews: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<ProdukReviewsPostPayload>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.produkReviews,
    actionKeys: {
      get: QueryKey.produkReviews.get,
      post: QueryKey.produkReviews.post,
    },
    endpoint: api.produkReviews,

    cache: {
      post: {
        invalidate: [
          QueryKey.produkReviews.get,
        ],
      },
    },
  },
  paymentWebhook: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.paymentWebhook,
    actionKeys: {
      create: QueryKey.paymentWebhook.create,
    },
    endpoint: api.paymentWebhook,
  },
  profile: {
    types: {
      list: typeOf<ProfileListResponse>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.profile,
    actionKeys: {
      list: QueryKey.profile.list,
      put: QueryKey.profile.put,
      patch: QueryKey.profile.patch,
    },
    endpoint: api.profile,

    cache: {
      list: QueryKey.profile.list,
      put: {
        invalidate: [
          QueryKey.profile.list,
        ],
      },
      patch: {
        invalidate: [
          QueryKey.profile.list,
        ],
      },
    },
  },
  orders: {
    types: {
      list: typeOf<OrderResourceIndex>(),
      detail: typeOf<OrderResourceShow>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.orders,
    actionKeys: {
      list: QueryKey.orders.list,
      get: QueryKey.orders.get,
    },
    endpoint: api.orders,

    cache: {
      list: QueryKey.orders.lists,
      detail: QueryKey.orders.detail,
    },
  },
  cartItems: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<CartItemsForm['Create']>(),
      update: typeOf<CartItemsForm['Update']>(),
    },

    queryKey: QueryKey.cartItems,
    actionKeys: {
      create: QueryKey.cartItems.create,
      update: QueryKey.cartItems.update,
      remove: QueryKey.cartItems.remove,
    },
    endpoint: api.cartItems,

    cache: {
      create: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
      update: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
      remove: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
    },
  },
  cart: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.cart,
    actionKeys: {
      delete: QueryKey.cart.delete,
    },
    endpoint: api.cart,

    cache: {
      delete: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
    },
  },
  cartPromo: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<CartPromoForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.cartPromo,
    actionKeys: {
      create: QueryKey.cartPromo.create,
      delete: QueryKey.cartPromo.delete,
    },
    endpoint: api.cartPromo,

    cache: {
      create: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
      delete: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
    },
  },
  checkout: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<CheckoutForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.checkout,
    actionKeys: {
      create: QueryKey.checkout.create,
    },
    endpoint: api.checkout,

    cache: {
      create: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
    },
  },
  buyNow: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<BuyNowForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.buyNow,
    actionKeys: {
      create: QueryKey.buyNow.create,
    },
    endpoint: api.buyNow,

    cache: {
      create: {
        invalidate: [
          QueryKey.keranjang.list,
          QueryKey.orders.lists,
        ],
      },
    },
  },
  keranjang: {
    types: {
      list: typeOf<OrderResourceShow>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.keranjang,
    actionKeys: {
      list: QueryKey.keranjang.list,
    },
    endpoint: api.keranjang,

    cache: {
      list: QueryKey.keranjang.list,
    },
  },
  wishlist: {
    types: {
      list: typeOf<ProdukItemResourceIndex>(),
      detail: typeOf<never>(),
      create: typeOf<WishlistForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.wishlist,
    actionKeys: {
      list: QueryKey.wishlist.list,
      create: QueryKey.wishlist.create,
      remove: QueryKey.wishlist.remove,
    },
    endpoint: api.wishlist,

    cache: {
      list: QueryKey.wishlist.list,
      create: {
        invalidate: [
          QueryKey.wishlist.list,
        ],
      },
      remove: {
        invalidate: [
          QueryKey.wishlist.list,
        ],
      },
    },
  },
  payment: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<PaymentPostPayload>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.payment,
    actionKeys: {
      post: QueryKey.payment.post,
    },
    endpoint: api.payment,

    cache: {
      post: {
        invalidate: [
          QueryKey.orders.lists,
          QueryKey.keranjang.list,
        ],
      },
    },
  },
  ordersInvoice: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.ordersInvoice,
    actionKeys: {
      get: QueryKey.ordersInvoice.get,
    },
    endpoint: api.ordersInvoice,
  },
  logout: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<never>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.logout,
    actionKeys: {
      create: QueryKey.logout.create,
    },
    endpoint: api.logout,
  },
  adminProduk: {
    types: {
      list: typeOf<never>(),
      detail: typeOf<never>(),
      create: typeOf<AdminProdukForm['Create']>(),
      update: typeOf<never>(),
    },

    queryKey: QueryKey.adminProduk,
    actionKeys: {
      create: QueryKey.adminProduk.create,
    },
    endpoint: api.adminProduk,

    cache: {
      create: {
        invalidate: [
          QueryKey.produk.lists,
        ],
      },
    },
  },
})

export const useRegister = hooks.register
export const useLogin = hooks.login
export const useOauthRedirect = hooks.oauthRedirect
export const useOauthCallback = hooks.oauthCallback
export const useSocialLogin = hooks.socialLogin
export const useForgotPassword = hooks.forgotPassword
export const useResetPassword = hooks.resetPassword
export const useCategories = hooks.categories
export const useProduk = hooks.produk
export const useProdukReviews = hooks.produkReviews
export const usePaymentWebhook = hooks.paymentWebhook
export const useProfile = hooks.profile
export const useOrders = hooks.orders
export const useCartItems = hooks.cartItems
export const useCart = hooks.cart
export const useCartPromo = hooks.cartPromo
export const useCheckout = hooks.checkout
export const useBuyNow = hooks.buyNow
export const useKeranjang = hooks.keranjang
export const useWishlist = hooks.wishlist
export const usePayment = hooks.payment
export const useOrdersInvoice = hooks.ordersInvoice
export const useLogout = hooks.logout
export const useAdminProduk = hooks.adminProduk

export * from './query-key'
