// Auto-generated by routesync. Do not edit manually.

import { useApiQuery, useApiMutation } from 'routesync/react'
import { api } from './api'

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.register.post, options)` for future compatibility.
 */
export function useRegisterPost() {
  return useApiMutation(api.register.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.login.post, options)` for future compatibility.
 */
export function useLoginPost() {
  return useApiMutation(api.login.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.oauth.getProviderRedirect, ...args)` for future compatibility.
 */
export function useOauthGetProviderRedirect(...args: [options: import('./api').OauthGetProviderRedirectContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').OauthGetProviderRedirectContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').OauthGetProviderRedirectContract['response'], import('./api').OauthGetProviderRedirectContract['request']['params'], import('./api').OauthGetProviderRedirectContract['request']['body'], import('./types').ApiError>(api.oauth.getProviderRedirect, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.oauth.getProviderCallback, ...args)` for future compatibility.
 */
export function useOauthGetProviderCallback(...args: [options: import('./api').OauthGetProviderCallbackContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').OauthGetProviderCallbackContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').OauthGetProviderCallbackContract['response'], import('./api').OauthGetProviderCallbackContract['request']['params'], import('./api').OauthGetProviderCallbackContract['request']['body'], import('./types').ApiError>(api.oauth.getProviderCallback, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.oauth.postProviderCallback, options)` for future compatibility.
 */
export function useOauthPostProviderCallback() {
  return useApiMutation(api.oauth.postProviderCallback)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.social.postLogin, options)` for future compatibility.
 */
export function useSocialPostLogin() {
  return useApiMutation(api.social.postLogin)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.forgotPassword.post, options)` for future compatibility.
 */
export function useForgotPasswordPost() {
  return useApiMutation(api.forgotPassword.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.resetPassword.post, options)` for future compatibility.
 */
export function useResetPasswordPost() {
  return useApiMutation(api.resetPassword.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.categories.get, ...args)` for future compatibility.
 */
export function useCategoriesGet(...args: [options?: import('./api').CategoriesGetContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').CategoriesGetContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').CategoriesGetContract['response'], import('./api').CategoriesGetContract['request']['params'], import('./api').CategoriesGetContract['request']['body'], import('./types').ApiError>(api.categories.get, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.produk.get, ...args)` for future compatibility.
 */
export function useProdukGet(...args: [options?: import('./api').ProdukGetContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').ProdukGetContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').ProdukGetContract['response'], import('./api').ProdukGetContract['request']['params'], import('./api').ProdukGetContract['request']['body'], import('./types').ApiError>(api.produk.get, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.produk.getId, ...args)` for future compatibility.
 */
export function useProdukGetId(...args: [options: import('./api').ProdukGetIdContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').ProdukGetIdContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').ProdukGetIdContract['response'], import('./api').ProdukGetIdContract['request']['params'], import('./api').ProdukGetIdContract['request']['body'], import('./types').ApiError>(api.produk.getId, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.produk.getIdReviews, ...args)` for future compatibility.
 */
export function useProdukGetIdReviews(...args: [options: import('./api').ProdukGetIdReviewsContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').ProdukGetIdReviewsContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').ProdukGetIdReviewsContract['response'], import('./api').ProdukGetIdReviewsContract['request']['params'], import('./api').ProdukGetIdReviewsContract['request']['body'], import('./types').ApiError>(api.produk.getIdReviews, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.produk.postIdReviews, options)` for future compatibility.
 */
export function useProdukPostIdReviews() {
  return useApiMutation(api.produk.postIdReviews)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.payment.postWebhook, options)` for future compatibility.
 */
export function usePaymentPostWebhook() {
  return useApiMutation(api.payment.postWebhook)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.payment.postOrderId, options)` for future compatibility.
 */
export function usePaymentPostOrderId() {
  return useApiMutation(api.payment.postOrderId)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.profile.get, ...args)` for future compatibility.
 */
export function useProfileGet(...args: [options?: import('./api').ProfileGetContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').ProfileGetContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').ProfileGetContract['response'], import('./api').ProfileGetContract['request']['params'], import('./api').ProfileGetContract['request']['body'], import('./types').ApiError>(api.profile.get, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.profile.put, options)` for future compatibility.
 */
export function useProfilePut() {
  return useApiMutation(api.profile.put)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.profile.patch, options)` for future compatibility.
 */
export function useProfilePatch() {
  return useApiMutation(api.profile.patch)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.orders.get, ...args)` for future compatibility.
 */
export function useOrdersGet(...args: [options?: import('./api').OrdersGetContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').OrdersGetContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').OrdersGetContract['response'], import('./api').OrdersGetContract['request']['params'], import('./api').OrdersGetContract['request']['body'], import('./types').ApiError>(api.orders.get, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.orders.getId, ...args)` for future compatibility.
 */
export function useOrdersGetId(...args: [options: import('./api').OrdersGetIdContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').OrdersGetIdContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').OrdersGetIdContract['response'], import('./api').OrdersGetIdContract['request']['params'], import('./api').OrdersGetIdContract['request']['body'], import('./types').ApiError>(api.orders.getId, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.orders.getIdInvoice, ...args)` for future compatibility.
 */
export function useOrdersGetIdInvoice(...args: [options: import('./api').OrdersGetIdInvoiceContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').OrdersGetIdInvoiceContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').OrdersGetIdInvoiceContract['response'], import('./api').OrdersGetIdInvoiceContract['request']['params'], import('./api').OrdersGetIdInvoiceContract['request']['body'], import('./types').ApiError>(api.orders.getIdInvoice, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.cart.postItems, options)` for future compatibility.
 */
export function useCartPostItems() {
  return useApiMutation(api.cart.postItems)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.cart.patchItemsProdukItemId, options)` for future compatibility.
 */
export function useCartPatchItemsProdukItemId() {
  return useApiMutation(api.cart.patchItemsProdukItemId)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.cart.deleteItemsProdukItemId, options)` for future compatibility.
 */
export function useCartDeleteItemsProdukItemId() {
  return useApiMutation(api.cart.deleteItemsProdukItemId)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.cart.delete, options)` for future compatibility.
 */
export function useCartDelete() {
  return useApiMutation(api.cart.delete)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.cart.postPromo, options)` for future compatibility.
 */
export function useCartPostPromo() {
  return useApiMutation(api.cart.postPromo)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.cart.deletePromo, options)` for future compatibility.
 */
export function useCartDeletePromo() {
  return useApiMutation(api.cart.deletePromo)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.checkout.post, options)` for future compatibility.
 */
export function useCheckoutPost() {
  return useApiMutation(api.checkout.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.buyNow.post, options)` for future compatibility.
 */
export function useBuyNowPost() {
  return useApiMutation(api.buyNow.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.keranjang.get, ...args)` for future compatibility.
 */
export function useKeranjangGet(...args: [options?: import('./api').KeranjangGetContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').KeranjangGetContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').KeranjangGetContract['response'], import('./api').KeranjangGetContract['request']['params'], import('./api').KeranjangGetContract['request']['body'], import('./types').ApiError>(api.keranjang.get, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiQuery(api.wishlist.get, ...args)` for future compatibility.
 */
export function useWishlistGet(...args: [options?: import('./api').WishlistGetContract['request'], queryOptions?: import('routesync/react').ApiQueryOptions<import('./api').WishlistGetContract['response'], import('./types').ApiError>]) {
  const [options, queryOptions] = args
  return useApiQuery<import('./api').WishlistGetContract['response'], import('./api').WishlistGetContract['request']['params'], import('./api').WishlistGetContract['request']['body'], import('./types').ApiError>(api.wishlist.get, options, queryOptions)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.wishlist.post, options)` for future compatibility.
 */
export function useWishlistPost() {
  return useApiMutation(api.wishlist.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.wishlist.deleteProdukItemId, options)` for future compatibility.
 */
export function useWishlistDeleteProdukItemId() {
  return useApiMutation(api.wishlist.deleteProdukItemId)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.logout.post, options)` for future compatibility.
 */
export function useLogoutPost() {
  return useApiMutation(api.logout.post)
}

/**
 * @deprecated Generated hooks will become optional in v2.
 * Prefer `useApiMutation(api.admin.postProduk, options)` for future compatibility.
 */
export function useAdminPostProduk() {
  return useApiMutation(api.admin.postProduk)
}
