// Auto-generated by routesync. Do not edit manually.

/* =========================
   ENTITY CONSTANTS
========================= */
export const Entity = {
  REGISTER: "register",
  LOGIN: "login",
  OAUTHREDIRECT: "oauthRedirect",
  OAUTHCALLBACK: "oauthCallback",
  SOCIALLOGIN: "socialLogin",
  FORGOTPASSWORD: "forgotPassword",
  RESETPASSWORD: "resetPassword",
  CATEGORIES: "categories",
  PRODUK: "produk",
  PRODUKREVIEWS: "produkReviews",
  PAYMENTWEBHOOK: "paymentWebhook",
  PROFILE: "profile",
  ORDERS: "orders",
  CARTITEMS: "cartItems",
  CART: "cart",
  CARTPROMO: "cartPromo",
  CHECKOUT: "checkout",
  BUYNOW: "buyNow",
  KERANJANG: "keranjang",
  WISHLIST: "wishlist",
  PAYMENT: "payment",
  ORDERSINVOICE: "ordersInvoice",
  LOGOUT: "logout",
  ADMINPRODUK: "adminProduk",
} as const

type EntityValue = (typeof Entity)[keyof typeof Entity]

/* =========================
   BASE FACTORY (GENERIC)
========================= */
const createBaseQueryKey = <T extends EntityValue>(entity: T) => ({
  all:     ()                         => [entity] as const,
  lists:   ()                         => [entity, "list"] as const,
  list:    (filters?: Record<string, unknown>) =>
             [entity, "list", filters ?? {}] as const,
  details: ()                         => [entity, "detail"] as const,
  detail:  (id: string | number)      => [entity, "detail", id] as const,
})

/* =========================
   QUERY KEY REGISTRY
========================= */
export const QueryKey = {
  /* ===== REGISTER ===== */
  register: {
    all: () => [Entity.REGISTER] as const,
  },

  /* ===== LOGIN ===== */
  login: {
    all: () => [Entity.LOGIN] as const,
  },

  /* ===== OAUTHREDIRECT ===== */
  oauthRedirect: {
    all: () => [Entity.OAUTHREDIRECT] as const,
    get: () => [Entity.OAUTHREDIRECT, "get"] as const,
  },

  /* ===== OAUTHCALLBACK ===== */
  oauthCallback: {
    all: () => [Entity.OAUTHCALLBACK] as const,
    get: () => [Entity.OAUTHCALLBACK, "get"] as const,
  },

  /* ===== SOCIALLOGIN ===== */
  socialLogin: {
    all: () => [Entity.SOCIALLOGIN] as const,
  },

  /* ===== FORGOTPASSWORD ===== */
  forgotPassword: {
    all: () => [Entity.FORGOTPASSWORD] as const,
  },

  /* ===== RESETPASSWORD ===== */
  resetPassword: {
    all: () => [Entity.RESETPASSWORD] as const,
  },

  /* ===== CATEGORIES ===== */
  categories: {
    all: () => [Entity.CATEGORIES] as const,
    list: () => [Entity.CATEGORIES, "list"] as const,
  },

  /* ===== PRODUK ===== */
  produk: {
    ...createBaseQueryKey(Entity.PRODUK),
  },

  /* ===== PRODUKREVIEWS ===== */
  produkReviews: {
    all: () => [Entity.PRODUKREVIEWS] as const,
    get: () => [Entity.PRODUKREVIEWS, "get"] as const,
  },

  /* ===== PAYMENTWEBHOOK ===== */
  paymentWebhook: {
    all: () => [Entity.PAYMENTWEBHOOK] as const,
  },

  /* ===== PROFILE ===== */
  profile: {
    all: () => [Entity.PROFILE] as const,
    list: () => [Entity.PROFILE, "list"] as const,
  },

  /* ===== ORDERS ===== */
  orders: {
    ...createBaseQueryKey(Entity.ORDERS),
  },

  /* ===== CARTITEMS ===== */
  cartItems: {
    all: () => [Entity.CARTITEMS] as const,
  },

  /* ===== CART ===== */
  cart: {
    all: () => [Entity.CART] as const,
  },

  /* ===== CARTPROMO ===== */
  cartPromo: {
    all: () => [Entity.CARTPROMO] as const,
  },

  /* ===== CHECKOUT ===== */
  checkout: {
    all: () => [Entity.CHECKOUT] as const,
  },

  /* ===== BUYNOW ===== */
  buyNow: {
    all: () => [Entity.BUYNOW] as const,
  },

  /* ===== KERANJANG ===== */
  keranjang: {
    all: () => [Entity.KERANJANG] as const,
    list: () => [Entity.KERANJANG, "list"] as const,
  },

  /* ===== WISHLIST ===== */
  wishlist: {
    all: () => [Entity.WISHLIST] as const,
    list: () => [Entity.WISHLIST, "list"] as const,
  },

  /* ===== PAYMENT ===== */
  payment: {
    all: () => [Entity.PAYMENT] as const,
  },

  /* ===== ORDERSINVOICE ===== */
  ordersInvoice: {
    all: () => [Entity.ORDERSINVOICE] as const,
    get: () => [Entity.ORDERSINVOICE, "get"] as const,
  },

  /* ===== LOGOUT ===== */
  logout: {
    all: () => [Entity.LOGOUT] as const,
  },

  /* ===== ADMINPRODUK ===== */
  adminProduk: {
    all: () => [Entity.ADMINPRODUK] as const,
  },

} as const

/* =========================
   BACKWARD COMPATIBLE EXPORTS
========================= */
export const registerKeys = QueryKey.register
export const loginKeys = QueryKey.login
export const oauthRedirectKeys = QueryKey.oauthRedirect
export const oauthCallbackKeys = QueryKey.oauthCallback
export const socialLoginKeys = QueryKey.socialLogin
export const forgotPasswordKeys = QueryKey.forgotPassword
export const resetPasswordKeys = QueryKey.resetPassword
export const categoriesKeys = QueryKey.categories
export const produkKeys = QueryKey.produk
export const produkReviewsKeys = QueryKey.produkReviews
export const paymentWebhookKeys = QueryKey.paymentWebhook
export const profileKeys = QueryKey.profile
export const ordersKeys = QueryKey.orders
export const cartItemsKeys = QueryKey.cartItems
export const cartKeys = QueryKey.cart
export const cartPromoKeys = QueryKey.cartPromo
export const checkoutKeys = QueryKey.checkout
export const buyNowKeys = QueryKey.buyNow
export const keranjangKeys = QueryKey.keranjang
export const wishlistKeys = QueryKey.wishlist
export const paymentKeys = QueryKey.payment
export const ordersInvoiceKeys = QueryKey.ordersInvoice
export const logoutKeys = QueryKey.logout
export const adminProdukKeys = QueryKey.adminProduk
