// Auto-generated by routesync. Do not edit manually.

/* =========================
   ENTITY CONSTANTS
========================= */
export const Entity = {
} as const

type EntityValue = (typeof Entity)[keyof typeof Entity]

/* =========================
   BASE FACTORY (GENERIC)
========================= */
const createBaseQueryKey = <T extends EntityValue>(entity: T) => ({
  all:     ()                         => [entity] as const,
  lists:   ()                         => [entity, "list"] as const,
  list:    (filters?: Record<string, unknown>) =>
             [entity, "list", filters ?? {}] as const,
  details: ()                         => [entity, "detail"] as const,
  detail:  (id: string | number)      => [entity, "detail", id] as const,
})

/* =========================
   QUERY KEY REGISTRY
========================= */
export const QueryKey = {
} as const

/* =========================
   BACKWARD COMPATIBLE EXPORTS
========================= */
