// Auto-generated by routesync. Do not edit manually.

import { z } from 'zod'

export const CategorySchema = z.object({
  id: z.number(),
  nama: z.string(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const OrderSchema = z.object({
  id: z.number(),
  userId: z.number(),
  totalHarga: z.number(),
  status: z.union([z.literal('pending'), z.literal('paid'), z.literal('canceled')]),
  orderNumber: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const OrderAmountSchema = z.object({
  id: z.number(),
  orderId: z.number(),
  subtotalMinor: z.number(),
  shippingMinor: z.number(),
  discountMinor: z.number(),
  taxMinor: z.number(),
  totalMinor: z.number(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const OrderDetailSchema = z.object({
  id: z.number(),
  orderId: z.number(),
  produkItemId: z.number(),
  qty: z.number(),
  harga: z.number(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
  banana: z.string().nullable(),
  potato: z.number().nullable(),
  flyingDog: z.number().nullable(),
})

export const OrderFinancialSchema = z.object({
  id: z.number(),
  orderId: z.number(),
  financialStatus: z.string(),
  refundedAt: z.string().nullable(),
  refundReason: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const OrderFulfillmentSchema = z.object({
  id: z.number(),
  orderId: z.number(),
  fulfillmentStatus: z.string(),
  processingAt: z.string().nullable(),
  shippedAt: z.string().nullable(),
  completedAt: z.string().nullable(),
  canceledAt: z.string().nullable(),
  cancelReason: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const OrderPromotionSchema = z.object({
  id: z.number(),
  orderId: z.number(),
  promoCodeId: z.number().nullable(),
  promoCode: z.string(),
  discountMinor: z.number(),
  metadata: z.record(z.string(), z.unknown()).nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const OrderShippingSchema = z.object({
  id: z.number(),
  orderId: z.number(),
  nama: z.string().nullable(),
  telepon: z.string().nullable(),
  alamat: z.string().nullable(),
  kota: z.string().nullable(),
  kodePos: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const PaymentSchema = z.object({
  id: z.number(),
  orderId: z.number(),
  metode: z.string().nullable(),
  status: z.union([z.literal('pending'), z.literal('success'), z.literal('failed')]),
  paidAt: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const PaymentAmountSchema = z.object({
  id: z.number(),
  paymentId: z.number(),
  currencyCode: z.string(),
  amountMinor: z.number(),
  feeMinor: z.number(),
  netAmountMinor: z.number(),
  refundAmountMinor: z.number(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const PaymentDetailSchema = z.object({
  id: z.number(),
  paymentId: z.number(),
  detail: z.record(z.string(), z.unknown()).nullable(),
  payloadHash: z.string().nullable(),
  payloadReceivedAt: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const PaymentGatewaySchema = z.object({
  id: z.number(),
  paymentId: z.number(),
  provider: z.string().nullable(),
  providerTxnId: z.string().nullable(),
  idempotencyKey: z.string().nullable(),
  gatewayStatus: z.string().nullable(),
  gatewayCode: z.string().nullable(),
  gatewayMessage: z.string().nullable(),
  authorizedAt: z.string().nullable(),
  capturedAt: z.string().nullable(),
  failedAt: z.string().nullable(),
  refundedAt: z.string().nullable(),
  reconciledAt: z.string().nullable(),
  reconciliationBatchId: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const ProductReviewSchema = z.object({
  id: z.number(),
  produkItemId: z.number(),
  userId: z.number(),
  rating: z.number(),
  title: z.string().nullable(),
  comment: z.string().nullable(),
  isVerifiedPurchase: z.boolean(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const ProdukItemSchema = z.object({
  id: z.number(),
  nama: z.string(),
  deskripsi: z.string().nullable(),
  categoryId: z.number().nullable(),
  harga: z.number(),
  stok: z.number(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
  image: z.unknown().optional(), // appended attribute
  imageUrl: z.unknown().optional(), // appended attribute
  categoryName: z.unknown().optional(), // appended attribute
  rating: z.unknown().optional(), // appended attribute
  reviewCount: z.unknown().optional(), // appended attribute
})

export const ProdukItemFrontendSchema = z.object({
  id: z.number(),
  produkItemId: z.number(),
  gambar: z.string().nullable(),
  rating: z.number(),
  jumlahReview: z.number(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const PromoCodeSchema = z.object({
  id: z.number(),
  code: z.string(),
  discountType: z.string(),
  discountValue: z.number(),
  maxDiscountMinor: z.number().nullable(),
  minOrderMinor: z.number(),
  usageLimit: z.number().nullable(),
  usedCount: z.number(),
  isActive: z.boolean(),
  startsAt: z.string().nullable(),
  endsAt: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const SocialAccountSchema = z.object({
  id: z.number(),
  userId: z.number(),
  provider: z.string(),
  providerUserId: z.string(),
  email: z.string().nullable(),
  avatarUrl: z.string().nullable(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const UserSchema = z.object({
  id: z.number(),
  name: z.string(),
  email: z.string(),
  password: z.string().optional(),
  role: z.union([z.literal('admin'), z.literal('user')]),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const WishlistSchema = z.object({
  id: z.number(),
  userId: z.number(),
  produkItemId: z.number(),
  createdAt: z.string().nullable(),
  updatedAt: z.string().nullable(),
})

export const RegisterResponseSchema = z.object({
  success: z.boolean(),
  message: z.string(),
  data: z.string().nullable(),
})

export const RegisterPostSchema = z.object({
  name: z.string(),
  email: z.string(),
  password: z.string(),
})

export const LoginPostSchema = z.object({
  email: z.string(),
  password: z.string(),
})

export const OauthGetProviderRedirectSchema = z.object({
  redirectTo: z.string().optional().nullable(),
})

export const SocialPostLoginSchema = z.object({
  provider: z.string(),
  providerUserId: z.string(),
  email: z.string(),
  name: z.string().optional().nullable(),
  avatarUrl: z.string().optional().nullable(),
})

export const ForgotPasswordPostSchema = z.object({
  email: z.string(),
})

export const ResetPasswordPostSchema = z.object({
  email: z.string(),
  token: z.string(),
  password: z.string(),
})

export const ProdukPostIdReviewsSchema = z.object({
  rating: z.number(),
  title: z.string().optional().nullable(),
  comment: z.string().optional().nullable(),
})

export const PaymentPostOrderIdSchema = z.object({
  metode: z.string(),
  detail: z.array(z.unknown()).optional().nullable(),
  provider: z.string().optional().nullable(),
  providerTxnId: z.string().optional().nullable(),
  idempotencyKey: z.string().optional().nullable(),
  gatewayCode: z.string().optional().nullable(),
  gatewayMessage: z.string().optional().nullable(),
})

export const ProfilePutSchema = z.object({
  name: z.string(),
  email: z.string(),
})

export const ProfilePatchSchema = z.object({
  name: z.string(),
  email: z.string(),
})

export const CartPostItemsSchema = z.object({
  produkItemId: z.string(),
  qty: z.number(),
})

export const CartPatchItemsProdukItemIdSchema = z.object({
  qty: z.number(),
})

export const CartPostPromoSchema = z.object({
  code: z.string(),
})

export const CheckoutPostSchema = z.object({
  items: z.array(z.unknown()).optional(),
  "items.*.produkItemId": z.string(),
  "items.*.qty": z.number(),
  shippingNama: z.string().optional().nullable(),
  shippingTelepon: z.string().optional().nullable(),
  shippingAlamat: z.string().optional().nullable(),
  shippingKota: z.string().optional().nullable(),
  shippingKodePos: z.string().optional().nullable(),
})

export const BuyNowPostSchema = z.object({
  produkItemId: z.string(),
  qty: z.number(),
  shippingNama: z.string().optional().nullable(),
  shippingTelepon: z.string().optional().nullable(),
  shippingAlamat: z.string().optional().nullable(),
  shippingKota: z.string().optional().nullable(),
  shippingKodePos: z.string().optional().nullable(),
})

export const WishlistPostSchema = z.object({
  produkItemId: z.string(),
})

export const AdminPostProdukSchema = z.object({
  nama: z.string(),
  deskripsi: z.string().optional().nullable(),
  gambar: z.string().optional().nullable(),
  categoryId: z.string(),
  harga: z.number(),
  stok: z.number(),
  rating: z.number().optional().nullable(),
  jumlahReview: z.number().optional().nullable(),
})
