// Auto-generated by routesync. Do not edit manually.

export interface ApiResponse<T = unknown> {
  success: boolean
  message?: string
  data: T
  meta?: PaginationMeta
}

export interface PaginationMeta {
  current_page: number
  last_page: number
  per_page: number
  total: number
}

export interface ApiError {
  success: false
  message: string
  errors?: Record<string, string[]>
  status?: number
}

export interface Register {
  id: number
  // TODO: Add register fields
  createdAt?: string
  updatedAt?: string
}

export interface Login {
  id: number
  // TODO: Add login fields
  createdAt?: string
  updatedAt?: string
}

export interface Oauth {
  id: number
  // TODO: Add oauth fields
  createdAt?: string
  updatedAt?: string
}

export interface Social {
  id: number
  // TODO: Add social fields
  createdAt?: string
  updatedAt?: string
}

export interface ForgotPassword {
  id: number
  // TODO: Add forgot-password fields
  createdAt?: string
  updatedAt?: string
}

export interface ResetPassword {
  id: number
  // TODO: Add reset-password fields
  createdAt?: string
  updatedAt?: string
}

export interface Categories {
  id: number
  // TODO: Add categories fields
  createdAt?: string
  updatedAt?: string
}

export interface Produk {
  id: number
  // TODO: Add produk fields
  createdAt?: string
  updatedAt?: string
}

export interface Payment {
  id: number
  // TODO: Add payment fields
  createdAt?: string
  updatedAt?: string
}

export interface Profile {
  id: number
  // TODO: Add profile fields
  createdAt?: string
  updatedAt?: string
}

export interface Orders {
  id: number
  // TODO: Add orders fields
  createdAt?: string
  updatedAt?: string
}

export interface Cart {
  id: number
  // TODO: Add cart fields
  createdAt?: string
  updatedAt?: string
}

export interface Checkout {
  id: number
  // TODO: Add checkout fields
  createdAt?: string
  updatedAt?: string
}

export interface BuyNow {
  id: number
  // TODO: Add buy-now fields
  createdAt?: string
  updatedAt?: string
}

export interface Keranjang {
  id: number
  // TODO: Add keranjang fields
  createdAt?: string
  updatedAt?: string
}

export interface Wishlist {
  id: number
  // TODO: Add wishlist fields
  createdAt?: string
  updatedAt?: string
}

export interface Logout {
  id: number
  // TODO: Add logout fields
  createdAt?: string
  updatedAt?: string
}

export interface Admin {
  id: number
  // TODO: Add admin fields
  createdAt?: string
  updatedAt?: string
}
