// Auto-generated by routesync. Do not edit manually.

export interface ApiResponse<T = unknown> {
  success: boolean
  message?: string
  data: T
  meta?: PaginationMeta
}

export interface PaginationMeta {
  current_page: number
  last_page: number
  per_page: number
  total: number
}

export interface ApiError {
  success: false
  message: string
  errors?: Record<string, string[]>
  status?: number
}
