// Auto-generated by routesync. Do not edit manually.

import { z } from 'zod'

export interface ApiResponse<T = unknown> {
  success: boolean
  message?: string
  data: T
  meta?: PaginationMeta
}

export interface PaginationMeta {
  current_page: number
  last_page: number
  per_page: number
  total: number
}

export interface ApiError {
  success: false
  message: string
  errors?: Record<string, string[]>
  status?: number
}

export interface Register {
  id: number
  // TODO: Add register fields
  created_at?: string
  updated_at?: string
}

export interface Login {
  id: number
  // TODO: Add login fields
  created_at?: string
  updated_at?: string
}

export interface Oauth {
  id: number
  // TODO: Add oauth fields
  created_at?: string
  updated_at?: string
}

export interface Social {
  id: number
  // TODO: Add social fields
  created_at?: string
  updated_at?: string
}

export interface ForgotPassword {
  id: number
  // TODO: Add forgot-password fields
  created_at?: string
  updated_at?: string
}

export interface ResetPassword {
  id: number
  // TODO: Add reset-password fields
  created_at?: string
  updated_at?: string
}

export interface Categories {
  id: number
  // TODO: Add categories fields
  created_at?: string
  updated_at?: string
}

export interface Produk {
  id: number
  // TODO: Add produk fields
  created_at?: string
  updated_at?: string
}

export interface Payment {
  id: number
  // TODO: Add payment fields
  created_at?: string
  updated_at?: string
}

export interface Profile {
  id: number
  // TODO: Add profile fields
  created_at?: string
  updated_at?: string
}

export interface Orders {
  id: number
  // TODO: Add orders fields
  created_at?: string
  updated_at?: string
}

export interface Cart {
  id: number
  // TODO: Add cart fields
  created_at?: string
  updated_at?: string
}

export interface Checkout {
  id: number
  // TODO: Add checkout fields
  created_at?: string
  updated_at?: string
}

export interface BuyNow {
  id: number
  // TODO: Add buy-now fields
  created_at?: string
  updated_at?: string
}

export interface Keranjang {
  id: number
  // TODO: Add keranjang fields
  created_at?: string
  updated_at?: string
}

export interface Wishlist {
  id: number
  // TODO: Add wishlist fields
  created_at?: string
  updated_at?: string
}

export interface Logout {
  id: number
  // TODO: Add logout fields
  created_at?: string
  updated_at?: string
}

export interface Admin {
  id: number
  // TODO: Add admin fields
  created_at?: string
  updated_at?: string
}

export const profilePutSchema = z.object({
  rules: z.string().optional(),
})
export type ProfilePutPayload = z.infer<typeof profilePutSchema>

export const profilePatchSchema = z.object({
  rules: z.string().optional(),
})
export type ProfilePatchPayload = z.infer<typeof profilePatchSchema>

export const cartPostSchema = z.object({
  rules: z.string().optional(),
})
export type CartPostPayload = z.infer<typeof cartPostSchema>

export const cartPatchSchema = z.object({
  rules: z.string().optional(),
})
export type CartPatchPayload = z.infer<typeof cartPatchSchema>

export const checkoutPostSchema = z.object({
  rules: z.string().optional(),
})
export type CheckoutPostPayload = z.infer<typeof checkoutPostSchema>

export const buyNowPostSchema = z.object({
  rules: z.string().optional(),
})
export type BuyNowPostPayload = z.infer<typeof buyNowPostSchema>

export const paymentPostSchema = z.object({
  rules: z.string().optional(),
})
export type PaymentPostPayload = z.infer<typeof paymentPostSchema>
