// Auto-generated by routesync. Do not edit manually.

export type RegisterForm = {
  Create: {
    name: string
    email: string
    password: string
  }
}

export type LoginForm = {
  Create: {
    email: string
    password: string
  }
}

export type OauthRedirectForm = {
  Get: {
    redirectTo?: string | undefined | null
  }
}

export type SocialLoginForm = {
  Create: {
    provider: 'google' | 'facebook' | 'apple'
    providerUserId: string
    email: string
    name?: string | undefined | null
    avatarUrl?: string | undefined | null
  }
}

export type ForgotPasswordForm = {
  Create: {
    email: string
  }
}

export type ResetPasswordForm = {
  Create: {
    email: string
    token: string
    password: string
  }
}

export type ProdukReviewsForm = {
  Create: {
    rating: number
    title?: string | undefined | null
    comment?: string | undefined | null
  }
}

export type ProfileForm = {
  Update: {
    name: string
    email: string
  }
}

export type CartItemsForm = {
  Create: {
    produkItemId: string
    qty: number
  }

  Update: {
    qty: number
  }
}

export type CartPromoForm = {
  Create: {
    code: string
  }
}

export type CheckoutForm = {
  Create: {
    items?: {
    produkItemId: string
    qty: number
  }[] | undefined
    shippingNama?: string | undefined | null
    shippingTelepon?: string | undefined | null
    shippingAlamat?: string | undefined | null
    shippingKota?: string | undefined | null
    shippingKodePos?: string | undefined | null
  }
}

export type BuyNowForm = {
  Create: {
    produkItemId: string
    qty: number
    shippingNama?: string | undefined | null
    shippingTelepon?: string | undefined | null
    shippingAlamat?: string | undefined | null
    shippingKota?: string | undefined | null
    shippingKodePos?: string | undefined | null
  }
}

export type WishlistForm = {
  Create: {
    produkItemId: string
  }
}

export type PaymentForm = {
  Create: {
    metode: string
    detail?: unknown[] | undefined | null
    provider?: 'mock' | 'midtrans' | undefined | null
    providerTxnId?: string | undefined | null
    idempotencyKey?: string | undefined | null
    gatewayCode?: string | undefined | null
    gatewayMessage?: string | undefined | null
  }
}

export type AdminProdukForm = {
  Create: {
    nama: string
    deskripsi?: string | undefined | null
    gambar?: string | undefined | null
    categoryId: string
    harga: number
    stok: number
    rating?: number | undefined | null
    jumlahReview?: number | undefined | null
  }
}
