// Auto-generated by routesync. Do not edit manually.

export interface CategoryTransformed {
  id: number
  nama: string
  createdAt: string | null
  updatedAt: string | null
}

export type CategoryShow = CategoryTransformed
export type CategoryIndex = CategoryTransformed[]

export interface OrderTransformed {
  id: number
  userId: number
  totalHarga: number
  status: "pending" | "paid" | "canceled"
  orderNumber: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type OrderShow = OrderTransformed
export type OrderIndex = OrderTransformed[]

export interface OrderAmountTransformed {
  id: number
  orderId: number
  subtotalMinor: number
  shippingMinor: number
  discountMinor: number
  taxMinor: number
  totalMinor: number
  createdAt: string | null
  updatedAt: string | null
}

export type OrderAmountShow = OrderAmountTransformed
export type OrderAmountIndex = OrderAmountTransformed[]

export interface OrderDetailTransformed {
  id: number
  orderId: number
  produkItemId: number
  qty: number
  harga: number
  createdAt: string | null
  updatedAt: string | null
  banana: string | null
  potato: number | null
  flyingDog: boolean | null
}

export type OrderDetailShow = OrderDetailTransformed
export type OrderDetailIndex = OrderDetailTransformed[]

export interface OrderFinancialTransformed {
  id: number
  orderId: number
  financialStatus: string
  refundedAt: string | null
  refundReason: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type OrderFinancialShow = OrderFinancialTransformed
export type OrderFinancialIndex = OrderFinancialTransformed[]

export interface OrderFulfillmentTransformed {
  id: number
  orderId: number
  fulfillmentStatus: string
  processingAt: string | null
  shippedAt: string | null
  completedAt: string | null
  canceledAt: string | null
  cancelReason: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type OrderFulfillmentShow = OrderFulfillmentTransformed
export type OrderFulfillmentIndex = OrderFulfillmentTransformed[]

export interface OrderPromotionTransformed {
  id: number
  orderId: number
  promoCodeId: number | null
  promoCode: string
  discountMinor: number
  metadata: Record<string, unknown> | null
  createdAt: string | null
  updatedAt: string | null
}

export type OrderPromotionShow = OrderPromotionTransformed
export type OrderPromotionIndex = OrderPromotionTransformed[]

export interface OrderShippingTransformed {
  id: number
  orderId: number
  nama: string | null
  telepon: string | null
  alamat: string | null
  kota: string | null
  kodePos: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type OrderShippingShow = OrderShippingTransformed
export type OrderShippingIndex = OrderShippingTransformed[]

export interface PaymentTransformed {
  id: number
  orderId: number
  metode: string | null
  status: "pending" | "success" | "failed"
  paidAt: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type PaymentShow = PaymentTransformed
export type PaymentIndex = PaymentTransformed[]

export interface PaymentAmountTransformed {
  id: number
  paymentId: number
  currencyCode: string
  amountMinor: number
  feeMinor: number
  netAmountMinor: number
  refundAmountMinor: number
  createdAt: string | null
  updatedAt: string | null
}

export type PaymentAmountShow = PaymentAmountTransformed
export type PaymentAmountIndex = PaymentAmountTransformed[]

export interface PaymentDetailTransformed {
  id: number
  paymentId: number
  detail: Record<string, unknown> | null
  payloadHash: string | null
  payloadReceivedAt: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type PaymentDetailShow = PaymentDetailTransformed
export type PaymentDetailIndex = PaymentDetailTransformed[]

export interface PaymentGatewayTransformed {
  id: number
  paymentId: number
  provider: string | null
  providerTxnId: string | null
  idempotencyKey: string | null
  gatewayStatus: string | null
  gatewayCode: string | null
  gatewayMessage: string | null
  authorizedAt: string | null
  capturedAt: string | null
  failedAt: string | null
  refundedAt: string | null
  reconciledAt: string | null
  reconciliationBatchId: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type PaymentGatewayShow = PaymentGatewayTransformed
export type PaymentGatewayIndex = PaymentGatewayTransformed[]

export interface ProductReviewTransformed {
  id: number
  produkItemId: number
  userId: number
  rating: number
  title: string | null
  comment: string | null
  isVerifiedPurchase: boolean
  createdAt: string | null
  updatedAt: string | null
}

export type ProductReviewShow = ProductReviewTransformed
export type ProductReviewIndex = ProductReviewTransformed[]

export interface ProdukItemTransformed {
  id: number
  nama: string
  deskripsi: string | null
  categoryId: number | null
  harga: number
  stok: number
  createdAt: string | null
  updatedAt: string | null
  image?: string // appended
  imageUrl?: string // appended
  categoryName?: string // appended
  rating?: number // appended
  reviewCount?: number // appended
}

export type ProdukItemShow = ProdukItemTransformed
export type ProdukItemIndex = ProdukItemTransformed[]

export interface ProdukItemFrontendTransformed {
  id: number
  produkItemId: number
  gambar: string | null
  rating: number
  jumlahReview: number
  createdAt: string | null
  updatedAt: string | null
}

export type ProdukItemFrontendShow = ProdukItemFrontendTransformed
export type ProdukItemFrontendIndex = ProdukItemFrontendTransformed[]

export interface PromoCodeTransformed {
  id: number
  code: string
  discountType: string
  discountValue: number
  maxDiscountMinor: number | null
  minOrderMinor: number
  usageLimit: number | null
  usedCount: number
  isActive: boolean
  startsAt: string | null
  endsAt: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type PromoCodeShow = PromoCodeTransformed
export type PromoCodeIndex = PromoCodeTransformed[]

export interface SocialAccountTransformed {
  id: number
  userId: number
  provider: string
  providerUserId: string
  email: string | null
  avatarUrl: string | null
  createdAt: string | null
  updatedAt: string | null
}

export type SocialAccountShow = SocialAccountTransformed
export type SocialAccountIndex = SocialAccountTransformed[]

export interface UserTransformed {
  id: number
  name: string
  email: string
  role: "admin" | "user"
  createdAt: string | null
  updatedAt: string | null
}

export type UserShow = UserTransformed
export type UserIndex = UserTransformed[]

export interface WishlistTransformed {
  id: number
  userId: number
  produkItemId: number
  createdAt: string | null
  updatedAt: string | null
}

export type WishlistShow = WishlistTransformed
export type WishlistIndex = WishlistTransformed[]

export interface RegisterResponseTransformed {
  success: boolean
  message: string
  data: unknown | null
}

export type RegisterResponseShow = RegisterResponseTransformed
export type RegisterResponseIndex = RegisterResponseTransformed[]

export interface OrderDetailResourceTransformed {
  id: number
  produkItemId: number
  produk?: { id: number; nama: string; gambar: (string) | null; imageUrl: string }
  qty: number
  harga: number
  subtotal: number
  banana: (string) | null
  potato: (number) | null
  flyingDog: (boolean) | null
  foo: unknown
}

export type OrderDetailResourceShow = OrderDetailResourceTransformed
export type OrderDetailResourceIndex = OrderDetailResourceTransformed[]

export interface OrderResourceTransformed {
  id: number
  status: string
  totalHarga: number
  invoiceNumber: (string) | null
  paymentStatus: string
  financialStatus: string
  fulfillmentStatus: string
  subtotalMinor: number
  discountMinor: number
  shippingMinor: number
  taxMinor: number
  totalHargaMinor: number
  items?: OrderDetailResourceTransformed[]
  promotion?: { code: string; discountMinor: number }
  shipping?: { nama: (string) | null; telepon: (string) | null; alamat: (string) | null; kota: (string) | null; kodePos: (string) | null }
  createdAt: string
}

export type OrderResourceShow = OrderResourceTransformed
export type OrderResourceIndex = OrderResourceTransformed[]

export interface PaymentResourceTransformed {
  id: number
  orderId: number
  invoiceNumber: (string) | null
  metode: (string) | null
  detail: (unknown) | null
  status: string
  paidAt: (string) | null
  provider: string
  providerTxnId: string
  gatewayStatus: string
  amountMinor: number
  refundAmountMinor: unknown
  items?: OrderDetailResourceTransformed[]
  promotion?: { code: string; discountMinor: number }
  gateway?: { name: null; orderId: null; token: null; redirectUrl: null }
  totalHarga: number
}

export type PaymentResourceShow = PaymentResourceTransformed
export type PaymentResourceIndex = PaymentResourceTransformed[]

export interface ProdukItemResourceTransformed {
  id: number
  nama: string
  deskripsi: (string) | null
  image: (string) | null
  imageUrl: string
  categoryId: (number) | null
  categoryName: string
  harga: number
  stok: number
  rating: number
  reviewCount: number
}

export type ProdukItemResourceShow = ProdukItemResourceTransformed
export type ProdukItemResourceIndex = ProdukItemResourceTransformed[]
