// Auto-generated by routesync. Do not edit manually.

export type RegisterForm = {
  Post: {
    name: string
    email: string
    password: string
  }
}

export type LoginForm = {
  Post: {
    email: string
    password: string
  }
}

export type OauthForm = {
  GetProviderRedirect: {
    redirectTo?: string | undefined | null
  }
}

export type SocialForm = {
  PostLogin: {
    provider: 'google' | 'facebook' | 'apple'
    providerUserId: string
    email: string
    name?: string | undefined | null
    avatarUrl?: string | undefined | null
  }
}

export type ForgotPasswordForm = {
  Post: {
    email: string
  }
}

export type ResetPasswordForm = {
  Post: {
    email: string
    token: string
    password: string
  }
}

export type ProdukForm = {
  PostIdReviews: {
    rating: number
    title?: string | undefined | null
    comment?: string | undefined | null
  }
}

export type PaymentForm = {
  PostOrderId: {
    metode: string
    detail?: unknown[] | undefined | null
    provider?: 'mock' | 'midtrans' | undefined | null
    providerTxnId?: string | undefined | null
    idempotencyKey?: string | undefined | null
    gatewayCode?: string | undefined | null
    gatewayMessage?: string | undefined | null
  }
}

export type ProfileForm = {
  Put: {
    name: string
    email: string
  }

  Patch: {
    name: string
    email: string
  }
}

export type CartForm = {
  PostItems: {
    produkItemId: string
    qty: number
  }

  PatchItemsProdukItemId: {
    qty: number
  }

  PostPromo: {
    code: string
  }
}

export type CheckoutForm = {
  Post: {
    items?: {
    produkItemId: string
    qty: number
  }[] | undefined
    shippingNama?: string | undefined | null
    shippingTelepon?: string | undefined | null
    shippingAlamat?: string | undefined | null
    shippingKota?: string | undefined | null
    shippingKodePos?: string | undefined | null
  }
}

export type BuyNowForm = {
  Post: {
    produkItemId: string
    qty: number
    shippingNama?: string | undefined | null
    shippingTelepon?: string | undefined | null
    shippingAlamat?: string | undefined | null
    shippingKota?: string | undefined | null
    shippingKodePos?: string | undefined | null
  }
}

export type WishlistForm = {
  Post: {
    produkItemId: string
  }
}

export type AdminForm = {
  PostProduk: {
    nama: string
    deskripsi?: string | undefined | null
    gambar?: string | undefined | null
    categoryId: string
    harga: number
    stok: number
    rating?: number | undefined | null
    jumlahReview?: number | undefined | null
  }
}
