// Auto-generated by routesync. Do not edit manually.

export interface ApiResponse<T = unknown> {
  success: boolean
  message?: string
  data: T
  meta?: PaginationMeta
}

export interface PaginationMeta {
  current_page: number
  from: number
  last_page: number
  path: string
  per_page: number
  to: number
  total: number
}

export interface PaginatedResponse<T> {
  data: T[]
  links: { first: string, last: string, prev: string | null, next: string | null }
  meta: PaginationMeta
}

export interface ApiError {
  success: false
  message: string
  errors?: Record<string, string[]>
  status?: number
}

export interface Category {
  id: number
  nama: string
  created_at: string | null
  updated_at: string | null
}

export interface Order {
  id: number
  user_id: number
  total_harga: number
  status: string
  order_number: string | null
  created_at: string | null
  updated_at: string | null
}

export interface OrderAmount {
  id: number
  order_id: number
  subtotal_minor: number
  shipping_minor: number
  discount_minor: number
  tax_minor: number
  total_minor: number
  created_at: string | null
  updated_at: string | null
  subtotal?: number
  shipping?: number
  discount?: number
  tax?: number
  total?: number
}

export interface OrderDetail {
  id: number
  order_id: number
  produk_item_id: number
  qty: number
  harga: number
  created_at: string | null
  updated_at: string | null
  banana: string | null
  potato: number | null
  flying_dog: boolean | null
  foo?: unknown
}

export interface OrderFinancial {
  id: number
  order_id: number
  financial_status: string
  refunded_at: string | null
  refund_reason: string | null
  created_at: string | null
  updated_at: string | null
}

export interface OrderFulfillment {
  id: number
  order_id: number
  fulfillment_status: string
  processing_at: string | null
  shipped_at: string | null
  completed_at: string | null
  canceled_at: string | null
  cancel_reason: string | null
  created_at: string | null
  updated_at: string | null
}

export interface OrderPromotion {
  id: number
  order_id: number
  promo_code_id: number | null
  promo_code: string
  discount_minor: number
  metadata: unknown | null
  created_at: string | null
  updated_at: string | null
}

export interface OrderShipping {
  id: number
  order_id: number
  nama: string | null
  telepon: string | null
  alamat: string | null
  kota: string | null
  kode_pos: string | null
  created_at: string | null
  updated_at: string | null
}

export interface Payment {
  id: number
  order_id: number
  metode: string | null
  status: string
  paid_at: string | null
  created_at: string | null
  updated_at: string | null
  gatewayStatus?: string
  amountMinor?: number
  providerTxnId?: string
  provider?: string
  refundAmountMinor?: unknown
  foo?: unknown
  bar?: unknown
}

export interface PaymentAmount {
  id: number
  payment_id: number
  currency_code: string
  amount_minor: number
  fee_minor: number
  net_amount_minor: number
  refund_amount_minor: number
  created_at: string | null
  updated_at: string | null
}

export interface PaymentDetail {
  id: number
  payment_id: number
  detail: unknown | null
  payload_hash: string | null
  payload_received_at: string | null
  created_at: string | null
  updated_at: string | null
}

export interface PaymentGateway {
  id: number
  payment_id: number
  provider: string | null
  provider_txn_id: string | null
  idempotency_key: string | null
  gateway_status: string | null
  gateway_code: string | null
  gateway_message: string | null
  authorized_at: string | null
  captured_at: string | null
  failed_at: string | null
  refunded_at: string | null
  reconciled_at: string | null
  reconciliation_batch_id: string | null
  created_at: string | null
  updated_at: string | null
}

export interface ProductReview {
  id: number
  produk_item_id: number
  user_id: number
  rating: number
  title: string | null
  comment: string | null
  is_verified_purchase: boolean
  created_at: string | null
  updated_at: string | null
}

export interface ProdukItem {
  id: number
  nama: string
  deskripsi: string | null
  category_id: number | null
  harga: number
  stok: number
  created_at: string | null
  updated_at: string | null
  image?: string
  image_url?: string
  category_name?: string
  rating?: number
  review_count?: number
}

export interface ProdukItemFrontend {
  id: number
  produk_item_id: number
  gambar: string | null
  rating: number
  jumlah_review: number
  created_at: string | null
  updated_at: string | null
}

export interface PromoCode {
  id: number
  code: string
  discount_type: string
  discount_value: number
  max_discount_minor: number | null
  min_order_minor: number
  usage_limit: number | null
  used_count: number
  is_active: boolean
  starts_at: string | null
  ends_at: string | null
  created_at: string | null
  updated_at: string | null
}

export interface SocialAccount {
  id: number
  user_id: number
  provider: string
  provider_user_id: string
  email: string | null
  avatar_url: string | null
  created_at: string | null
  updated_at: string | null
}

export interface User {
  id: number
  name: string
  email: string
  role: string
  created_at: string | null
  updated_at: string | null
  use_factory?: unknown
}

export interface Wishlist {
  id: number
  user_id: number
  produk_item_id: number
  created_at: string | null
  updated_at: string | null
}

export interface RegisterResponse {
  success: boolean
  message: string
  data: unknown | null
}


export * from './api-read'
export * from './api-form'